### ISSUE TITLE
Footer:  Help link is broken

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#10]
The "Help" link at the right of the footer does not work.

It should be grayed out or removed until it is functional.

![screen shot 2017-10-04 at 11 25 13 am](https://user-images.githubusercontent.com/13629122/31184191-b7d28f94-a8f6-11e7-881f-c5f59862283c.png)
![screen shot 2017-10-04 at 11 25 05 am](https://user-images.githubusercontent.com/13629122/31184190-b7bf2bf2-a8f6-11e7-9ee5-63e7966d082a.png)

**Comment by cneidle** [comment]
Actually, I see that there really is a Help function!  Clicking on "Help" from the Sign Bank brings the user to this page: http://dai.cs.rutgers.edu/dai/s/help   

I had not seen that before.

I will have some suggestions for the text on that page.  I'll send those separately.   It also includes descriptions of some functionalities that have not been implemented yet...

**Comment by kwasiopoku** [comment]
Got it.  I will update the help links to point to http://dai.cs.rutgers.edu/dai/s/help

**Comment by kwasiopoku** [comment]
@cneidle  This is fixed and pushed to prod.  Please very and close ticket or let me know if the fix looks good and I will close the ticket

**Comment by cneidle** [comment]
Yes - this now links to the help page (which itself still needs to be modified, as per my email yesterday). Thanks.
