### ISSUE TITLE
Frame being displayed in Utterance view - which frame and why?

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#100]
Just sent email about this.

The frame being displayed for each utterance is not the first frame; compare below.

Not sure how the frame is being chosen.

?

<img width="815" alt="screen shot 2018-07-24 at 3 26 31 pm" src="https://user-images.githubusercontent.com/13629122/43161497-478d9f34-8f56-11e8-869e-0f024ff190f6.png">

**Comment by kwasiopoku** [comment]
As discussed, this is because the thumbnail generation estimates the best quality frame based on the frame transitions so the thumbnail is not necessarily the first frame
