### ISSUE TITLE
Alignment issue:  Relative clause marking extends systematically by a few too many characters

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#101]
Hi,

It looks like you are not properly calculating the length of the "rel-cl" label.  The line for that seems to extend several characters too far, systematically.

<img width="866" alt="screen shot 2018-07-31 at 7 38 09 am" src="https://user-images.githubusercontent.com/13629122/43457449-e48168a0-9494-11e8-8b4c-5a3303473e85.png">

For example, the relative clause line should end before WOW starts; it should be right-aligned with ...GIVE-1p.

<img width="725" alt="screen shot 2018-07-31 at 7 39 56 am" src="https://user-images.githubusercontent.com/13629122/43457474-f99ae5ae-9494-11e8-888c-cc2a63c5b237.png">

**Comment by cneidle** [comment]
AH - I see the problem:  The field identifier label "relative clause" on the left is too long and pushes everything else in that row over too far to the right.   You could abbreviate that as "relative cl." if that would help...

**Comment by kwasiopoku** [comment]
Fixed
