### ISSUE TITLE
Utterance videos not right - File 107

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#102]
For 107 - 

U1 utterance videos fail to play.  Also U4 and U5 and U6 and U7 and U8. 

(U2 and U3 are OK)

Something is obviously very wrong…

Just fyi.

Thanks,
 Carol

On Aug 2, 2018, at 10:09 AM, Carol Neidle <carolneidle@mac.com> wrote:

Hi Augustine,

The utterances for file 107 don’t play at all.  The “utterance” videos seem to contain 
just a few frames each.

**Comment by kwasiopoku** [comment]
Fixed
