### ISSUE TITLE
+'s internal to compounds should be ignored for classification

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#119]
Just as we disregard the number of +s at the end of a sign for purposes of classification, so we should disregard extra +s at the end of a part of a compound.

So these two are really instances of the same compound, COP+RESEARCH:

<img width="165" alt="Screen Shot 2019-06-28 at 9 50 02 AM" src="https://user-images.githubusercontent.com/13629122/60346968-590be880-998a-11e9-8b3e-847b4c0e5e47.png">

**Comment by cneidle** [comment]
Also, they should be disregarded for distinguishing variants of a given compound - both of these should be
grouped under

     BOY+CORRECT

<img width="146" alt="Screen Shot 2019-06-30 at 6 23 42 PM" src="https://user-images.githubusercontent.com/13629122/60402931-5369fa80-9b64-11e9-93d4-edee6b559600.png">

another example just like that one

<img width="152" alt="Screen Shot 2019-06-30 at 6 55 39 PM" src="https://user-images.githubusercontent.com/13629122/60403246-bcec0800-9b68-11e9-9054-17aa1d926507.png">

**Comment by kwasiopoku** [comment]
Fixed
