### ISSUE TITLE
Sign Bank - Full set of options for viewing not available if selection is made from list on the left

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#12]
If I search for ACCEPT, this is what I see:

![screen shot 2017-10-04 at 1 22 27 pm](https://user-images.githubusercontent.com/13629122/31189793-3c603ddc-a907-11e7-94df-98d5cdbea30d.png)

but if I select ACCEPT from the left, I see this:

![screen shot 2017-10-04 at 1 22 39 pm](https://user-images.githubusercontent.com/13629122/31189833-5f32b402-a907-11e7-9db9-c7b1007f12c2.png)

Presumably, I should be able to see the other occurrences and the composite video regardless of what means I used to display the result, no?

**Comment by kwasiopoku** [comment]
Fixed
