### ISSUE TITLE
Handshapes not showing up in Sign Bank

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#121]
<img width="798" alt="Screen Shot 2019-06-30 at 8 01 00 AM" src="https://user-images.githubusercontent.com/13629122/60396286-60a7ca80-9b0d-11e9-82c8-73025ed9a17c.png">

**Comment by kwasiopoku** [comment]
Issue is related to the exported signbank.  Handshape labels with slashes when exported do not link bank to correct handshape

**Comment by kwasiopoku** [comment]
This has been resolved.
<img width="926" alt="Screen Shot 2019-09-10 at 7 12 31 AM" src="https://user-images.githubusercontent.com/10775608/64609227-7a318200-d39a-11e9-8fbd-5f7d6a37d289.png">
