### ISSUE TITLE
Double-clicking on the highest-level entries in the sign bank does not work properly

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#122]
Hi,

Clicking on, e.g., BALL (4) below brings up a functional window, but clicking on BALL
brings up what you see below.

Should clicking on the main entry be disabled from having any effect ? 

Thanks!

<img width="83" alt="Screen Shot 2019-06-30 at 6 16 56 PM" src="https://user-images.githubusercontent.com/13629122/60402873-60d2b500-9b63-11e9-908c-852f50aa90c8.png">

<img width="505" alt="Screen Shot 2019-06-30 at 6 15 34 PM" src="https://user-images.githubusercontent.com/13629122/60402878-65976900-9b63-11e9-8396-52c96f9e0461.png">

**Comment by kwasiopoku** [comment]
Plan is to disable double clicking of the primary entry

**Comment by kwasiopoku** [comment]
Fixed
