### ISSUE TITLE
Correction needed to ASLLVD entries:  BEFORE

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#123]
I sent you email about this; just making a ticket for it.

In the ASLLVD, we had BEFORE_2 as a main entry.
BEFORE occurs in the continuing signing data.

We need for BEFORE to be the main entry, with BEFORE_2 as a variant under that:

BEFORE
    BEFORE                [example to be incorporated from the new data]
    BEFORE_2 (4)
    BEFORE_2* (BEFORE_2+SCHOOL) (4)

Thank you !!!

**Comment by kwasiopoku** [comment]
Fixed
