### ISSUE TITLE
Correction needed to ASLLVD entries - sorry!  BUSY and BUSINESS

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#124]
Hi Augustine,  There is some inconsistency in the listings for BUSY and BUSINESS.
Here is what will need to be done to fix it:  

**Signs labeled as BUSINESS_2 - need to be changed to BUSINESS:**
   1766  BUSINESS_2++   -->  BUSINESS++
   1765  BUSINESS_2++   -->  BUSINESS++
**Signs labeled as BUSINESS_3 - need to be changed to BUSINESS_2 (without the +):**
   1767 BUSINESS_3+  -->  BUSINESS_2
**Signs labeled as BUSY_2 - need to be changed to BUSY (but we will eliminate the +s):**
   1770 BUSY_2++  -->  BUSY
   1769 BUSY_2++  -->  BUSY
   1771 BUSY_2+++  -->  BUSY
**Signs labeled as BUSY_3 - need to be changed to BUSY_2 (note additional suffix):**
   1772 BUSY_3++++ --> BUSY_2-continuative
**Signs labeled as either BUSY or BUSINESS will need to be changed to BUSY/BUSINESS:**
    1763 BUSINESS  --> BUSY/BUSINESS
    1764 BUSINESS+ --> BUSY/BUSINESS+
    1768 BUSY + --> BUSY/BUSINESS+

**However this one should stay as it is:**
    17631 BUSY

SO sorry for the inconvenience!  

Thanks.

**Comment by cneidle** [comment]
Please make the main variant = BUSY/BUSINESS

Thanks!

**Comment by kwasiopoku** [comment]
With regards to the following statement, can you check the sign id?  There is no sign with id 17631

However this one should stay as it is:
17631 BUSY

**Comment by kwasiopoku** [comment]
Done

**Comment by cneidle** [comment]
Thanks, Augustine!   I don't have independent access to the information about its sign ID.  I'll check things from the office in case I have notes that would have the correct ID.

It would be great to have a main entry of BUSY/BUSINESS, with all the rest being
variants under that.

Thank you very much!

One other issue for the few cases where we are reorganizing the data from the ASLLVD 
data set:  This means that the composite video no longer encompasses the correct set
of entries, so ideally display of the composite videos should be disabled in such cases,
e.g., all of the BUSY, BUSINESS, and BUSY/BUSINESS entries.

(sorry, once again!)

**Comment by cneidle** [comment]
ACTUALLY, the composite videos are almost exactly right!

Looks like we collected these as separate (correct) groupings in the first place.

So for now, please do *not* make any changes to the access of the composite video :-)

**Comment by kwasiopoku** [comment]
Complete
