### ISSUE TITLE
Problem with Sign Bank entry for "WHAT" - and more generally, discrepancies between display of occurrences and the examples appearing in the composite videos ("ground truth" for what should be there)

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#126]
In the display of occurrences, we see the same signer 4 times; there are 3 different examples (with 3 different signers) in the composite video.

So something is very wrong with the listings of occurrences.

<img width="628" alt="Screen Shot 2019-07-01 at 12 07 22 PM" src="https://user-images.githubusercontent.com/13629122/60450966-fcfacb80-9bf8-11e9-88a4-8d6c03208b69.png">

<img width="741" alt="Screen Shot 2019-07-01 at 12 07 10 PM" src="https://user-images.githubusercontent.com/13629122/60450968-fcfacb80-9bf8-11e9-8adb-868beaa7ef13.png">

**Comment by cneidle** [comment]
There is another discrepancy between composite video and listing of occurrences.  For the sign below, there are two listings, with different ID numbers, for the single example that is correctly shown in the composite video.

<img width="790" alt="Screen Shot 2019-07-01 at 12 27 35 PM" src="https://user-images.githubusercontent.com/13629122/60452099-ce322480-9bfb-11e9-8d0e-bbe3d84fb503.png">

<img width="647" alt="Screen Shot 2019-07-01 at 12 27 29 PM" src="https://user-images.githubusercontent.com/13629122/60452100-ce322480-9bfb-11e9-97f0-a0195e00dc89.png">

**Comment by cneidle** [comment]
Another inconsistency, with JEWELRY.  The composite video shows two distinct signers.  The occurrences window shows only 1 example (1 signer).  Thanks.

**Comment by cneidle** [comment]
Also with KNOW-THAT:  The combined video has 2 examples, with 2 different signers.  The occurrences display shows the same 1 example (1 signer) twice.

**Comment by cneidle** [comment]
Another discrepancy between occurrence listing and composite video:  OLD.  In the composite, there are 4 different signers (1 example from each).  In the occurrences list, there are 2 signers - with 1 example from each presented twice (for a total of 4 productions, including 2 duplicates).

**Comment by cneidle** [comment]
See also -- although presumably you will catch this when you check the entire data set, as there are surely many other examples like these.  THANKS.

![Screen Shot 2019-07-08 at 11 14 29 AM](https://user-images.githubusercontent.com/13629122/60821591-d8ab6b80-a171-11e9-92cd-6615f22940f9.png)

**Comment by cneidle** [comment]
Just one more example of the mismatch between composite video examples and displayed occurrences:  GATE

**Comment by kwasiopoku** [comment]
Complete
