### ISSUE TITLE
Sign Bank - display for primary entry

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#13]
I thought the idea was to display the variant that is identical with the primary entry, if there is one.  That hasn't been implemented yet, e.g.

![screen shot 2017-10-04 at 1 25 33 pm](https://user-images.githubusercontent.com/13629122/31189981-bd684fe6-a907-11e7-846d-2c218a970af9.png)

**Comment by kwasiopoku** [comment]
Fixed
