### ISSUE TITLE
One sign properly annotated as a classifier is showing up as a non-classifier in the DAI search

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#132]
I was doing some sanity checks to try to detect -- and fix -- annotation errors.

I was looking for classifiers that were not annotated as such.  I found one example that was correctly annotated but that erroneously showed up in this search:

<img width="967" alt="Screen Shot 2019-07-03 at 6 28 12 AM" src="https://user-images.githubusercontent.com/13629122/60584786-1d8f6680-9d5c-11e9-80b2-486bc65598ec.png">

**Comment by cneidle** [comment]
Also, there are a few classifiers and gestures showing up in the list of signs to be classified.  In principle, classifiers and gestures should not be showing up, unless they are part of compounds.  But I checked, and these do seem to be correctly annotated as classifiers and gestures...

**Comment by kwasiopoku** [comment]
Fixed
