### ISSUE TITLE
Participant information is not being registered properly.

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#133]
<img width="418" alt="Screen Shot 2019-07-04 at 10 01 57 AM" src="https://user-images.githubusercontent.com/13629122/60672283-f5c6fe00-9e42-11e9-9459-1b8838fdcb36.png">

**Comment by cneidle** [comment]
In some cases, this may be due to the participant information not being properly recorded, e.g., in some of the new files.  I am checking for this and will fix these cases as I find them.  But even for files where the participant information had been showing up properly, there are problems...

**Comment by cneidle** [comment]
I believe I know the problem here.  I need to explicitly include participant information in the files, which I am doing.  When these were first uploaded, you devised an alternative way of deriving the participant from the file name, which presumably you didn't do on the most recent uploads.  In any case no need for you to do this again; I will make sure that all the participant information is properly encoded in the files.  (This was a result of a change in the SignStream application at some point after these files had initially been created.)

**Comment by kwasiopoku** [comment]
Fixed

**Comment by cneidle** [comment]
Several files are showing up as having no participant.  Some of them definitely did have participants defined.  In any case, I re-specified participants and saved, so can check again after next upload to make sure they're OK:  files 44, 60, 62, 108, 111, 115
