### ISSUE TITLE
Duplication in display of search results

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#134]
See below. Or the 19 examples shown in the table for (1)DO-DO,
8 of them are for the same sentence -- which contains 2 instances total of this sign, not 8.

<img width="900" alt="Screen Shot 2019-07-04 at 10 13 17 AM" src="https://user-images.githubusercontent.com/13629122/60673016-ce713080-9e44-11e9-8147-e5362e70473c.png">

<img width="799" alt="Screen Shot 2019-07-04 at 10 15 00 AM" src="https://user-images.githubusercontent.com/13629122/60673011-c9ac7c80-9e44-11e9-9a9d-3e1463d29c6a.png">

<img width="789" alt="Screen Shot 2019-07-04 at 10 15 13 AM" src="https://user-images.githubusercontent.com/13629122/60673005-c1544180-9e44-11e9-93ca-52ac8dc96632.png">

**Comment by cneidle** [comment]
Another example:  1 sign displayed 4 times in the search result:

<img width="467" alt="Screen Shot 2019-07-04 at 10 24 36 AM" src="https://user-images.githubusercontent.com/13629122/60673579-0dec4c80-9e46-11e9-82f9-bf891839039a.png">
<img width="1195" alt="Screen Shot 2019-07-04 at 10 23 50 AM" src="https://user-images.githubusercontent.com/13629122/60673580-0e84e300-9e46-11e9-8c88-65b3887c2382.png">

**Comment by cneidle** [comment]
There are lots and lots and lots of examples of this kind of duplication.  When it happens, it's usually exactly 4 x as many displays as there should be...

**Comment by kwasiopoku** [comment]
Fixed
