### ISSUE TITLE
Error in display of canonical examples for most of the signs added to the Sign Bank from continuous signing data

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#136]
examples:

<img width="1248" alt="Screen Shot 2019-07-06 at 12 18 11 PM" src="https://user-images.githubusercontent.com/13629122/60758698-4f1c6200-9fe8-11e9-9c40-c450507f5479.png">

<img width="1264" alt="Screen Shot 2019-07-06 at 12 17 49 PM" src="https://user-images.githubusercontent.com/13629122/60758699-4f1c6200-9fe8-11e9-8b2f-60a8547d51e7.png">

<img width="1254" alt="Screen Shot 2019-07-06 at 12 17 34 PM" src="https://user-images.githubusercontent.com/13629122/60758701-4f1c6200-9fe8-11e9-8304-5c1c692f4025.png">

<img width="1252" alt="Screen Shot 2019-07-06 at 12 16 59 PM" src="https://user-images.githubusercontent.com/13629122/60758702-4f1c6200-9fe8-11e9-808e-aa7fe8f5426b.png">

**Comment by kwasiopoku** [comment]
Variants with single occurrence fro the continuous sign data, were missing the default occurrences.  I have updated all the variants that were missing the default and I have updated the parser to set the default variant when new variants are being added.
