### ISSUE TITLE
Requests for deletion from Sign Bank

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#138]
I see that (2h)DO-DO may have been automatically classified with DO-DO (athough it lists 0 occurrences).  However, that was an error,  (2h)DO-DO should just be DO-DO.  I will correct it in the collections if I find it, but (2h)DO-DO should be removed from the Sign Bank.

Also as I mentioned, WORK/BUSINESS should not be a main entry; I entered it in error.  It should be a variant of WORK

**Comment by kwasiopoku** [comment]
(2h)DO-DO  has been removed from SignBank.

**Comment by kwasiopoku** [comment]
Fixed
