### ISSUE TITLE
Very minor request:   SignBank --> Sign Bank

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#14]
Where possible (without too much effort), it would be great to add a space between "Sign" and "Bank".

Thanks!

![screen shot 2017-10-04 at 1 31 10 pm](https://user-images.githubusercontent.com/13629122/31190167-5471e78a-a908-11e7-970d-129132a5c1ba.png)
![screen shot 2017-10-04 at 1 31 05 pm](https://user-images.githubusercontent.com/13629122/31190168-5476d33a-a908-11e7-81ce-c238d88952d2.png)

**Comment by kwasiopoku** [comment]
This is fixed and pushed to prod.  Please very and close ticket or let me know if the fix looks good and I will close the ticket

**Comment by kwasiopoku** [comment]
@cneidle This is fixed and pushed to prod.  Please very and close ticket or let me know if the fix looks good and I will close the ticket

**Comment by cneidle** [comment]
Low priority, but one more place where a space is needed for "SignBank":

![screen shot 2017-10-05 at 1 26 14 pm](https://user-images.githubusercontent.com/13629122/31241084-c9801510-a9d0-11e7-872f-25eab25f6254.png)

**Comment by kwasiopoku** [comment]
Fixed.
