### ISSUE TITLE
One more small change to the ASLLVD:  VOMIT

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#142]
I thought I had already sent this request, but I can't find a record of it:

Could you please change VOMIT to VOMIT/HATE?    ID = 8720

There is one entry from the ASLLVD, so what is now:

<img width="192" alt="Screen Shot 2019-07-07 at 10 13 24 AM" src="https://user-images.githubusercontent.com/13629122/60769620-15a72d80-a0a0-11e9-99ed-03b53f7d6b8d.png">

should instead appear as

VOMIT/HATE
      VOMIT/HATE (1)

and (1h)VOMIT should be deleted.

THANK YOU !!

**Comment by kwasiopoku** [comment]
Fixed

**Comment by cneidle** [comment]
thank you
