### ISSUE TITLE
Videos not playing for signs to be added on dev1

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#143]
It says that the video processing is complete for all the collections, but almost all of the videos (sign and utterance) for the signs to be added to the Sign Bank fail to play.

<img width="1319" alt="Screen Shot 2019-07-07 at 12 52 03 PM" src="https://user-images.githubusercontent.com/13629122/60771438-3bd7c800-a0b6-11e9-90c9-b593d940e8b2.png">

**Comment by kwasiopoku** [comment]
Fixed.
