### ISSUE TITLE
ASLLVD changes

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#144]
Just FYI, I appended the first round of changes to ticket  #125  --  THANK YOU !!!!!!

(That included the BUSY  BUSINESS  BUSY/BUSINESS changes that you have already done;
and please hold off on the MOSQUITO change.)

Here is a duplicate copy in case it is helpful to have it here.

[asllvd-corrections.xlsx](https://github.com/DCS-LCSR/ASL-DAI/files/3365946/asllvd-corrections.xlsx)

_______
     >  Note that I had incorporated the corrections that had been requested separately for 
     >  (1h)GOOD/THANK-YOU and for WORK.

   >  I have listed in column 3 any change that may be required to the gloss. If that cell 
   >  is empty, the gloss does not need to be changed. Likewise, I have listed only 
   >  handshapes that need to be changed. So for example if the dominant handshape 
   >  is correct but the non-dominant hand needs to be modified, I have not listed 
   >  anything for the dominant hand. I have only indicated the specific handshapes 
   >  that need to be changed. In the last column, I have included a main entry if the 
   >  example needs to be under a main entry different from the one currently in the Sign Bank.

   >  I hope it is all clear! Happy to explain. If there's any change in format that would be 
   >  helpful for the future, please let me know.

**Comment by cneidle** [comment]
One additional change requested - thank you !!!

![Screen Shot 2019-07-08 at 11 33 52 AM](https://user-images.githubusercontent.com/13629122/60822895-51132c00-a174-11e9-9833-8f8c3af0a5b6.png)

So the main entry GOOD/THANK-YOU will look like this:

GOOD/THANK-YOU
    (1h)GOOD-THANK-YOU 
    THANK-YOU

Note that this change will in fact be made by our editing the relevant files, as GOOD/THANK-YOU
is only in the continuous signing video.  But it does entail removing GOOD/THANK-YOU as an sub-entry under the main entry GOOD/THANK-YOU.   Perhaps you don't actually need to do anything to make that happen ?   Perhaps when it gets removed (when we re-upload collections without it), it will just disappear on its own.  In which case:  never mind.

THANKS !!  (and sorry for any confusion)

**Comment by kwasiopoku** [comment]
Done

**Comment by cneidle** [comment]
THANK YOU SO MUCH!

However:

When the gloss has been changed from KISS to KISS_2 for 5216, it needs to become a separate variant:

KISS
    KISS (3)
    KISS_2 (1)

This is how it shows up now:

<img width="732" alt="Screen Shot 2019-07-10 at 6 24 30 AM" src="https://user-images.githubusercontent.com/13629122/60962066-72daf300-a2db-11e9-83f9-0cce2071c177.png">

**Perfect**

The same is true for (1h)LAST-YEAR_2

We should end up with

LAST-YEAR
    (1h)LAST-YEAR (4)
    (1h)LAST-YEAR)_2 (1)
    LAST-YEAR_2 (1)

This is what there is now:

<img width="769" alt="Screen Shot 2019-07-10 at 6 27 11 AM" src="https://user-images.githubusercontent.com/13629122/60962380-1f1cd980-a2dc-11e9-98ac-93a321f19a63.png">

**Perfect**

Sorry I did not specify this explicitly.  I assumed that it would be automatic.

And now that "LEATHER" has been changed to "EVERYDAY" those two examples
should appear with our other examples of "EVERYDAY"

<img width="934" alt="Screen Shot 2019-07-10 at 6 33 16 AM" src="https://user-images.githubusercontent.com/13629122/60962729-ec271580-a2dc-11e9-95cd-445ed7257bd8.png">


<img width="810" alt="Screen Shot 2019-07-10 at 6 34 49 AM" src="https://user-images.githubusercontent.com/13629122/60962728-ec271580-a2dc-11e9-82a0-99e568e9ae58.png">

**Perfect**

Same for MOP_2, which should become a separate variant under MOP:

<img width="783" alt="Screen Shot 2019-07-10 at 6 38 40 AM" src="https://user-images.githubusercontent.com/13629122/60962968-88511c80-a2dd-11e9-9d72-e7bb3248de2e.png">

**Perfect**

and MENTION, which should become a separate variant under NAME

<img width="738" alt="Screen Shot 2019-07-10 at 6 40 29 AM" src="https://user-images.githubusercontent.com/13629122/60963090-dd8d2e00-a2dd-11e9-8666-56eddc74df50.png">

**Perfect**

For the changes with OF-COURSE, NORMAL and NATURAL should become their 
own entries.

establishment of 
  NORMAL
       NORMAL
       NATURAL 
**pending**

For the change from OIL to GRAVY, since it affects all entries, the main entry title
should become GRAVY, as well, and the listings that show up in the index on the left 
should be consistent -- i.e.,

GRAVY
    GRAVY (4)

rather than

<img width="93" alt="Screen Shot 2019-07-10 at 6 46 19 AM" src="https://user-images.githubusercontent.com/13629122/60963346-876cba80-a2de-11e9-8b08-5c8225753e07.png">


<img width="778" alt="Screen Shot 2019-07-10 at 6 45 57 AM" src="https://user-images.githubusercontent.com/13629122/60963299-660bce80-a2de-11e9-924b-b41d6c045fd6.png">

**pending**

**Comment by cneidle** [comment]
Continued from above...

The changes requested for OLD --> AGE were not made.
AGE can become a variant under OLD

For the change of one occurrence of LINGUISTICS to JAPAN, it should have
been "ns-nat-JAPAN" !!!  So sorry. Could we fix that?   And then that occurrence
should be moved in with the rest:


<img width="781" alt="Screen Shot 2019-07-10 at 6 52 02 AM" src="https://user-images.githubusercontent.com/13629122/60963617-4628da80-a2df-11e9-9761-e24b42d681c3.png">


<img width="785" alt="Screen Shot 2019-07-10 at 6 51 04 AM" src="https://user-images.githubusercontent.com/13629122/60963564-25f91b80-a2df-11e9-8c79-0ae436f7cc34.png">

The requested handshape change for MONDAY from bent-M to bent-B-xd
seems to have been made instead to B-xd

5903 | MONDAY |   | bent-M |   | bent-M |   | bent-B-xd |   | bent-B-xd |  

And WORK/BUSINESS still needs to moved to become a variant under WORK:

<img width="227" alt="Screen Shot 2019-07-10 at 7 08 05 AM" src="https://user-images.githubusercontent.com/13629122/60964528-8ab57580-a2e1-11e9-9c75-0e0d9fc77f06.png">

<img width="152" alt="Screen Shot 2019-07-10 at 7 07 58 AM" src="https://user-images.githubusercontent.com/13629122/60964529-8b4e0c00-a2e1-11e9-910e-7bb031299282.png">


So sorry for all the trouble.

Thank you very much !!

**Comment by kwasiopoku** [comment]
w.r.t "For the changes with OF-COURSE, NORMAL and NATURAL should become their
own entries" do you mean primary entry or entry variant?

**Comment by cneidle** [comment]
I just consulted with Carey.

He suggested that OF-COURSE should be its own main entry.

OF-COURSE
    OF-COURSE

NORMAL could be a different main entry, with two entry variants:

NORMAL
     NORMAL
     NATURAL


Thanks !!

**Comment by kwasiopoku** [comment]
Done.

**Comment by cneidle** [comment]
Hi Augustine,

very sorry, but much of the above is not actually done...  I'm going to comment on the remaining problems separately, so it will be easiest to track them.

1. There is not yet a listing for 
  NORMAL
       NORMAL
       NATURAL

Those forms have been returned to the gloss of "OF COURSE" instead.  
<img width="729" alt="Screen Shot 2019-07-11 at 7 42 32 PM" src="https://user-images.githubusercontent.com/13629122/61092429-39f26980-a414-11e9-9582-1c551c6c0b27.png">

<img width="458" alt="Screen Shot 2019-07-11 at 7 42 12 PM" src="https://user-images.githubusercontent.com/13629122/61092430-39f26980-a414-11e9-8ee5-2789d7501a61.png">

We should have

OF-COURSE

NORMAL
    NORMAL
    NATURAL

**Comment by cneidle** [comment]
2) 

For the change from OIL to GRAVY, since it affects all entries, the main entry title
should become GRAVY, as well, and the listings that show up in the index on the left
should be consistent -- i.e.,

GRAVY
      GRAVY (4)

rather than

OIL
    OIL (4)

(although the labels of the occurrences were correctly changed to GRAVY,
the title of that occurrence window still also says OIL)


But I am still seeing this:


<img width="536" alt="Screen Shot 2019-07-11 at 7 49 09 PM" src="https://user-images.githubusercontent.com/13629122/61092624-05cb7880-a415-11e9-8d1b-7b6bb23a70e0.png">

**Comment by cneidle** [comment]
OOPS - My apologies!   I somehow was looking at the DAI, rather than the dev1 Server.

Things actually look great !!!!!

**Comment by cneidle** [comment]
Please see issue # 169.

ALSO - I am REALLY REALLY REALLY REALLY sorry, but please see the very top of this message, where I asked that you NOT make the change from MOSQUITO to BEE (which you actually did).  SORRY !!!

**Comment by cneidle** [comment]
All set except for EVERYDAY - THANK YOU!
