### ISSUE TITLE
Requesting a couple of additional ASLLVD changes 

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#147]
Could you please remove two signs from the Sign Bank?  They were entered (by me) from the continuous signing, but they should not have been.

We will change the glosses so that these will no longer be present in the new batch of files we will upload, but it would be great to delete both of these entries from the Sign Bank:

- FOOD
- EARLY

Thank you!

**Comment by cneidle** [comment]
Still need to be deleted...

<img width="129" alt="Screen Shot 2019-07-23 at 1 05 51 PM" src="https://user-images.githubusercontent.com/13629122/61732072-ccff9d80-ad4a-11e9-9000-5a4a6d633920.png">

**Comment by kwasiopoku** [comment]
Done
