### ISSUE TITLE
Part 2 of ASLLVD corrections - THANK YOU !!!

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#148]
Please let me know if you have any questions.   THANKS so much !!!

[asllvd-corrections-part2.xlsx](https://github.com/DCS-LCSR/ASL-DAI/files/3383175/asllvd-corrections-part2.xlsx)

**Comment by kwasiopoku** [comment]
Done

**Comment by cneidle** [comment]
Thanks very much- but one further correction.  When the gloss is changed from PRISON to SCREEN/FILTER, the example needs to be moved into the proper group.   THANKS!

<img width="787" alt="Screen Shot 2019-07-31 at 9 32 12 AM" src="https://user-images.githubusercontent.com/13629122/62216212-54b26100-b376-11e9-9763-450b54724434.png">


<img width="805" alt="Screen Shot 2019-07-31 at 9 33 05 AM" src="https://user-images.githubusercontent.com/13629122/62216222-57ad5180-b376-11e9-9949-a98d47d050f9.png">

**Comment by cneidle** [comment]
Same issue when PERSPECTIVE_2 is changed to PERSPECTIVE - the example needs to be moved

<img width="791" alt="Screen Shot 2019-07-31 at 9 35 57 AM" src="https://user-images.githubusercontent.com/13629122/62216433-bf639c80-b376-11e9-9543-2afc172aaaa8.png">

<img width="782" alt="Screen Shot 2019-07-31 at 9 36 05 AM" src="https://user-images.githubusercontent.com/13629122/62216441-c2f72380-b376-11e9-912d-42e70b82699b.png">

**Comment by cneidle** [comment]
Also, when a new entry/variant BUILD_2 was created, which was intended to be listed under main entry BUILD, it still needs to be a distinct entry/variant.

BUILD
     BUILD_2

<img width="787" alt="Screen Shot 2019-07-31 at 9 38 03 AM" src="https://user-images.githubusercontent.com/13629122/62216608-0d78a000-b377-11e9-9664-1d3d1768fbb2.png">

**Comment by kwasiopoku** [comment]
Fixed

**Comment by cneidle** [comment]
looks good
