### ISSUE TITLE
Search menu - not working

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#15]
None of the three options works.  Should either be removed or grayed out.

![screen shot 2017-10-05 at 1 24 00 pm](https://user-images.githubusercontent.com/13629122/31241025-91f763c8-a9d0-11e7-855c-f18549abd05e.png)

**Comment by kwasiopoku** [comment]
I will disable this drop down for now.  Should be easy enough to link them to the their respective search pages

**Comment by kwasiopoku** [comment]
Fixed
