### ISSUE TITLE
GOOD/THANK-YOU - and a general, serious, problem with duplications in compounds

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#151]
GOOD/THANK-YOU is still not right

<img width="304" alt="Screen Shot 2019-07-13 at 7 09 10 AM" src="https://user-images.githubusercontent.com/13629122/61170856-28f14780-a53d-11e9-9a1c-da4f7a783ab7.png">

1) Looking first at the 2 examples of (1h)GOOD-THANK-YOU* associated with (1h)GOOD/THANK-YOU+MORNING but listed -- incorrectly -- under main entry (1h)GOOD/THANK-YOU:
There are two occurrences listed, ID numbers 9031 and 9028, but they both correspond to the same video (frames 622-760). These both correspond to the one video shown in the composite video. This one occurrence should be moved to main entry GOOD/THANK-YOU.

2) Looking next at the 6 occurrences shown of (1h)GOOD/THANK-YOU* associated with (1h)GOOD/THANK-YOU+(1h)MORNING but listed -- **correctly** -- under main entry GOOD/THANK YOU: There are 3 videos in the composite, but 6 occurrences shown from 3 different signers.  But in the listing of occurrences, the one video from Naomi is listed 4 times (i.e., there are 3 duplicates of Naomi that need to be removed). These ID numbers all correspond to the same video:  9025, 9022, 9019, and 9016.

3) For the 4 occurrences of (1h)GOOD/THANK-YOU* associated with (1h)GOOD/THANK-YOU+NIGHT, also listed -- incorrectly -- under main entry (1h)GOOD/THANK-YOU, there are 4 occurrences shown, but they correspond to only 2 different videos in the composite video, from 2 different signers (Liz and Naomi).  ID number 9034 is the example from Liz, but there are 3 copies of the example from Naomi:  9037, 9040, and 9043.  Two of the duplicates of Naomi should be removed, leaving a total of 2 examples, which should be moved under
main entry GOOD/THANK-YOU

So we should end up with the following (not including data in blue, coming only from continuous signing):

GOOD/THANK-YOU
    (1h)GOOD/THANK-YOU (29)
    (1h)GOOD/THANK-YOU* ((1h)GOOD/THANK-YOU+(1h)MORNING) (3)  
    (1h)GOOD/THANK-YOU* ((1h)GOOD/THANK-YOU+MORNING) (1)
    (1h)GOOD/THANK-YOU* ((1h)GOOD/THANK-YOU+NIGHT) (2)

Next, looking at the listings of the compounds themselves, unsurprisingly the same 
duplications found above are manifested in the compounds as well:

<img width="297" alt="Screen Shot 2019-07-13 at 7 52 46 AM" src="https://user-images.githubusercontent.com/13629122/61171275-4fb27c80-a543-11e9-861e-77c634175b99.png">

1) For the 3 examples of the compound (1h)GOOD/THANK-YOU+(1h)MORNING),
again, the 1 example with Naomi has 3 extra copies (ID numbers 9024, 9021, 9018, and 9015).  So the 6 total occurrences should be reduced to 3, 1 from each of the signers.

2) And we have the same problem as above with the compound (1h)GOOD/THANK-YOU+MORNING:  2 occurrences for the same one video of Liz (ID numbers 9027 and 9030).

3) Same for (1h)GOOD/THANK-YOU+NIGHT:  The same duplicates of Naomi mentioned above also need to be removed here. These three are all the same:  ID numbers 9033, 9042, 9039.

________

Unfortunately, the problem with duplications in compounds seems to be much more general.

Compare, for example, the composite video for ALWAYS+FOREVER_2 (1 video)
with the number of occurrences listed (2: including 1 duplicate). Exactly the same situation for:  ANSWER+AGENT, BAD+DREAM, BATH+DRESS/CLOTHES, 

For BECOME+QUIET, there are 2 examples in the composite video, but 4 in the occurrences shown (1 of the videos has 2 extra copies).

For ADVISE/INFLUENCE+AGENT, there are 3 examples from 3 different signers in the composite, but only 2 signers (with 2 duplicates, to make 4 examples in all) in the occurrences.  So there are 2 extras and 1 missing (the male signer):

<img width="608" alt="Screen Shot 2019-07-13 at 8 01 39 AM" src="https://user-images.githubusercontent.com/13629122/61171359-7ae99b80-a544-11e9-8c24-c30d41793903.png">
<img width="773" alt="Screen Shot 2019-07-13 at 8 01 30 AM" src="https://user-images.githubusercontent.com/13629122/61171360-7ae99b80-a544-11e9-8e6a-e8bef672a986.png">

In a random check of compounds, I have found inconsistencies between the composite videos (essentially ground truth, except in the very few cases where we have made very recent changes) and the listings of occurrences...    (And the same problems are replicated in the listing of the compound parts, unsurprisingly; but I expect that fixing the compounds will also result in fixing the listings of their parts.)  There are duplications as well as missing occurrences.

SORRY to be the messenger about this!

**Comment by kwasiopoku** [comment]
Fixed
