### ISSUE TITLE
compounds - something missing

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#156]
Hi Augustine,

For the compound (1h)HAIRCUT+AGENT, I am not seeing (1h)HAIRCUT*

Same thing with (2h)alt.HAIRCUT+AGENT, (2h)HAIRCUT* is not there.

<img width="294" alt="Screen Shot 2019-07-22 at 11 14 00 AM" src="https://user-images.githubusercontent.com/13629122/61643993-ee408b00-ac71-11e9-9063-b91daac6d582.png">

<img width="1024" alt="Screen Shot 2019-07-22 at 11 11 23 AM" src="https://user-images.githubusercontent.com/13629122/61644005-f1d41200-ac71-11e9-8ae2-ff9aeed7795d.png">

There are a lot of problems like this.  For example, HEAR+RUMBLE and HEAR+RUMBLE+
(which should be under the same entry; I know you have not fixed that yet), we should also be seeing HEAR* (HEAR+RUMBLE) for those.

Those are just a couple of examples.  This seems to be a very systematic problem... 

THANKS.

**Comment by kwasiopoku** [comment]
Fixed
