### ISSUE TITLE
for compounds, the representation of handshapes for the parts (when they are not missing) is confused

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#157]
So, if we have GLOSS1+GLOSS2 as a compound,
the compound itself should display the start handshape(s) for GLOSS 1 and the
end handshapes for GLOSS2.

However, GLOSS1* (GLOSS1+GLOSS2) should have the start and and handshapes for GLOSS1
(even though the video plays the whole compound).

Similarly for *GLOSS2 (GLOSS1+GLOSS2):  We should be seeing the start and end handshapes for GLOSS2.

But that is not what is happening.

The start and end handshapes for the compound itself GLOSS1+GLOSS2 seem to be correct, but the parts have some wrong handshapes.

Compare:

<img width="1218" alt="Screen Shot 2019-07-22 at 1 25 53 PM" src="https://user-images.githubusercontent.com/13629122/61651889-d1618300-ac84-11e9-91c6-6b761eed1bd1.png">

The start and end handshapes for HEART are 
<img width="71" alt="Screen Shot 2019-07-22 at 1 30 22 PM" src="https://user-images.githubusercontent.com/13629122/61651907-e0e0cc00-ac84-11e9-91af-d441b2a923d5.png">, 

and for ATTACK, the start and end handshapes are 
<img width="142" alt="Screen Shot 2019-07-22 at 1 31 02 PM" src="https://user-images.githubusercontent.com/13629122/61652004-0e2d7a00-ac85-11e9-8ce4-e972883ffafd.png">

So what is shown above for the compound itself is correct.

However, this is what we have for HEART* (actually the start handshape for HEART and the end handshapes for ATTACK):

<img width="1276" alt="Screen Shot 2019-07-22 at 1 25 30 PM" src="https://user-images.githubusercontent.com/13629122/61652067-2b624880-ac85-11e9-8b67-2c0f042a45ea.png">

and this is what we have for *ATTACK (actually the start and end handshapes for HEART):

<img width="1340" alt="Screen Shot 2019-07-22 at 1 24 59 PM" src="https://user-images.githubusercontent.com/13629122/61652089-374e0a80-ac85-11e9-90c6-63c3b8ab0f45.png">

Another example of a similar problem:

<img width="1083" alt="Screen Shot 2019-07-22 at 1 26 49 PM" src="https://user-images.githubusercontent.com/13629122/61652258-872cd180-ac85-11e9-899b-d61666c206d6.png">

This is *almost* right, except for the extraneous hand on the non-dominant hand
for the start of the second example.  Note that the above is exactly what is displayed for 
KING*, although that should have start and end handshapes as follows:

<img width="154" alt="Screen Shot 2019-07-22 at 1 37 05 PM" src="https://user-images.githubusercontent.com/13629122/61652394-d5da6b80-ac85-11e9-8e01-ea62fcc93968.png">

We can't check AREA because AREA is not listed (as AREA* (KING+AREA)), the problem reported in the previous ticket.

**Comment by kwasiopoku** [comment]
Fixed
