### ISSUE TITLE
Another feature not yet implemented:  Search by video properties

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#16]
![screen shot 2017-10-05 at 1 27 32 pm](https://user-images.githubusercontent.com/13629122/31241145-fe687204-a9d0-11e7-8747-0cc55c262fe3.png)

Might be good to indicate, e.g.

+ Video Properties  [NOT YET IMPLEMENTED]

**Comment by kwasiopoku** [comment]
Fixed
