### ISSUE TITLE
One more small correction needed to Sign Bank entry

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#163]
We have an entry in the ASLLVD data set:  #BBQ, and we have some examples of #BBQ in the continuous signing data.  But there is a frequent "error," which we also have many attested examples of:  "#BQQ".  Right now this last sign is listed as a separate main entry - note that all of the examples of this are from our continuous signing data.

It should, however, be an entry/variant of the other.  So we should have:

#BBQ  
       #BBQ 
       #BQQ (9)

When you have a chance, could you move it so that "#BQQ" is not its own main entry, but rather a variant of #BBQ, as shown above?   THANK YOU.

**Comment by kwasiopoku** [comment]
Fixed

**Comment by cneidle** [comment]
Thank you !!
