### ISSUE TITLE
ASLLVD corrections - part 8 (really just a single correction x 7)

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#165]
Hi,  What is currently glossed as EXPLAIN should be relabelled as DIRECT/EXPLAIN,
with the number of plusses retained.  And DIRECT/EXPLAIN should become a sub-entry under DIRECT.  As shown in the attached.   THANK YOU !!!!

[asllvd-corrections-part8.xlsx](https://github.com/DCS-LCSR/ASL-DAI/files/3444265/asllvd-corrections-part8.xlsx)

**Comment by kwasiopoku** [comment]
Done

**Comment by kwasiopoku** [comment]
Done
