### ISSUE TITLE
problem with incorporating compounds from continuous signing data into the Sign Bank

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#166]
Once the compounds for the ASLLVD are straightened out, we will need to revisit the way in which compounds from the continuous signing data get pulled into the Sign Bank.  That is not happening now for the compounds themselves, although it seems to be happening for the parts of compounds -- although they are integrated with the non-compound versions. So for CORRECT, along with the isolated instances of CORRECT, CORRECT* is included:

<img width="1073" alt="Screen Shot 2019-07-29 at 5 05 42 PM" src="https://user-images.githubusercontent.com/13629122/62082658-30923b00-b223-11e9-9433-70c77f4aadb2.png">

but GIRL+CORRECT is not shown

<img width="797" alt="Screen Shot 2019-07-29 at 5 07 14 PM" src="https://user-images.githubusercontent.com/13629122/62082797-70f1b900-b223-11e9-8156-005925858945.png">

Compare with CORRECT* shown separately for the ASLLVD data, as well:

<img width="264" alt="Screen Shot 2019-07-29 at 5 08 47 PM" src="https://user-images.githubusercontent.com/13629122/62082843-8e268780-b223-11e9-8aed-d17f3a1480b9.png">

**Comment by cneidle** [comment]
Compounds are now getting imported, but it's not quite right;

<img width="195" alt="Screen Shot 2019-08-06 at 6 44 36 PM" src="https://user-images.githubusercontent.com/13629122/62582419-5ac6a700-b87a-11e9-9bc9-9fb6688b0d8a.png">

What we should see for this one is the compound only
and then the parts with an * where it needs to be and
the compound itself in parentheses

25(WHY)+NOT          (the compound)
25(WHY)* (25(WHY)+NOT)
*NOT (25(WHY)+NOT)

**Comment by kwasiopoku** [comment]
Fixed
