### ISSUE TITLE
Collections on dev1 currently - 1 missing; 1 duplicate; 1 new to be added

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#168]
Hi Augustine, 

There are two copies of file 44 listed.  Perhaps you could delete both and replace with the most recent version in my "to-be-uploaded" folder?

File 107 is in the folder with files you have uploaded, but it does not appear to be on dev1.  Perhaps you could upload my latest version from the "to-be-uploaded" folder?

I also sent you email earlier about a new file that I have put in the private "to-be-uploaded" folder: file 109.

Would be great to get the 3 files just mentioned uploaded when you can...

In fact, we are still verifying the others, but it would be useful to upload those whenever is convenient... for continuing review.  

Thanks so much !!!

**Comment by kwasiopoku** [comment]
44 has been removed

**Comment by kwasiopoku** [comment]
Done
