### ISSUE TITLE
Some remaining issues from asllvd-corrections.xlsx. -- see issue #144 -- only EVERYDAY remaining to be fixed here

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#169]
APPROVE/VETO was changed from APPROVE/RATIFY, but the main entry listing was not updated, as it should have been, to match this new gloss.

<img width="139" alt="Screen Shot 2019-07-31 at 9 46 17 AM" src="https://user-images.githubusercontent.com/13629122/62217275-5c730500-b378-11e9-8438-6c9df9de0bf3.png">

<img width="788" alt="Screen Shot 2019-07-31 at 9 46 11 AM" src="https://user-images.githubusercontent.com/13629122/62217287-6137b900-b378-11e9-91c4-38176dff0324.png">

Also, 5329 and 5330 were to have been changed from LEATHER to EVERYDAY -- and moved to the EVERYDAY group.  I don't see them there.  In fact, we are missing other examples of EVERYDAY.  The composite video has 5 examples, but only 2 are showing up in the display of occurrences

<img width="1230" alt="Screen Shot 2019-07-31 at 9 52 10 AM" src="https://user-images.githubusercontent.com/13629122/62217598-e91dc300-b378-11e9-9175-341f18525d68.png">

**Comment by cneidle** [comment]
WORK_2 also needs to be a separate entry/variant under WORK

<img width="786" alt="Screen Shot 2019-07-31 at 9 56 08 AM" src="https://user-images.githubusercontent.com/13629122/62217921-7b25cb80-b379-11e9-8bd6-812c3ec84e77.png">

**Comment by cneidle** [comment]
ALSO - with huge apologies, when you have a chance, could you please restore the following examples to MOSQUITO ?   So sorry.

5934 | MOSQUITO | BEE
5933 | MOSQUITO | BEE
5938 | MOSQUITO | BEE
5937 | MOSQUITO | BEE
5936 | MOSQUITO | BEE
5935 | MOSQUITO | BEE

This is a term for MOSQUITO that Carey was unfamiliar with.  He thought it meant BEE.
But we have found this sign for MOSQUITO in several dictionaries, so it really is MOSQUITO.
Huge apologies for the inconvenience.   

Thanks for all your work on this !!!

**Comment by kwasiopoku** [comment]
All the issues on this ticket are resolved with the exception of the missing "EVERYDAY" signs.  I am looking what happened and how they were removed.

**Comment by cneidle** [comment]
The rest looks great.  Thanks for continuing to investigate EVERYDAY :-)

**Comment by kwasiopoku** [comment]
I have resolved the issue with EVERYDAY.

**Comment by cneidle** [comment]
THANK YOU!   A few small + corrections needed.  (sorry)

[asllvd-corrections-part10.xlsx](https://github.com/DCS-LCSR/ASL-DAI/files/3538828/asllvd-corrections-part10.xlsx)
