### ISSUE TITLE
One more (tiny, tiny) ASLLVD correction:  adding one +

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#171]
[~$asllvd-corrections-part9.xlsx](https://github.com/DCS-LCSR/ASL-DAI/files/3472431/asllvd-corrections-part9.xlsx)

**Comment by kwasiopoku** [comment]
I am unable to open asllvd-corrections-part9.xlsx.  
<img width="443" alt="Screen Shot 2019-08-25 at 6 30 28 PM" src="https://user-images.githubusercontent.com/10775608/63656759-7c72ca00-c766-11e9-9f94-97cd900ed952.png">

**Comment by cneidle** [comment]
This is an easy one :-)

Just needs one extra +



THANKS, 
Carol

**Comment by cneidle** [comment]
<img width="558" alt="Screen Shot 2019-09-01 at 1 43 11 PM" src="https://user-images.githubusercontent.com/13629122/64080112-7c228380-ccbe-11e9-9142-9e9d17e0528a.png">

**Comment by kwasiopoku** [comment]
Fixed
