### ISSUE TITLE
Some remaining issues - Thursday, August 8

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#174]
1)  The + here should not be included in the label in the list... 

<img width="1123" alt="ix-2" src="https://user-images.githubusercontent.com/13629122/62700335-a9299200-b9af-11e9-83be-954c60e7c071.png">

<img width="576" alt="ix-3" src="https://user-images.githubusercontent.com/13629122/62700334-a9299200-b9af-11e9-94e4-0cb27a3feae0.png">

2)  There was previously a problem with a listing that included (0).  The new item was correctly moved -- although with one + at the end --  but the listing with the (0) is still there.

<img width="1190" alt="ask-1" src="https://user-images.githubusercontent.com/13629122/62700339-a9c22880-b9af-11e9-8d42-f8121e1e1833.png">

<img width="1276" alt="ask-2" src="https://user-images.githubusercontent.com/13629122/62700338-a9c22880-b9af-11e9-8f88-aa0a178d042f.png">

3)  Same as (1) - the prior incorrect listing with a (0) remains, although this item was correctly classified now.

<img width="1440" alt="0-1" src="https://user-images.githubusercontent.com/13629122/62700341-a9c22880-b9af-11e9-939e-a9cd400535d2.png">

<img width="1136" alt="0-2" src="https://user-images.githubusercontent.com/13629122/62700340-a9c22880-b9af-11e9-81d8-b16f5cf39360.png">

THANK YOU !!!

**Comment by cneidle** [comment]
same (0) problem as before here

<img width="753" alt="Screen Shot 2019-08-08 at 7 56 45 AM" src="https://user-images.githubusercontent.com/13629122/62701423-353cb900-b9b2-11e9-9c5c-eb051e6987e7.png">

**Comment by cneidle** [comment]
Ordering:  Would be good for fs-SUN+..... to be sorted near fs-SUN

<img width="325" alt="Screen Shot 2019-08-08 at 8 05 05 AM" src="https://user-images.githubusercontent.com/13629122/62701872-5651d980-b9b3-11e9-88c3-85d6f62740e8.png">
<img width="320" alt="Screen Shot 2019-08-08 at 8 04 39 AM" src="https://user-images.githubusercontent.com/13629122/62701873-5651d980-b9b3-11e9-89d1-aaa9f138c2c7.png">

**Comment by cneidle** [comment]
quotation marks are being lost!

<img width="1280" alt="Screen Shot 2019-08-08 at 8 08 43 AM" src="https://user-images.githubusercontent.com/13629122/62702060-cb251380-b9b3-11e9-956f-02d04502f7fe.png">

**Comment by cneidle** [comment]
The entry with (0) still remains after I add (successfully) TIE_2

<img width="206" alt="Screen Shot 2019-08-08 at 9 17 06 AM" src="https://user-images.githubusercontent.com/13629122/62706388-6a9ad400-b9bd-11e9-9383-1dd95f487f00.png">

**Comment by cneidle** [comment]
A few comments on the screen shot below:

1) Don't know what REALLYWORK (0) is doing there.  That would not have existed as such in our annotations, other than as a compound REALLY+WORK.

2) I added REALLY+WORK/BUSINESS as its own compound - a new primary entry/variant.  REALLY+WORK (currently its own primary entry) should be moved to a variant under that.  Could you move it?  SORRY, once again, for the inconvenience.

3) I have just changed the gloss for REALLY+BUSINESS in the SignStream files to REALLY+WORK/BUSINESS.  So, I hope that the part, "REALLY* (REALLY+BUSINESS)", will also disappear (to be replaced by the corrected form) when the data is reuploaded.

THANK YOU !!

<img width="616" alt="Screen Shot 2019-08-08 at 9 32 33 AM" src="https://user-images.githubusercontent.com/13629122/62707558-9454fa80-b9bf-11e9-803c-503544dc2488.png">

**Comment by cneidle** [comment]
Another left-over problem from + and (0)

<img width="127" alt="Screen Shot 2019-08-08 at 9 45 27 AM" src="https://user-images.githubusercontent.com/13629122/62708413-59ec5d00-b9c1-11e9-85ae-8c996812b147.png">

**Comment by cneidle** [comment]
Error (perhaps mine) in entering this info:

<img width="748" alt="cl" src="https://user-images.githubusercontent.com/13629122/62710210-e4828b80-b9c4-11e9-9240-5d5c0866a3e9.png">


I was trying to enter this under *(2h)DCL"small flat round".  And I manually entered all the quotation marks.  But this seems to have come out as shown above -- with the rest of the compound included.  I'm afraid there may have been automatic completion of the text outside of my range of view.  (I otherwise watch for this and delete the extra characters... ).  SORRY.

I will not mess with things with quotation marks until that issue gets fixed.  For what it's worth, I am not seeing actual entries (yet, at least) missing quotation marks.

**Comment by cneidle** [comment]
Here are a whole bunch of examples, in one place, of cases where entries with (0) are showing up (but shouldn't) and/or where glosses with one or more +'s are showing up as separate entry/variants (whereas the +'s should not show up in these labels):

<img width="283" alt="Screen Shot 2019-08-08 at 10 05 03 AM" src="https://user-images.githubusercontent.com/13629122/62710567-899d6400-b9c5-11e9-8d61-fafce94d7366.png">

<img width="156" alt="Screen Shot 2019-08-08 at 10 04 48 AM" src="https://user-images.githubusercontent.com/13629122/62710568-899d6400-b9c5-11e9-9540-1f7614c9e4f1.png">

<img width="120" alt="Screen Shot 2019-08-08 at 10 04 31 AM" src="https://user-images.githubusercontent.com/13629122/62710570-899d6400-b9c5-11e9-8699-af8c89106839.png">

<img width="139" alt="Screen Shot 2019-08-08 at 10 03 34 AM" src="https://user-images.githubusercontent.com/13629122/62710573-899d6400-b9c5-11e9-94e5-262983868551.png">

<img width="265" alt="Screen Shot 2019-08-08 at 10 03 25 AM" src="https://user-images.githubusercontent.com/13629122/62710574-8a35fa80-b9c5-11e9-91ae-d9e1f8d1e7e4.png">

<img width="293" alt="Screen Shot 2019-08-08 at 10 03 01 AM" src="https://user-images.githubusercontent.com/13629122/62710575-8a35fa80-b9c5-11e9-9089-3f54b823d44a.png">

<img width="138" alt="Screen Shot 2019-08-08 at 10 02 48 AM" src="https://user-images.githubusercontent.com/13629122/62710577-8a35fa80-b9c5-11e9-96bc-36d7fa505617.png">

<img width="111" alt="Screen Shot 2019-08-08 at 10 02 44 AM" src="https://user-images.githubusercontent.com/13629122/62710580-8ace9100-b9c5-11e9-8bb0-a728a4ac44f1.png">

<img width="145" alt="Screen Shot 2019-08-08 at 10 02 29 AM" src="https://user-images.githubusercontent.com/13629122/62710581-8ace9100-b9c5-11e9-86d7-a491c23eb6e0.png">

<img width="115" alt="Screen Shot 2019-08-08 at 10 02 22 AM" src="https://user-images.githubusercontent.com/13629122/62710585-8ace9100-b9c5-11e9-8a63-ab0b3c31dae3.png">

<img width="145" alt="Screen Shot 2019-08-08 at 10 02 16 AM" src="https://user-images.githubusercontent.com/13629122/62710586-8b672780-b9c5-11e9-894c-dd01feab48a9.png">

<img width="129" alt="Screen Shot 2019-08-08 at 10 02 05 AM" src="https://user-images.githubusercontent.com/13629122/62710589-8b672780-b9c5-11e9-9014-887d06467cc5.png">

<img width="118" alt="Screen Shot 2019-08-08 at 10 01 05 AM" src="https://user-images.githubusercontent.com/13629122/62710590-8b672780-b9c5-11e9-88d7-6b40e2519fec.png">

<img width="179" alt="Screen Shot 2019-08-08 at 10 00 20 AM" src="https://user-images.githubusercontent.com/13629122/62710591-8b672780-b9c5-11e9-97da-005f8f9f9a0b.png">

<img width="120" alt="Screen Shot 2019-08-08 at 9 59 57 AM" src="https://user-images.githubusercontent.com/13629122/62710593-8bffbe00-b9c5-11e9-9a94-f7a2dd9586c9.png">

<img width="146" alt="Screen Shot 2019-08-08 at 9 59 36 AM" src="https://user-images.githubusercontent.com/13629122/62710594-8bffbe00-b9c5-11e9-8ee4-b8a44c82ff27.png">

<img width="99" alt="Screen Shot 2019-08-08 at 9 59 20 AM" src="https://user-images.githubusercontent.com/13629122/62710595-8bffbe00-b9c5-11e9-88e0-2b957d6e10ce.png">

<img width="135" alt="Screen Shot 2019-08-08 at 9 52 29 AM" src="https://user-images.githubusercontent.com/13629122/62710596-8bffbe00-b9c5-11e9-97bd-f030f1892cd5.png">

<img width="152" alt="Screen Shot 2019-08-08 at 9 50 43 AM" src="https://user-images.githubusercontent.com/13629122/62710597-8bffbe00-b9c5-11e9-9eec-1d08907d8656.png">

<img width="127" alt="Screen Shot 2019-08-08 at 9 45 27 AM" src="https://user-images.githubusercontent.com/13629122/62710599-8c985480-b9c5-11e9-91c3-87b56b14a08a.png">



<img width="310" alt="Screen Shot 2019-08-07 at 10 33 08 AM" src="https://user-images.githubusercontent.com/13629122/62710604-8c985480-b9c5-11e9-8880-380b21cb45ae.png">

**Comment by kwasiopoku** [comment]
Fixed
