### ISSUE TITLE
Plusses within compounds are also not being eliminated from classifications

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#175]
<img width="250" alt="Screen Shot 2019-08-08 at 10 47 36 AM" src="https://user-images.githubusercontent.com/13629122/62713041-10544000-b9ca-11e9-899d-8e4d248a40f5.png">

<img width="261" alt="Screen Shot 2019-08-08 at 10 47 31 AM" src="https://user-images.githubusercontent.com/13629122/62713042-10544000-b9ca-11e9-8f87-60bf06039fa6.png">

**Comment by kwasiopoku** [comment]
Fixed

**Comment by cneidle** [comment]
THANK YOU SO MUCH.

Looking really good !  -- for the non-compounds.

The only exception are a few cases where a + remains, before a :

<img width="181" alt="Screen Shot 2019-08-11 at 8 39 05 AM" src="https://user-images.githubusercontent.com/13629122/62834553-48eb5800-bc1c-11e9-88fd-3150804ebda6.png">

<img width="158" alt="Screen Shot 2019-08-11 at 8 58 14 AM" src="https://user-images.githubusercontent.com/13629122/62834554-48eb5800-bc1c-11e9-8371-8a59a41e4c4b.png">

<img width="212" alt="Screen Shot 2019-08-11 at 9 22 46 AM" src="https://user-images.githubusercontent.com/13629122/62834555-48eb5800-bc1c-11e9-8a28-f96011a75301.png">

<img width="176" alt="Screen Shot 2019-08-11 at 9 30 14 AM" src="https://user-images.githubusercontent.com/13629122/62834556-4983ee80-bc1c-11e9-8280-949195848a2c.png">

The same change should be made for all parts of compounds.  Right now, if there is a different number of +'s on any part of the compound the compound as a whole is classified as distinct from the one with a different number of +'s, e.g.:

<img width="170" alt="Screen Shot 2019-08-11 at 8 41 59 AM" src="https://user-images.githubusercontent.com/13629122/62834567-7cc67d80-bc1c-11e9-873f-f286f4b4ef96.png">

<img width="177" alt="Screen Shot 2019-08-11 at 8 48 18 AM" src="https://user-images.githubusercontent.com/13629122/62834568-7cc67d80-bc1c-11e9-81a3-768e29aa22c9.png">

<img width="130" alt="Screen Shot 2019-08-11 at 8 48 26 AM" src="https://user-images.githubusercontent.com/13629122/62834569-7cc67d80-bc1c-11e9-9ee3-c23a52a568c9.png">

<img width="133" alt="Screen Shot 2019-08-11 at 8 53 31 AM" src="https://user-images.githubusercontent.com/13629122/62834570-7cc67d80-bc1c-11e9-9090-964c8de20887.png">

<img width="164" alt="Screen Shot 2019-08-11 at 8 53 41 AM" src="https://user-images.githubusercontent.com/13629122/62834571-7cc67d80-bc1c-11e9-80f0-7dd15b95c1a5.png">

<img width="181" alt="Screen Shot 2019-08-11 at 8 55 24 AM" src="https://user-images.githubusercontent.com/13629122/62834572-7cc67d80-bc1c-11e9-8a8b-0045d68c4a1d.png">

<img width="188" alt="Screen Shot 2019-08-11 at 8 56 54 AM" src="https://user-images.githubusercontent.com/13629122/62834573-7d5f1400-bc1c-11e9-8bb8-c4779ebacd31.png">

<img width="169" alt="Screen Shot 2019-08-11 at 9 32 21 AM" src="https://user-images.githubusercontent.com/13629122/62834574-7d5f1400-bc1c-11e9-95c7-1f6daeb6899f.png">

<img width="211" alt="Screen Shot 2019-08-11 at 9 32 31 AM" src="https://user-images.githubusercontent.com/13629122/62834575-7d5f1400-bc1c-11e9-9232-99898525019d.png">



THANK YOU !!

**Comment by cneidle** [comment]
This is a correction needed to the ASLLVD data:

<img width="201" alt="Screen Shot 2019-08-11 at 10 34 11 AM" src="https://user-images.githubusercontent.com/13629122/62835217-a931c800-bc23-11e9-9cba-6a838a1b9c5f.png">

This should be listed as 

POSS:i  (no plus)
      *POSS:i  (REALLY+POSS:i)

The gloss for the compound is correct: REALLY+POSS:i+
Not sure why the + has come into the main entry/variant (and in the wrong place).

THANKS, 
Carol

**Comment by cneidle** [comment]
Related also to the "quotations are missing" comment in #174:

When I manually enter the quotation marks to insert an item, the version without quotation marks gets listed with (0) occurrences...

<img width="1235" alt="Screen Shot 2019-08-11 at 11 15 15 AM" src="https://user-images.githubusercontent.com/13629122/62835781-39730b80-bc2a-11e9-9c19-f5476024bfaa.png">

<img width="301" alt="Screen Shot 2019-08-11 at 11 16 09 AM" src="https://user-images.githubusercontent.com/13629122/62835788-51e32600-bc2a-11e9-9e8a-e769e05ae47e.png">

<img width="817" alt="Screen Shot 2019-08-11 at 11 16 50 AM" src="https://user-images.githubusercontent.com/13629122/62835796-5e677e80-bc2a-11e9-921e-b42b1e1f225d.png">

<img width="305" alt="Screen Shot 2019-08-11 at 11 18 12 AM" src="https://user-images.githubusercontent.com/13629122/62835798-63c4c900-bc2a-11e9-87c8-3f240a8ed99b.png">

**Comment by cneidle** [comment]
Also, when corrections result in eliminating previously classified signs, they do not disappear; they remain visible but with (0) occurrences.

<img width="96" alt="Screen Shot 2019-08-11 at 11 23 42 AM" src="https://user-images.githubusercontent.com/13629122/62835820-9bcc0c00-bc2a-11e9-9927-af54417fcab7.png">

thanks !!

**Comment by cneidle** [comment]
Another example like 2013, where the original entry has been eliminated (by virtue of the gloss having been corrected), but this is still visible with 0 occurrences.  POSS:1p has been corrected to POSS-1p  

<img width="150" alt="Screen Shot 2019-08-19 at 8 18 28 AM" src="https://user-images.githubusercontent.com/13629122/63264952-604cc580-c25a-11e9-91bc-5df294161afb.png">

**Comment by kwasiopoku** [comment]
Fixed
