### ISSUE TITLE
Sign Bank - view buttons doing strange things 

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#18]
@gdimitriadis 

In a Skype meeting with Greg, when he clicked on the View buttons (using Chrome), he got a dialog box to open a file from his computer.  This doesn't happen for me.  Greg - could you please send a screen shot of this?

THANKS.

![screen shot 2017-10-06 at 10 10 13 am](https://user-images.githubusercontent.com/13629122/31284766-878ea22c-aa87-11e7-8b16-082117642f7f.png)

**Comment by cneidle** [comment]
@gdimitriadis 

The Play Video was also not working for Greg from the DAI (i.e., the problem was not only in the Sign Bank part of the site).  I wonder if this is because he is missing a critical plug-in for playing the video.

Perhaps the javascript plug-in ??

If so, we will need to warn users about this.

**Comment by kwasiopoku** [comment]
I confirmed with Gregory that the behavior is working as expected for users without the right critical plug-in.  In Gregory's case, his machine is configured to prompt him to download the video after which it plays the video as expected.

I don't think this is a bug so we should close this ticket

**Comment by cneidle** [comment]
Has the DAI been tested on a PC?  Are there browser restrictions there?  Presumably also plug-in requirements?  We should provide the relevant information on this page, at least:  http://www.bu.edu/asllrp/about-dai2.html  (and wherever else on the site we provide information about requirements).  Thanks!

**Comment by kwasiopoku** [comment]
Users need the Quicktime plugin in order to play the ASLLVD single sign videos.  I will put together the relevant text for the users

https://support.mozilla.org/en-US/kb/quicktime-plugin-play-audio-and-video

**Comment by kwasiopoku** [comment]
Fixed

**Comment by cneidle** [comment]
You still wanted to check on what might need to be said for PC users, no?  THANKS

**Comment by kwasiopoku** [comment]
FIXED and VERIFIED
