### ISSUE TITLE
incorrect handshapes at the start of whole compounds : should be derived from the start handshapes of the first part

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#180]
I commented on this within the last two days in reference to another set of signs.

This seems to be something that is happening frequently.

For ONE+MILLION/BILLION, although the first part is one-handed and should have
NO handshape on the non-dominant hand for the start frame, this is appearing incorrectly for 3/4 examples:

<img width="792" alt="Screen Shot 2019-08-25 at 7 08 12 PM" src="https://user-images.githubusercontent.com/13629122/63657136-b8f4f480-c76b-11e9-92d6-70ee700cf047.png">

It is shown correctly for the compound part, but not for the compound as a whole.
What is on the left in these cases should be exactly the same:

<img width="793" alt="Screen Shot 2019-08-25 at 7 08 59 PM" src="https://user-images.githubusercontent.com/13629122/63657139-e346b200-c76b-11e9-8d91-334fd662a191.png">

The start handshapes for the compound as a whole should come from the start handshapes for the first part of the compound.

**Comment by kwasiopoku** [comment]
Fixed
