### ISSUE TITLE
Compound vs. part of compound - on dev1

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#187]
For COP+RESEARCH, there are 2 instances of the compound, but the part (COP*) only appears once.
<img width="1450" alt="Screen Shot 2019-09-27 at 12 43 26 PM" src="https://user-images.githubusercontent.com/13629122/65786377-894b5a80-e124-11e9-9bf9-2fd6f0c4b8e8.png">
<img width="1412" alt="Screen Shot 2019-09-27 at 12 43 19 PM" src="https://user-images.githubusercontent.com/13629122/65786378-894b5a80-e124-11e9-8013-03b7a92b570b.png">

**Comment by kwasiopoku** [comment]
I fixed this case but also found others (125 total) that need fixed.  Working on a script to fix these

**Comment by kwasiopoku** [comment]
This is now fixed
