### ISSUE TITLE
Problem with GOOD/THANK-YOU (sorry)

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#188]
There is one case where we changed (2h)THANK-YOU to THANK-YOU in a compound, but where the old ones were not deleted.  So there is a duplication.  The (2h)THANK-YOU+...
need to be deleted.

<img width="1425" alt="Screen Shot 2019-09-27 at 12 52 01 PM" src="https://user-images.githubusercontent.com/13629122/65787208-68840480-e126-11e9-8016-0e0e32f3f5d5.png">

<img width="1424" alt="Screen Shot 2019-09-27 at 12 51 53 PM" src="https://user-images.githubusercontent.com/13629122/65787209-68840480-e126-11e9-86a8-51d736e7a59c.png">

**Comment by kwasiopoku** [comment]
Fixed

**Comment by cneidle** [comment]
thank you!
