### ISSUE TITLE
Sign Bank - wrong sign comes up for "show occurrences"

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#19]
![screen shot 2017-10-06 at 11 25 41 am](https://user-images.githubusercontent.com/13629122/31285405-312bc9a8-aa89-11e7-9508-9e0e7be367f9.png)

The sign ACTION is selected; the occurrences are displayed for COCKTAIL.  E.g.

ACQUIRE - brings up CLOSE-DOOR,  e.g.

ACCOMPANY - brings up CLOSE

systematically wrong, in other words.

**Comment by kwasiopoku** [comment]
Fixed

**Comment by cneidle** [comment]
This is still a problem - see new issue 34.

**Comment by kwasiopoku** [comment]
Fixed
