### ISSUE TITLE
sorting issue in the DAI with compound parts - the * should be ignored

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#190]
These classifier parts should not be at the top of the list.

(1h)L-X)INTERESTING+ZERO is also not where it ought to be...

<img width="314" alt="Screen Shot 2019-09-30 at 8 07 32 PM" src="https://user-images.githubusercontent.com/13629122/65925267-16f5a700-e3be-11e9-96a4-9a3579006f7b.png">

This is where those entries belong and how they should be listed:

<img width="323" alt="Screen Shot 2019-09-30 at 8 08 57 PM" src="https://user-images.githubusercontent.com/13629122/65925296-3a205680-e3be-11e9-844d-be0da61ea6a4.png">

**Comment by kwasiopoku** [comment]
Fixed

**Comment by cneidle** [comment]
thanks!
