### ISSUE TITLE
Problem with the Sign Bank: ONLY and other signs missing images

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#191]
<img width="1174" alt="Screen Shot 2020-01-08 at 1 09 51 PM" src="https://user-images.githubusercontent.com/13629122/72003894-597a1b80-3218-11ea-9d70-bbe28e5c70ce.png">

<img width="935" alt="Screen Shot 2020-01-08 at 1 10 06 PM" src="https://user-images.githubusercontent.com/13629122/72003895-5a12b200-3218-11ea-934f-94f22023586a.png">

**Comment by cneidle** [comment]
another one:

<img width="710" alt="Screen Shot 2020-01-08 at 8 05 51 PM" src="https://user-images.githubusercontent.com/13629122/72028943-60258480-3252-11ea-9a41-419108e0ab02.png">

**Comment by cneidle** [comment]
<img width="663" alt="Screen Shot 2020-01-08 at 8 09 07 PM" src="https://user-images.githubusercontent.com/13629122/72029105-dde99000-3252-11ea-87c1-97e1d3a86a1e.png">

**Comment by cneidle** [comment]
<img width="726" alt="Screen Shot 2020-01-08 at 8 19 25 PM" src="https://user-images.githubusercontent.com/13629122/72029535-42f1b580-3254-11ea-861c-4bf42db7ac91.png">
<img width="739" alt="Screen Shot 2020-01-08 at 8 18 45 PM" src="https://user-images.githubusercontent.com/13629122/72029536-42f1b580-3254-11ea-831a-7720e0ad8a7d.png">
<img width="729" alt="Screen Shot 2020-01-08 at 8 18 26 PM" src="https://user-images.githubusercontent.com/13629122/72029537-42f1b580-3254-11ea-9b68-679d88abc018.png">
<img width="734" alt="Screen Shot 2020-01-08 at 8 17 48 PM" src="https://user-images.githubusercontent.com/13629122/72029538-42f1b580-3254-11ea-93e6-14eb5109d40d.png">
<img width="720" alt="Screen Shot 2020-01-08 at 8 17 38 PM" src="https://user-images.githubusercontent.com/13629122/72029539-42f1b580-3254-11ea-98d1-418de064cb26.png">

**Comment by cneidle** [comment]
<img width="693" alt="Screen Shot 2020-01-08 at 8 20 52 PM" src="https://user-images.githubusercontent.com/13629122/72029632-8b10d800-3254-11ea-92b1-237d1bc2c6cb.png">

**Comment by cneidle** [comment]
<img width="724" alt="Screen Shot 2020-01-08 at 8 24 18 PM" src="https://user-images.githubusercontent.com/13629122/72029751-e773f780-3254-11ea-8100-ae69a9960baa.png">

**Comment by cneidle** [comment]
<img width="750" alt="Screen Shot 2020-01-08 at 8 31 14 PM" src="https://user-images.githubusercontent.com/13629122/72030060-e7c0c280-3255-11ea-83b6-ae3ce82dcdd2.png">
<img width="752" alt="Screen Shot 2020-01-08 at 8 30 59 PM" src="https://user-images.githubusercontent.com/13629122/72030061-e7c0c280-3255-11ea-9a54-0d881d99873e.png">
<img width="771" alt="Screen Shot 2020-01-08 at 8 30 52 PM" src="https://user-images.githubusercontent.com/13629122/72030062-e7c0c280-3255-11ea-8191-1a7209f1aad1.png">
<img width="708" alt="Screen Shot 2020-01-08 at 8 29 56 PM" src="https://user-images.githubusercontent.com/13629122/72030063-e7c0c280-3255-11ea-92cf-55bba88a0c7b.png">

**Comment by cneidle** [comment]
<img width="679" alt="Screen Shot 2020-01-08 at 8 32 46 PM" src="https://user-images.githubusercontent.com/13629122/72030148-235b8c80-3256-11ea-85d1-e16b2cd6d5b9.png">
<img width="750" alt="Screen Shot 2020-01-08 at 8 31 14 PM" src="https://user-images.githubusercontent.com/13629122/72030149-235b8c80-3256-11ea-8801-f885c2ac0df3.png">

**Comment by cneidle** [comment]
<img width="682" alt="Screen Shot 2020-01-08 at 8 53 32 PM" src="https://user-images.githubusercontent.com/13629122/72030986-fd83b700-3258-11ea-931e-48da4476f895.png">
<img width="671" alt="Screen Shot 2020-01-08 at 8 53 24 PM" src="https://user-images.githubusercontent.com/13629122/72030988-fd83b700-3258-11ea-8d43-439c9bbdb515.png">

**Comment by cneidle** [comment]
<img width="698" alt="Screen Shot 2020-01-08 at 9 01 01 PM" src="https://user-images.githubusercontent.com/13629122/72031320-13de4280-325a-11ea-95c2-7de9e865829f.png">
<img width="660" alt="Screen Shot 2020-01-08 at 9 00 52 PM" src="https://user-images.githubusercontent.com/13629122/72031321-13de4280-325a-11ea-8b8f-826ad06b5780.png">
<img width="664" alt="Screen Shot 2020-01-08 at 9 00 43 PM" src="https://user-images.githubusercontent.com/13629122/72031322-13de4280-325a-11ea-9746-229da0a46a94.png">
<img width="682" alt="Screen Shot 2020-01-08 at 8 53 32 PM" src="https://user-images.githubusercontent.com/13629122/72031323-13de4280-325a-11ea-9810-d046bf80e684.png">

**Comment by cneidle** [comment]
<img width="869" alt="Screen Shot 2020-01-08 at 9 18 02 PM" src="https://user-images.githubusercontent.com/13629122/72032092-6ae51700-325c-11ea-8723-768cda2ef212.png">

**Comment by cneidle** [comment]
<img width="668" alt="Screen Shot 2020-01-08 at 9 28 38 PM" src="https://user-images.githubusercontent.com/13629122/72032616-e4313980-325d-11ea-809e-ac516ec0a8e9.png">
<img width="682" alt="Screen Shot 2020-01-08 at 9 28 26 PM" src="https://user-images.githubusercontent.com/13629122/72032617-e4313980-325d-11ea-9334-be21b79ae2f1.png">
<img width="682" alt="Screen Shot 2020-01-08 at 9 28 13 PM" src="https://user-images.githubusercontent.com/13629122/72032618-e4313980-325d-11ea-9778-44a7667eeb3c.png">
<img width="704" alt="Screen Shot 2020-01-08 at 9 27 59 PM" src="https://user-images.githubusercontent.com/13629122/72032619-e4313980-325d-11ea-91c8-39f99f9df28a.png">

**Comment by cneidle** [comment]
<img width="721" alt="Screen Shot 2020-01-08 at 9 32 43 PM" src="https://user-images.githubusercontent.com/13629122/72032808-7e917d00-325e-11ea-8b42-8370e628243c.png">
<img width="799" alt="Screen Shot 2020-01-08 at 9 32 34 PM" src="https://user-images.githubusercontent.com/13629122/72032809-7e917d00-325e-11ea-8180-ca7d9399440c.png">

**Comment by cneidle** [comment]
<img width="732" alt="Screen Shot 2020-01-08 at 9 47 15 PM" src="https://user-images.githubusercontent.com/13629122/72033526-910cb600-3260-11ea-8a86-45cb56caff71.png">
<img width="731" alt="Screen Shot 2020-01-08 at 9 47 06 PM" src="https://user-images.githubusercontent.com/13629122/72033527-910cb600-3260-11ea-8d34-0a61e046d4ab.png">

**Comment by kwasiopoku** [comment]
This was resolved.  Carol to confirm and close this ticket

**Comment by cneidle** [comment]
Hi -  In checking these, I discovered that now, for some signs (not restricted to the "Ben" data), a single image appears in the middle, whereas the standard set of two images shows up for the occurrences display

<img width="542" alt="Screen Shot 2020-01-26 at 11 14 05 AM" src="https://user-images.githubusercontent.com/13629122/73138125-35e30d80-402d-11ea-89be-bee70aa43535.png">

<img width="803" alt="Screen Shot 2020-01-26 at 11 14 13 AM" src="https://user-images.githubusercontent.com/13629122/73138124-35e30d80-402d-11ea-8ee1-0bb425d0659b.png">


<img width="554" alt="Screen Shot 2020-01-26 at 11 13 52 AM" src="https://user-images.githubusercontent.com/13629122/73138126-35e30d80-402d-11ea-85c1-aacc0acf86d1.png">



<img width="807" alt="Screen Shot 2020-01-26 at 11 11 29 AM" src="https://user-images.githubusercontent.com/13629122/73138128-35e30d80-402d-11ea-9b8c-cc1fd92f6036.png">

<img width="788" alt="Screen Shot 2020-01-26 at 11 11 35 AM" src="https://user-images.githubusercontent.com/13629122/73138127-35e30d80-402d-11ea-8e7d-b34a17d808e2.png">

**Comment by kwasiopoku** [comment]
The fix for this issue has been pushed to dev1 and dai

**Comment by cneidle** [comment]
There is still just a single image showing - is this intended to be not part of this fix?

<img width="541" alt="Screen Shot 2020-02-02 at 8 42 03 AM" src="https://user-images.githubusercontent.com/13629122/73609126-9f689c00-4598-11ea-94c6-171bdb5fb391.png">
