### ISSUE TITLE
one handshape image does not show up for handshape search

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#192]
<img width="67" alt="Screen Shot 2020-01-08 at 9 41 28 PM" src="https://user-images.githubusercontent.com/13629122/72033246-c2d14d00-325f-11ea-811b-e559e9de4219.png">
<img width="1239" alt="Screen Shot 2020-01-08 at 9 41 08 PM" src="https://user-images.githubusercontent.com/13629122/72033247-c2d14d00-325f-11ea-8c53-20682fadc23a.png">

**Comment by kwasiopoku** [comment]
Fixed

**Comment by cneidle** [comment]
thank you.
