### ISSUE TITLE
missing compound part

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#198]
We have ENGINEERING+AGENT
but I am not seeing ENGINEERING*

THanks,
 Carol
<img width="174" alt="Screen Shot 2020-01-30 at 11 24 03 AM" src="https://user-images.githubusercontent.com/13629122/73468751-452ac980-4353-11ea-8175-c82496418eba.png">

**Comment by kwasiopoku** [comment]
The variant was accidentally misclassified and was not showing up in the "Engineering" main gloss.  I have fixed this
