### ISSUE TITLE
Request from Greg to change video filenames for Sign Bank videos from continuous signing corpus

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#202]
One thing also that needs changing in the sign bank file: the video URL's

In the current global file, the video url is of the form "...mpeg4.mp4" but the actual files on the server only have the ".mp4" extension. This should be changed for all signs in the file.

**Comment by kwasiopoku** [comment]
I have made the code change for this so next signbank export should have the correct file extension for the ASLLVD data
