### ISSUE TITLE
handshape search is not working in the DAI

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#205]
When you combine a text-based search with a restriction to handshape, it does not work

Compare searching just for start dominant handshape "A" 
with searching for a class that contains the letter a, restricted to start dominant handshape "A".

<img width="736" alt="Screen Shot 2020-02-21 at 12 51 21 PM" src="https://user-images.githubusercontent.com/13629122/75058431-fcc18000-54a8-11ea-9828-fd74a28bf418.png">

<img width="1233" alt="Screen Shot 2020-02-21 at 12 50 51 PM" src="https://user-images.githubusercontent.com/13629122/75058468-09de6f00-54a9-11ea-8974-0f77dd18cfd1.png">

---

<img width="1086" alt="Screen Shot 2020-02-21 at 12 51 05 PM" src="https://user-images.githubusercontent.com/13629122/75058502-1bc01200-54a9-11ea-93a9-71f77d87a0d0.png">

<img width="933" alt="Screen Shot 2020-02-21 at 12 51 13 PM" src="https://user-images.githubusercontent.com/13629122/75058489-1367d700-54a9-11ea-8bda-18891a198c27.png">

**Comment by kwasiopoku** [comment]
Carol and I were not able to reproduce this issue.  Will keep the ticket open for now in case the issue re-occurs
