### ISSUE TITLE
Links from various places are broken: http://dai.cs.rutgers.edu/dai/s/acknowledgments

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#208]
This is linked to from various menus and also from other web pages. 

So we should make sure that URL has content.

If you can point that URL instead to this one:  http://www.bu.edu/asllrp/dai-credits.html
I can update that page...

But since there are links to that page from so many different places, we should keep that URL working.

Thanks!

**Comment by cneidle** [comment]
The link to Terms of Use is also broken:  http://dai.cs.rutgers.edu/dai/s/terms

<img width="299" alt="Screen Shot 2020-05-05 at 1 54 26 PM" src="https://user-images.githubusercontent.com/13629122/81099837-86de8980-8ed9-11ea-9a6e-d1d22f280c1d.png">

> This was the original content of that page: 
> 
> 
> The data available from these pages can be used for research and education purposes, but cannot be redistributed without permission.
> 
> Commercial use, without explicit permission, is not allowed, nor are any patents and copyrights based on this material.
> 
> Those making use of these data in research must, in resulting publications or presentations, cite, as appropriate:

Carol Neidle, Augustine Opoku, Gregory Dimitriadis, and Dimitris Metaxas [2018] 
**NEW Shared & Interconnected ASL Resources: SignStream® 3 Software; DAI 2 for Web Access to Linguistically Annotated Video Corpora; and a Sign Bank**, 8th Workshop on the Representation and Processing of Sign Languages: Involving the Language Community, 
LREC 2018, Miyazaki, Japan, pp.147-154.  https://open.bu.edu/handle/2144/30047

Carol Neidle and Christian Vogler [2012] **A New Web Interface to Facilitate Access to Corpora: Development of the ASLLRP Data Access Interface (DAI)**, 5th Workshop on the Representation and Processing of Sign Languages: Interactions between Corpus and Lexicon, LREC 2012, Istanbul, Turkey.  http://www.bu.edu/linguistics/UG/LREC2012/LREC-dai-final.pdf.

Carol Neidle, Ashwin Thangali, and Stan Sclaroff [2012] **Challenges in the Development of the American Sign Language Lexicon Video Dataset (ASLLVD) Corpus**, Proceedings of the 5th Workshop on the Representation and Processing of Sign Languages: Interactions between Corpus and Lexicon, LREC 2012, Istanbul, Turkey.  http://www.bu.edu/linguistics/UG/LREC2012/LREC-asllvd-final.pdf

and also include the following URL: http://dai.cs.rutgers.edu/dai/s/dai

**Comment by cneidle** [comment]
This link is also broken - again referenced from multiple places:

http://dai.cs.rutgers.edu/dai/s/overview

<img width="275" alt="Screen Shot 2020-05-05 at 2 10 10 PM" src="https://user-images.githubusercontent.com/13629122/81100269-42072280-8eda-11ea-959b-312220012051.png">

**Comment by cneidle** [comment]
I have updated the http://www.bu.edu/asllrp/dai-credits.html page.  So the easiest thing would be to have http://dai.cs.rutgers.edu/dai/s/acknowledgments  just redirect to that page.  Then all the links to http://dai.cs.rutgers.edu/dai/s/acknowledgments can be left as is.  Thanks.

likewise I have added a  “terms of use” page:

	http://www.bu.edu/asllrp/dai-terms.html

You can eitalsoer redirect from http://dai.cs.rutgers.edu/dai/s/terms

       to that page (or else replicate the page above at the Rutgers URL).

**Comment by cneidle** [comment]
The HOME link is also broken - on the Download Cart page

**Comment by cneidle** [comment]
The Search menu is also broken- on the Download Cart page

**Comment by kwasiopoku** [comment]
Remove overview page from all dai pages
