### ISSUE TITLE
Help page needs to be updated

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#210]
E.g., with respect to download instructions and account information, and also general information about the SIgn Bank (in addition to deleting the "beta").

<img width="997" alt="Screen Shot 2020-05-05 at 2 17 28 PM" src="https://user-images.githubusercontent.com/13629122/81100817-2f411d80-8edb-11ea-96c5-f4d4bca6af9d.png">

<img width="983" alt="Screen Shot 2020-05-05 at 2 19 25 PM" src="https://user-images.githubusercontent.com/13629122/81101041-83e49880-8edb-11ea-840c-700ae9c20bb4.png">

**Comment by cneidle** [comment]
As I suggested via email, I think we should eliminate the help page, and have the Help button open up a page with a link to the User's Guide.  In order to finish off that guide, though, I need a decision on how people should reset their password...  I sent email with some considerations about this.  We will then also need to fix the buttons that send the user from "reset password" to the Help page...

**Comment by cneidle** [comment]
This is the current URL for the Help page:

  http://dai.cs.rutgers.edu/dai/s/help

So that should just be replaced with a link to the User Guide http://www.bu.edu/asllrp/rpt18/asllrp18.pdf 
(which is just a placeholder file for now, saying "coming soon"), 
or it can just be redirected to:

   http://www.bu.edu/asllrp/SignStream/3/dai2/dai2-faq.pdf

That was the page that had served as the source for what is at the Rutgers URL, but I have now replaced what was on the BU page with a single link to that User's Guide.

**Comment by kwasiopoku** [comment]
Link all references to help page to http://www.bu.edu/asllrp/rpt18/asllrp18.pdf
