### ISSUE TITLE
Statistics - check

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#211]
Would be great to verify the statistics on this page:

http://dai.cs.rutgers.edu/dai/s/runningstats

And it would be great to also provide statistics for the Sign Bank as a whole:
e.g., total number of main entries; total number of distinct entry/variants; total number of sign examples...

**Comment by kwasiopoku** [comment]
Add third column to stats page with heading "Entire Sign Bank"

Add data for first 3 rows(main gloss entry, gloss variants and individual sign occurrences)

**Comment by kwasiopoku** [comment]
For the following rows, add the items in columns 1 & 2 and persist the result to column 3


Lexical Signs | 11043 | 8489 |  
Fingerspelled Signs | 712 | 0 |  
Loan Signs | 492 | 138 |  
Gestures | 224 | 0 |  
Classifiers | 239 | 47 |  
Number Signs | 99 | 261 |  
Compounds | 310 | 350 |  
Name Signs
