### ISSUE TITLE
Non admin users should only be able to use the cart feature

### ISSUE THREAD

**Issue by kwasiopoku** [DCS-LCSR/ASL-DAI#217]
Non admin users should only be able to use the cart feature
Non admin users should not be able to see the signs that have not yet been added to signbank
Non admin users should not be able to see non public data

**Comment by cneidle** [comment]
Non admin users also should not see the “display graphs” option

**Comment by cneidle** [comment]
Non admin users should not be able to see the option to "Change other user's account information" from the ACCOUNT ADMIN button.

**Comment by kwasiopoku** [comment]
Done
