### ISSUE TITLE
Wrong video in the original videos window

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#222]
<img width="1013" alt="Screen Shot 2020-05-27 at 10 42 22 AM" src="https://user-images.githubusercontent.com/13629122/83035952-158d8480-a008-11ea-8010-0b57660151dc.png">

**Comment by cneidle** [comment]
Another example:  The "original video" for 1120 displays a different signer (same sign).
<img width="1118" alt="Screen Shot 2020-05-30 at 1 33 48 PM" src="https://user-images.githubusercontent.com/13629122/83335370-61dffb00-a27a-11ea-9470-9922355c01fe.png">

**Comment by cneidle** [comment]
The original video for 1126 brings up the wrong signer in the second window.

<img width="1142" alt="Screen Shot 2020-05-30 at 1 35 49 PM" src="https://user-images.githubusercontent.com/13629122/83335400-8dfb7c00-a27a-11ea-9773-26b4c900eeac.png">

**Comment by kwasiopoku** [comment]
Fixed

**Comment by cneidle** [comment]
Here is another one!

<img width="955" alt="Screen Shot 2020-07-01 at 7 49 19 PM" src="https://user-images.githubusercontent.com/13629122/86301720-937b1780-bbd4-11ea-831e-cbcce7787a7e.png">


<img width="349" alt="Screen Shot 2020-07-01 at 7 49 09 PM" src="https://user-images.githubusercontent.com/13629122/86301723-9413ae00-bbd4-11ea-95dc-3eaab9fd44ce.png">

**Comment by cneidle** [comment]
There seem to be a lot of these - with Liz and Brady. Liz has 1 original video; Brady has 4, one of which is actually Liz... 

<img width="1007" alt="Screen Shot 2020-07-01 at 9 53 28 PM" src="https://user-images.githubusercontent.com/13629122/86307686-5f5c2280-bbe5-11ea-92da-2285d1dd28e4.png">

<img width="1059" alt="Screen Shot 2020-07-01 at 9 54 55 PM" src="https://user-images.githubusercontent.com/13629122/86307769-9cc0b000-bbe5-11ea-983b-b993ed8f87c8.png">

**Comment by cneidle** [comment]
definitely seems to be a systematic problem.  When we have Liz and Brady, 1 of Liz's original videos shows up with Brady's.

So we have one (correct) video for Liz, and then Brady's videos + 1 of Liz's.

<img width="917" alt="Screen Shot 2020-07-04 at 6 01 08 AM" src="https://user-images.githubusercontent.com/13629122/86510239-04c8ef00-bdbc-11ea-8021-8ba9bfa86de1.png">
