### ISSUE TITLE
A few more requests for changes to ASLLVD data structures

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#229]
Hi Augustine, 

SO sorry.

1. Whenever you have a chance, could you please change the glosses for HUG to LOVE?

<img width="781" alt="Screen Shot 2020-06-24 at 11 58 45 AM" src="https://user-images.githubusercontent.com/13629122/85590037-17039a00-b612-11ea-81cb-6b49dcb576a5.png">

So we will end up with

LOVE
- LOVE (incorporating the 3 examples above)
- HUG_2

and HUG should be permanently deleted as a main entry.

=====

2. Could you please move the one example of (F)EXACT out of where it is now, and make it a variant under PERFECT, reglossing it as PERFECT_2 ?

<img width="796" alt="Screen Shot 2020-06-24 at 12 03 45 PM" src="https://user-images.githubusercontent.com/13629122/85590990-e2441280-b612-11ea-9d4a-c30dfbc07cdb.png">

<img width="1194" alt="Screen Shot 2020-06-24 at 12 00 29 PM" src="https://user-images.githubusercontent.com/13629122/85590503-7661aa00-b612-11ea-9666-a1918f428938.png">

<img width="211" alt="Screen Shot 2020-06-24 at 12 00 54 PM" src="https://user-images.githubusercontent.com/13629122/85590555-811c3f00-b612-11ea-939d-270cc9c85e36.png">

So we will end up with

EXACT
- EXACT
- EXACT_2

PERFECT
- PERFECT
- PERFECT_2    (previously (F)EXACT)
- (P)PERFECT

=============

3. We currently have two errors in the continuous signing data, which I will fix.  What is now glossed as PICK and PICK-1p should be glossed as PICK/CHOOSE.  I have just fixed those in the SignStream files.  Once they are re-uploaded, PICK should be deleted as a main entry.  Now fixed (but not yet reuploaded):

<img width="793" alt="Screen Shot 2020-06-24 at 12 07 11 PM" src="https://user-images.githubusercontent.com/13629122/85591400-45ce4000-b613-11ea-80e9-9adc10deb122.png">

<img width="785" alt="Screen Shot 2020-06-24 at 12 07 02 PM" src="https://user-images.githubusercontent.com/13629122/85591407-46ff6d00-b613-11ea-8d72-a86980dcadb0.png">

=============

THANK YOU  !!!

**Comment by cneidle** [comment]
Could you please move MISTAKE_2 from the main entry MISTAKE to the main entry WRONG?  No need to change the gloss.  So what we have now is: 

<img width="128" alt="Screen Shot 2020-06-25 at 9 12 11 PM" src="https://user-images.githubusercontent.com/13629122/85810333-b87d0f80-b728-11ea-9216-73c5dd89b85c.png">

<img width="144" alt="Screen Shot 2020-06-25 at 9 12 23 PM" src="https://user-images.githubusercontent.com/13629122/85810342-c468d180-b728-11ea-821d-08fd5eb25794.png">

AND we should end up with 

MISTAKE
- MISTAKE

WRONG
- WRONG
- MISTAKE_2
- VERY-WRONG

**Comment by kwasiopoku** [comment]
Done.

**Comment by cneidle** [comment]
THANKS - the only thing that still needs to be done is (3) above -- which can only be done after the new SignStream files have been uploaded.  THANK YOU !!!!
