### ISSUE TITLE
DAI - Handshape display should not be wrapping

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#23]
There should be a minimum width so that the text doesn't wrap

<img width="446" alt="screen shot 2017-10-06 at 6 12 07 pm" src="https://user-images.githubusercontent.com/13629122/31300479-ed3f41c8-aac1-11e7-9e5a-4237ac9a9e2a.png">

**Comment by kwasiopoku** [comment]
Fixed
