### ISSUE TITLE
One more small request for ASLLVD data

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#231]
Could you please make TEST_2 an entry/variant under TEST?

So we will have 

TEST
- TEST
- TEST_2

Thank you !!!!

<img width="1012" alt="Screen Shot 2020-06-30 at 9 17 58 PM" src="https://user-images.githubusercontent.com/13629122/86192305-408f5a80-bb17-11ea-981b-75533d6dad23.png">

**Comment by cneidle** [comment]
Another request:

Right now we have two separate main entries:   ADD and TOTAL:

<img width="87" alt="Screen Shot 2020-07-05 at 5 52 33 PM" src="https://user-images.githubusercontent.com/13629122/86542975-6be3c200-bee8-11ea-83e8-9ee8e4d6ff27.png">


<img width="118" alt="Screen Shot 2020-07-05 at 5 52 06 PM" src="https://user-images.githubusercontent.com/13629122/86542976-6be3c200-bee8-11ea-9214-73e76aa506cf.png">


These are actually the same sign.

So,  could you please change the gloss for the 4 ASLLVD ADD signs to "TOTAL" and merge them with the examples in TOTAL?  I will have to change the one from the continuous signing data.  Once that is done, we should delete the main entry for ADD. 

We will then end up with

TOTAL
- TOTAL  (will include the 4 signs previously glossed as "ADD")
- TOTAL_2


<img width="773" alt="Screen Shot 2020-07-05 at 5 51 11 PM" src="https://user-images.githubusercontent.com/13629122/86542977-6be3c200-bee8-11ea-8e87-24da77ce5806.png">

THANK YOU !!

**Comment by kwasiopoku** [comment]
Done

**Comment by cneidle** [comment]
THANK YOU !

We can close this once the SignStream file has been uploaded and ADD has been removed as a potential main entry :-)

**Comment by cneidle** [comment]
For the correction above to change ADD to TOTAL, the main entry ADD remained (hidden), so this incorrect annotation was automatically added:

<img width="293" alt="Screen Shot 2020-09-08 at 12 15 21 PM" src="https://user-images.githubusercontent.com/13629122/92502021-45ceec80-f1cd-11ea-8960-0d4b500cd02d.png">

In such. cases, the deleted items should be removed from the database so that we catch errors like this..   

I will re-annotate that file, for re-upload, but after that is done, ADD should be removed from the database as a possible gloss for automatic classification.   

THANKS !!
