### ISSUE TITLE
some data seems to be missing -- from recently reuploaded SignStream files

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#232]
For BEFORE and (nd-1)BEFORE

These were probably from the SignStream files that were very recently reuploaded...

They are not showing up in searches, either.

<img width="662" alt="Screen Shot 2020-07-05 at 8 07 09 PM" src="https://user-images.githubusercontent.com/13629122/86545215-575cf500-befb-11ea-856c-cc1f8e7337b9.png">

<img width="665" alt="Screen Shot 2020-07-05 at 8 07 00 PM" src="https://user-images.githubusercontent.com/13629122/86545216-575cf500-befb-11ea-9cfd-4891d1dd586d.png">

<img width="684" alt="Screen Shot 2020-07-05 at 8 05 50 PM" src="https://user-images.githubusercontent.com/13629122/86545217-575cf500-befb-11ea-9631-e1b789681536.png">

**Comment by kwasiopoku** [comment]
This has been resolved.

**Comment by cneidle** [comment]
Thank you!
