### ISSUE TITLE
The ticket that disappeared:  Please change EAR to HEAR in one compound

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#233]
<img width="690" alt="Screen Shot 2020-07-11 at 3 46 42 PM" src="https://user-images.githubusercontent.com/13629122/87232648-96bd9280-c38e-11ea-9ccb-65bf3dc4fe4f.png">

THANK YOU

**Comment by kwasiopoku** [comment]
Fixed
