### ISSUE TITLE
Download cart history:  doubled

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#235]
Download seems to be working :-)

But each of my two downloads seems to be listed twice.

<img width="869" alt="Screen Shot 2020-07-17 at 5 32 45 PM" src="https://user-images.githubusercontent.com/13629122/87832319-bef83600-c853-11ea-835c-e04fd2b6faba.png">

**Comment by kwasiopoku** [comment]
This has been resolved and pushed to dai
