### ISSUE TITLE
fixes needed to ASLLVD data

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#237]
**NOT COMPLETELY FIXED** - The entries for ns-#VN should be merged:

<img width="123" alt="Screen Shot 2020-10-04 at 9 54 49 AM" src="https://user-images.githubusercontent.com/13629122/95017519-bf6cc580-0627-11eb-95c4-eaf9cab24bf0.png">

======

When you have a chance, could you please change ns-VIETNAM to ns-#VN ?

There are 2 signs that will be affected.

Thank you very much !!

<img width="797" alt="Screen Shot 2020-07-27 at 2 16 38 PM" src="https://user-images.githubusercontent.com/13629122/88576837-0cbf2c00-d014-11ea-97da-68cc74adbf84.png">

**Comment by cneidle** [comment]
FIXED - Also, there should be separate main entries for "LIGHT-ON" and "LIGHT-OUT"

So we should have 

LIGHT-ON
- *LIGHT-ON  (LIGHT+LIGHT-ON)

LIGHT-OUT
- *LIGHT-OUT (LIGHT+LIGHT-OUT)

thanks !!

<img width="234" alt="Screen Shot 2020-07-27 at 5 18 15 PM" src="https://user-images.githubusercontent.com/13629122/88593256-451f3400-d02d-11ea-9b10-c868b08ed531.png">

=====
9/9 Since I posted this originally, there has been some further auto-classification.  This is what we now have:

<img width="248" alt="Screen Shot 2020-09-09 at 7 39 41 AM" src="https://user-images.githubusercontent.com/13629122/92593814-bcbcc180-f26f-11ea-95c4-1f2cc2442543.png">

So we should end up with:

LIGHT-ON
- *LIGHT-ON (LIGHT+LIGHT-ON) (11)
- (2h)LIGHT-ON (1)

LIGHT-OUT
- *LIGHT-OUT (LIGHT+LIGHT-OUT) (11)
- (2h)LIGHT-OUT

**Comment by cneidle** [comment]
FIXED - NOTE AS OF 8/17:  I have now added #VP_2 from the new DSP data.  So these occurrences of VICE-PRESIDENT should be reglossed as #VP_2 and moved in with the other examples, and VICE-PRESIDENT should be permanently removed as a possible main entry or entry/variant.  Thanks !

========================

For the two occurrences of "VICE-PRESIDENT" could you please regloss that as #VP_2 (a loan sign) ?  THANK YOU !!

<img width="1082" alt="Screen Shot 2020-07-29 at 9 17 56 AM" src="https://user-images.githubusercontent.com/13629122/88804979-a1449e00-d17c-11ea-8bd3-a9654cd808c8.png">

Note that "VICE-PRESIDENT" should be removed as a possible main entry.  Note also that #VP and #VP_2 should be distinct main entries.

**Comment by cneidle** [comment]
FIXED - We currently have two distinct main entries:  CLOSE and NEAR.

Could you please make CLOSE an entry/variant under NEAR?
No changes in glossing are required, but we will go from:

CLOSE
- CLOSE

NEAR 
- NEAR

to:

NEAR
- NEAR
- CLOSE

THANK YOU !!

<img width="1104" alt="Screen Shot 2020-07-31 at 11 43 25 AM" src="https://user-images.githubusercontent.com/13629122/89052155-49946700-d323-11ea-84b4-30fef45d0990.png">

<img width="1059" alt="Screen Shot 2020-07-31 at 11 42 58 AM" src="https://user-images.githubusercontent.com/13629122/89052163-4bf6c100-d323-11ea-9df1-97acabe2d3f2.png">

**Comment by cneidle** [comment]
ALSO - not sure what has happened with the "ns-VIETNAM" fix requested above.  Although the fix has not yet been made, one of the 2 original entries seems to have disappeared

**Comment by cneidle** [comment]
**NOT FIXED** -- The entry in question has disappeared entirely.

There is one occurrence of (1h)AREA that is *not* listed as an entry/variant under AREA, which is how it should be listed (along with other occurrences of (1h)AREA).

<img width="787" alt="Screen Shot 2020-08-15 at 5 53 38 PM" src="https://user-images.githubusercontent.com/13629122/90322280-7b5f1d80-df20-11ea-83c7-7e7ca7a4cf89.png">

<img width="312" alt="Screen Shot 2020-08-15 at 5 53 27 PM" src="https://user-images.githubusercontent.com/13629122/90322282-7c904a80-df20-11ea-9c7b-947f0013a32a.png">

Could you please fix that one?   THANKS!

**Comment by cneidle** [comment]
FIXED - One more requested change:

We have two signs in the ASLLVD data set glossed as RELATIVE.  Those should be glossed instead as FRIEND and moved in with the other examples of FRIEND.  Thanks!

<img width="701" alt="Screen Shot 2020-08-24 at 2 47 48 PM" src="https://user-images.githubusercontent.com/13629122/91083955-32daea80-e619-11ea-8fdb-39ac18d8990e.png">


What we have now is:

FRIEND
- FRIEND (261)
- *FRIEND (BOY+FRIEND) (7)
- *FRIEND (GIRL+FRIEND) (15)

RELATIVE
- RELATIVE (2)
- (R)RELATIVE (6)

We should end up with:

FRIEND
- FRIEND (263)
- *FRIEND (BOY+FRIEND) (7)
- *FRIEND (GIRL+FRIEND) (15)

RELATIVE
- (R)RELATIVE (6)

**Comment by kwasiopoku** [comment]
Done

**Comment by kwasiopoku** [comment]
Fixed and verified
