### ISSUE TITLE
A few additional issues with the Sign Bank listings of glosses

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#239]
FIXED - 1). Could you please make LEGAL-RIGHT an entry/variant under ALL-RIGHT?

So now we have 

LEGAL-RIGHT
- LEGAL-RIGHT

ALL-RIGHT
- ALL-RIGHT

and we will end up with

ALL-RIGHT
- ALL-RIGHT
- LEGAL-RIGHT

<img width="912" alt="Screen Shot 2020-08-27 at 5 44 08 PM" src="https://user-images.githubusercontent.com/13629122/91498064-1b0b9c80-e88d-11ea-9149-22455d33283f.png">

<img width="951" alt="Screen Shot 2020-08-27 at 5 43 43 PM" src="https://user-images.githubusercontent.com/13629122/91498069-1d6df680-e88d-11ea-96e9-570e9b569382.png">

**NOT FIXED** - 2) There was a typo in one of the glosses, which I only noticed after I had entered it.   I will correct the file, but once it is reloaded, we should delete SSH+HIDE as a possible main entry.  I will reupload that as SHH+HIDE.  Thanks!

<img width="131" alt="Screen Shot 2020-08-27 at 5 46 17 PM" src="https://user-images.githubusercontent.com/13629122/91498194-56a66680-e88d-11ea-9ffd-599f6517c074.png">

**Comment by cneidle** [comment]
I am having some trouble with entering glosses into the SIgn Bank that have +'s.  I'll discuss this with you next time we talk.

This will need to be deleted - 
<img width="313" alt="Screen Shot 2020-08-27 at 4 22 48 PM" src="https://user-images.githubusercontent.com/13629122/91498429-bc92ee00-e88d-11ea-86e9-fc509f5697d6.png">

and I will show you what happens with SELF+:i and (P)PAY+* (PAY++FINISH)

THANKS.

**Comment by cneidle** [comment]
FIXED - this is a mistake.  TREE-pl should not be a main entry.  The subentries listed there should be moved to be under TREE.

<img width="280" alt="Screen Shot 2020-08-28 at 3 12 57 PM" src="https://user-images.githubusercontent.com/13629122/91606982-26200480-e941-11ea-9445-f42f13b8581c.png">

**Comment by cneidle** [comment]
FIXED -I had corrected (V/2)FACE to (V)FACE, but when the file was re-uploaded, the main entry from the previous version was still visible.  That should be deleted.  THANKS!
 
<img width="653" alt="Screen Shot 2020-09-05 at 7 18 00 PM" src="https://user-images.githubusercontent.com/13629122/92314942-ba771080-efac-11ea-8f19-76f644b0f3fd.png">

**Comment by cneidle** [comment]
**NOT FIXED** - The entry for the compound in question seems to have disappeared... 

This was somehow misclassified.

<img width="173" alt="Screen Shot 2020-09-11 at 2 12 52 PM" src="https://user-images.githubusercontent.com/13629122/92959186-57b4c780-f439-11ea-9eb1-bcb4bd865bf3.png">

The highlighted item should be its own main entry:  BREAK+#(2h)UP

(Sorry if I did this!)

**Comment by kwasiopoku** [comment]
Done

**Comment by kwasiopoku** [comment]
Fixed and resolved

**Comment by cneidle** [comment]
BREAK+#(2h)UP seems to have disappeared!
