### ISSUE TITLE
DAI - restriction to name signs does not work; problems also with restrictions to passive base arm, marked no. of hands

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#24]
<img width="689" alt="screen shot 2017-10-06 at 6 14 32 pm" src="https://user-images.githubusercontent.com/13629122/31300543-402bab56-aac2-11e7-98fd-8f0b47865c80.png">

Restriction to marked number of hands *almost* works - with two errors at the bottom
<img width="791" alt="screen shot 2017-10-06 at 6 15 32 pm" src="https://user-images.githubusercontent.com/13629122/31300641-c0103a9e-aac2-11e7-9e61-0e4d4e5670d5.png">

Restriction to passive base arm also includes a few errors, e.g., BROTHER,  (2h)5"dismissive gesture"

<img width="794" alt="screen shot 2017-10-06 at 6 17 09 pm" src="https://user-images.githubusercontent.com/13629122/31300649-c7c1ca14-aac2-11e7-83d0-0f4a5b9b29ae.png">

**Comment by cneidle** [comment]
Restricting to 1-handed signs with marked number of hands also produces two errors at the bottom

<img width="704" alt="screen shot 2017-10-06 at 6 23 58 pm" src="https://user-images.githubusercontent.com/13629122/31300772-973949e8-aac3-11e7-9881-4bc863d886bc.png">

**Comment by kwasiopoku** [comment]
@cneidle how do I identify name signs?  apologies if you have already asked this in the past.

**Comment by cneidle** [comment]
There is a checkbox:




also glossing conventions include ns-



which may be preceded by a handshape, e.g.

(25)ns-CALIFORNIA

**Comment by kwasiopoku** [comment]
Fixed
