### ISSUE TITLE
small display suggestion

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#242]
Right now, these sets of results appear to be displayed centered within the window.  It would be better if they were all left-aligned, as the multiple groupings would have a more consistent display.  Low priority, of course, but just a thought...

thanks!

<img width="1063" alt="Screen Shot 2020-09-10 at 10 38 33 AM" src="https://user-images.githubusercontent.com/13629122/92747135-e64e1980-f351-11ea-8f9b-ab3f3352bad3.png">

**Comment by kwasiopoku** [comment]
Fixed

**Comment by cneidle** [comment]
Thank you !
