### ISSUE TITLE
Search - does not work on private data

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#244]
<img width="882" alt="Screen Shot 2020-09-23 at 11 29 33 AM" src="https://user-images.githubusercontent.com/13629122/94034566-2bca0800-fd90-11ea-930b-5f1ab259948b.png">

**Comment by cneidle** [comment]
This should be a relatively high priority for fixing, as having this functionality would be very helpful for the verifications.   Thanks!

**Comment by kwasiopoku** [comment]
This has been resolved
