### ISSUE TITLE
something weird with sorting

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#246]
These compounds seem to be sorted based on the second element in the compound rather than the first.

<img width="306" alt="Screen Shot 2020-10-04 at 9 47 48 AM" src="https://user-images.githubusercontent.com/13629122/95017343-cb0bbc80-0626-11eb-80f2-95daf0802d77.png">

<img width="247" alt="Screen Shot 2020-10-04 at 9 50 39 AM" src="https://user-images.githubusercontent.com/13629122/95017407-2ccc2680-0627-11eb-8b2b-db3d30c03a38.png">

**Comment by kwasiopoku** [comment]
Sorting should ignore leading quotation marks.

**Comment by cneidle** [comment]
I'm not seeing *DCL"rounded rectangle" as a separate entry.  It seems to have disappeared.
