### ISSUE TITLE
DSP sentences not showing up in the right section of the Sign Bank

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#247]
There should be a separate section for them ("DawnSIgnPress signs from sentences"), but they are showing up interspersed with the "ASLLRP signs from sentences")

<img width="806" alt="Screen Shot 2020-10-04 at 10 07 29 AM" src="https://user-images.githubusercontent.com/13629122/95017874-cf85a480-0629-11eb-9570-372c1fa9dc20.png">

<img width="784" alt="Screen Shot 2020-10-04 at 10 07 19 AM" src="https://user-images.githubusercontent.com/13629122/95017875-d0b6d180-0629-11eb-9bb8-38ca196ef514.png">

<img width="779" alt="Screen Shot 2020-10-04 at 10 07 09 AM" src="https://user-images.githubusercontent.com/13629122/95017876-d14f6800-0629-11eb-871c-bad582b171f6.png">

<img width="787" alt="Screen Shot 2020-10-04 at 10 06 56 AM" src="https://user-images.githubusercontent.com/13629122/95017877-d14f6800-0629-11eb-9146-5f3c7341648e.png">

**Comment by kwasiopoku** [comment]
This has been fixed

**Comment by cneidle** [comment]
Thanks!   Would be good to have parallelism in the headings:

<img width="223" alt="Screen Shot 2020-10-04 at 11 38 20 AM" src="https://user-images.githubusercontent.com/13629122/95019921-2d1fee00-0636-11eb-8c56-01a917a4a241.png">
<img width="221" alt="Screen Shot 2020-10-04 at 11 38 02 AM" src="https://user-images.githubusercontent.com/13629122/95019922-2db88480-0636-11eb-85fe-019144c9d436.png">

Could we make it "DawnSignPress signs from sentences" ?

THANKS!

**Comment by kwasiopoku** [comment]
Fixed
