### ISSUE TITLE
Issues with classifying signs

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#248]
As previously discussed, need to protect the apostrophe, e.g. here:

<img width="212" alt="Screen Shot 2020-10-04 at 10 16 52 AM" src="https://user-images.githubusercontent.com/13629122/95018027-d6f97d80-062a-11eb-8b67-6fb49f4e434d.png">

**Comment by cneidle** [comment]
As listed in the "wish list" (probably not the right place to have listed it), there are issues with respect to +'s in entries - both with respect to classifying new entries, and to the presence of +'s where they shouldn't be in some existing entries.

**Comment by kwasiopoku** [comment]
Fixed
