### ISSUE TITLE
one more ASLLVD correction, please (and thank you!)

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#249]
I checked on the example you asked about, and actually, the gloss is incorrect.

#DO+ should be reglossed as (and merged with the other examples) of DO-DO.
There is just one example, as part of a compound, which should therefore also be
reglossed.  #DO+"WHAT" should be changed to DO-DO+"WHAT"

THANK YOU !

<img width="166" alt="Screen Shot 2020-10-08 at 3 14 01 PM" src="https://user-images.githubusercontent.com/13629122/95503373-4946c680-0979-11eb-8dba-433f756c3217.png">

<img width="768" alt="Screen Shot 2020-10-08 at 3 17 03 PM" src="https://user-images.githubusercontent.com/13629122/95503576-89a64480-0979-11eb-9b11-c4f9ff0efa12.png">

<img width="796" alt="Screen Shot 2020-10-08 at 3 17 52 PM" src="https://user-images.githubusercontent.com/13629122/95503568-88751780-0979-11eb-946a-233d1eb360a8.png">

**Comment by kwasiopoku** [comment]
This issue has been resolved

**Comment by cneidle** [comment]
The example above seems to have been removed, rather than moved to where it needs to go...

<img width="775" alt="Screen Shot 2020-10-12 at 8 48 08 AM" src="https://user-images.githubusercontent.com/13629122/95748254-b69f7380-0c67-11eb-9436-e92f9d12532f.png">

**Comment by kwasiopoku** [comment]
Resolved and verified
