### ISSUE TITLE
PERIODICALLY

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#253]
This is showing up in the index, but without any examples...

I thought we did have something glossed this way.

<img width="302" alt="Screen Shot 2020-10-10 at 4 50 32 PM" src="https://user-images.githubusercontent.com/13629122/95664763-d7a57e80-0b18-11eb-8dc1-22490978704f.png">

**Comment by cneidle** [comment]
I did find this searching through the DAI:

<img width="1061" alt="Screen Shot 2020-10-10 at 4 52 10 PM" src="https://user-images.githubusercontent.com/13629122/95664784-028fd280-0b19-11eb-845f-7afb92d6ab79.png">

**Comment by kwasiopoku** [comment]
This has been resolved.

**Comment by cneidle** [comment]
This is fixed. Thanks.  Do you know why this happened?  I'm concerned about things disappearing.  I am undoubtedly not noticing all cases where this may be happening...  thanks!

**Comment by kwasiopoku** [comment]
Resolved
