### ISSUE TITLE
odd display of utterance number

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#255]
<img width="592" alt="Screen Shot 2020-10-19 at 9 53 02 AM" src="https://user-images.githubusercontent.com/13629122/96465009-7c4d4d80-11f6-11eb-88d8-6dfb0cc887a7.png">

This is actually U11...  This appears this way consistently for all signs in this utterance.

**Comment by kwasiopoku** [comment]
Issue seems isolated to (F)BELONG sign in utterance 19 of 3-Ben collection.  Seems like an issue with the signbank query for the specific sign occurrence.

**Comment by cneidle** [comment]
This is also happening here:  #437
