### ISSUE TITLE
very small change needed

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#256]
There should be consistency in these displays.

Can you change "PLAY" to "Play" at the top, for ASLLVD isolated signs?

<img width="944" alt="Screen Shot 2020-10-25 at 11 38 27 AM" src="https://user-images.githubusercontent.com/13629122/97111679-a4392700-16b6-11eb-9b6c-e60919d428f7.png">

And for DawnSignPress isolated signs, change the button from "Play sign video" to "Sign video" and change the button from "Play sign clip" to "Sign clip" ?

For DawnSignPress signs from sentences, the "Sign clip" button should be changed to "Utterance video".

<img width="1070" alt="Screen Shot 2020-10-25 at 11 23 52 AM" src="https://user-images.githubusercontent.com/13629122/97111370-bfa33280-16b4-11eb-80bd-b056f79d4586.png">

Also - could we be consistent in the capitalization, so that all buttons have the first word capitalized and subsequent words not capitalized?

So, for this:  

<img width="970" alt="Screen Shot 2020-10-25 at 11 33 04 AM" src="https://user-images.githubusercontent.com/13629122/97111559-df872600-16b5-11eb-859d-282af142fcd1.png">

it should be "Original video" 

For this:

<img width="938" alt="Screen Shot 2020-10-25 at 11 33 45 AM" src="https://user-images.githubusercontent.com/13629122/97111576-f88fd700-16b5-11eb-9cc9-794ee0f94212.png">

it should be "Sign video" and "Utterance video"

For this:
<img width="918" alt="Screen Shot 2020-10-25 at 11 34 32 AM" src="https://user-images.githubusercontent.com/13629122/97111587-12c9b500-16b6-11eb-8dee-c507d5583828.png">

it should be "Sign video" and "Sign clip"

For this

<img width="1045" alt="Screen Shot 2020-10-25 at 11 36 38 AM" src="https://user-images.githubusercontent.com/13629122/97111645-62a87c00-16b6-11eb-86a8-f33f208b8472.png">

it should be "Sign video" and "Utterance video"

And for this

<img width="714" alt="Screen Shot 2020-10-25 at 11 37 35 AM" src="https://user-images.githubusercontent.com/13629122/97111664-89ff4900-16b6-11eb-9013-f31acdda6ed0.png">

it is correct, as "Sign clip"

**Comment by cneidle** [comment]
The above is mostly fixed, except for the DSP signs from sentences, where the "Sign clip" still needs to be changed to "Utterance video".  Thanks!

**Comment by kwasiopoku** [comment]
Fixed
