### ISSUE TITLE
Problem with display of handshapes for signs that occur only on the non-dominant hand

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#257]
In this example, 1"focus" is a 1-handed sign produced by the non-dominant hand, in parallel with the sign being fingerspelled by the dominant hand.  However, the handshape for this sign is shown as being on the dominant hand...

<img width="1496" alt="Screen Shot 2020-10-28 at 10 54 35 AM" src="https://user-images.githubusercontent.com/13629122/97453513-3128ee00-190c-11eb-9380-faadd3545f86.png">

**Comment by cneidle** [comment]
This problem persists.  Something is very wrong here - recall that 1"focus" occurs solely on the non-dominant hand:

<img width="791" alt="Screen Shot 2020-11-03 at 11 55 34 AM" src="https://user-images.githubusercontent.com/13629122/98016344-dab82580-1dcb-11eb-86b6-89e9f0dac796.png">

And this is made all that much more apparent by the non-optimal sorting that puts "WHAT" and 1"focus" at the top of the list... 

<img width="282" alt="Screen Shot 2020-11-03 at 11 54 58 AM" src="https://user-images.githubusercontent.com/13629122/98016496-0affc400-1dcc-11eb-9eba-a1b633f3bb73.png">

**Comment by kwasiopoku** [comment]
Collection parser is fixed for future uploads.  We need to delete 1 handed sign occurrences from signbank with glossing on the non dominant hand.

**Comment by kwasiopoku** [comment]
1-handed signs on non dominant hand have been removed from the signbank.
