### ISSUE TITLE
Problem with top item in Sign Bank sign list

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#26]
Clicking on "WHAT" or the sub-entry below it has no effect.

![screen shot 2017-10-13 at 9 40 22 am](https://user-images.githubusercontent.com/13629122/31549036-e4718f36-affa-11e7-8330-d0fb915ec844.png)

The previously selected item remains visible...

**Comment by kwasiopoku** [comment]
Fixed

**Comment by cneidle** [comment]
This specific issue is fixed, but for that top item, no start/end images are appearing:

![screen shot 2017-10-16 at 1 24 14 pm](https://user-images.githubusercontent.com/13629122/31625803-6543858e-b275-11e7-9f5a-a703d893d383.png)

![screen shot 2017-10-16 at 1 24 07 pm](https://user-images.githubusercontent.com/13629122/31625805-655eb78c-b275-11e7-8746-ef73a3fe5a09.png)

**Comment by kwasiopoku** [comment]
FIXED
