### ISSUE TITLE
Still more small ASLLVD fixes

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#265]
Could you please remove the ":i" at the end of these two examples, and move them in with the other occurrences of AGREE?

THANKS.

<img width="784" alt="Screen Shot 2020-11-26 at 2 53 50 PM" src="https://user-images.githubusercontent.com/13629122/100387980-5f771780-2ff7-11eb-936d-a1d39b577be8.png">

**Comment by cneidle** [comment]
One more + is needed on the following three examples.  The first two should be AIRPLANE+ and the third should be AIRPLANE++

<img width="969" alt="Screen Shot 2020-11-26 at 3 13 28 PM" src="https://user-images.githubusercontent.com/13629122/100389012-2be9bc80-2ffa-11eb-804d-6191bddae3e8.png">

<img width="949" alt="Screen Shot 2020-11-26 at 3 13 37 PM" src="https://user-images.githubusercontent.com/13629122/100389020-31470700-2ffa-11eb-916c-fb98ab43a716.png">

Looks good - thank you.

**Comment by kwasiopoku** [comment]
This is done.

**Comment by cneidle** [comment]
The AGREE issue at the top is only partially resolved.  THe ":i" has been removed, but these two now need to be merged with the other occurrences of AGREE, and the label "AGREE:i" at the top of the first screenshot below is no longer appopriate.  THANKS.


<img width="925" alt="Screen Shot 2020-11-27 at 10 48 07 AM" src="https://user-images.githubusercontent.com/13629122/100465988-33fb3800-309e-11eb-903a-5a3477d69230.png">

<img width="1159" alt="Screen Shot 2020-11-27 at 10 48 17 AM" src="https://user-images.githubusercontent.com/13629122/100465999-38275580-309e-11eb-9843-a9464bf37099.png">

**Comment by cneidle** [comment]
NEW ONE:

Could you please make this BALL++ (i.e., add two plusses)?  THANKS

<img width="940" alt="Screen Shot 2020-11-27 at 1 22 18 PM" src="https://user-images.githubusercontent.com/13629122/100476503-bb9f7180-30b3-11eb-8fdf-7ba468bdd241.png">

And could you please add one + to this one?

<img width="1001" alt="Screen Shot 2020-11-27 at 1 25 50 PM" src="https://user-images.githubusercontent.com/13629122/100476662-29e43400-30b4-11eb-8164-eae8029d5fbb.png">

And REMOVE the plus from this one?

<img width="972" alt="Screen Shot 2020-11-27 at 1 26 59 PM" src="https://user-images.githubusercontent.com/13629122/100476696-441e1200-30b4-11eb-8ce4-042bd959d101.png">

And add two plusses to this one, making it 4 in all, ANYWAY/NOT-MATTER++++

<img width="955" alt="Screen Shot 2020-11-27 at 1 27 58 PM" src="https://user-images.githubusercontent.com/13629122/100476764-6f086600-30b4-11eb-8e57-c1e31e038dc8.png">

Could you also please change 1018 from ANNOUNCE_2 to ANNOUNCE, and move that occurrence in with the other occurrences of ANNOUNCE?   THANKS.

<img width="767" alt="Screen Shot 2020-11-27 at 1 47 29 PM" src="https://user-images.githubusercontent.com/13629122/100477721-361dc080-30b7-11eb-9429-3ac63d266b88.png">

**Comment by kwasiopoku** [comment]
This is all done.  Thanks

**Comment by cneidle** [comment]
Beautiful.  Thanks very much!
