### ISSUE TITLE
Cases where we need new main entry for compounds with variants in the parts

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#266]
Example of what we need done- for the first one, we need each line under
the main entry of the compound to be its own main entry, e.g.

ALWAYS+FOREVER
- ALWAYS+FOREVER

ALWAYS+FOREVER_2
- ALWAYS+FOREVER_2

<img width="167" alt="Screen Shot 2020-11-27 at 11 05 13 AM" src="https://user-images.githubusercontent.com/13629122/100467493-88071c00-30a0-11eb-8b26-390045e45f61.png">

<img width="177" alt="Screen Shot 2020-11-27 at 12 39 12 PM" src="https://user-images.githubusercontent.com/13629122/100473989-a1629500-30ad-11eb-9229-5cb42b3a5559.png">

<img width="190" alt="Screen Shot 2020-11-27 at 11 15 26 AM" src="https://user-images.githubusercontent.com/13629122/100468178-e385d980-30a1-11eb-8cac-12aa0ad22c2a.png">

<img width="119" alt="Screen Shot 2020-11-27 at 11 21 31 AM" src="https://user-images.githubusercontent.com/13629122/100468603-bbe34100-30a2-11eb-808d-c63b4ef380cf.png">

<img width="183" alt="Screen Shot 2020-11-27 at 11 24 38 AM" src="https://user-images.githubusercontent.com/13629122/100468822-2d22f400-30a3-11eb-978e-54c5101feda1.png">

<img width="191" alt="Screen Shot 2020-11-27 at 11 25 16 AM" src="https://user-images.githubusercontent.com/13629122/100468855-41ff8780-30a3-11eb-814b-6582556521d5.png">

<img width="134" alt="Screen Shot 2020-11-27 at 11 28 07 AM" src="https://user-images.githubusercontent.com/13629122/100469099-a91d3c00-30a3-11eb-87fc-fd17a7199662.png">

<img width="158" alt="Screen Shot 2020-11-27 at 11 31 58 AM" src="https://user-images.githubusercontent.com/13629122/100469429-32cd0980-30a4-11eb-9a46-6e7dce54a7d1.png">

<img width="133" alt="Screen Shot 2020-11-27 at 11 36 32 AM" src="https://user-images.githubusercontent.com/13629122/100469724-d61e1e80-30a4-11eb-808a-5cdb1a38627b.png">

<img width="181" alt="Screen Shot 2020-11-27 at 11 45 02 AM" src="https://user-images.githubusercontent.com/13629122/100470311-074b1e80-30a6-11eb-8aff-dc4fcfdb058f.png">

<img width="159" alt="Screen Shot 2020-11-27 at 11 47 50 AM" src="https://user-images.githubusercontent.com/13629122/100470532-69a41f00-30a6-11eb-87f9-8cdb9d5fc721.png">

<img width="165" alt="Screen Shot 2020-11-27 at 12 06 13 PM" src="https://user-images.githubusercontent.com/13629122/100471792-049df880-30a9-11eb-87bf-5e0936b641c7.png">

<img width="145" alt="Screen Shot 2020-11-27 at 12 10 22 PM" src="https://user-images.githubusercontent.com/13629122/100472117-9dcd0f00-30a9-11eb-9e45-d2425d948a6f.png">

<img width="141" alt="Screen Shot 2020-11-27 at 12 15 53 PM" src="https://user-images.githubusercontent.com/13629122/100472496-5c892f00-30aa-11eb-9ad9-9de278ca7c8c.png">

<img width="171" alt="Screen Shot 2020-11-27 at 12 16 59 PM" src="https://user-images.githubusercontent.com/13629122/100472581-804c7500-30aa-11eb-83d1-7b4371ed3590.png">

<img width="156" alt="Screen Shot 2020-11-27 at 12 17 35 PM" src="https://user-images.githubusercontent.com/13629122/100472613-92c6ae80-30aa-11eb-9778-7772311fab4b.png">

These are missing their entries; I believe that ns-#PR was changed to ns-PUERTO-RICO, so the second one is presumably a remnant.

<img width="111" alt="Screen Shot 2020-11-27 at 11 19 02 AM" src="https://user-images.githubusercontent.com/13629122/100468427-69098980-30a2-11eb-87a3-21636c22ee0e.png">

<img width="253" alt="Screen Shot 2020-11-27 at 11 50 16 AM" src="https://user-images.githubusercontent.com/13629122/100470717-c1428a80-30a6-11eb-840a-69201ef60754.png">

COLD is misgrouped here.  (Must have been from a typo where the "C" didn't get typed) - COLD* (COLD+DOOR) should be under main entry "COLD".

<img width="289" alt="Screen Shot 2020-11-27 at 11 46 21 AM" src="https://user-images.githubusercontent.com/13629122/100470438-40838e80-30a6-11eb-9eb7-3406540b7749.png">

**Comment by cneidle** [comment]
This one is also missing an entry; probably also a remnant - I think ZERO_2 got changed to ZERO_3 in this compound...

<img width="310" alt="Screen Shot 2020-11-27 at 12 01 38 PM" src="https://user-images.githubusercontent.com/13629122/100471497-65790100-30a8-11eb-89fb-09d66d487d19.png">

This is also a remnant - it was obviously changed to something else:

<img width="112" alt="Screen Shot 2020-11-27 at 12 05 17 PM" src="https://user-images.githubusercontent.com/13629122/100471724-e0421c00-30a8-11eb-9a44-29e9e84021a4.png">

This one, too, is a remnant; I believe I also changed this one:

<img width="124" alt="Screen Shot 2020-11-27 at 12 12 32 PM" src="https://user-images.githubusercontent.com/13629122/100472259-eab0e580-30a9-11eb-9c1e-8873d2125ebc.png">

This one probably the same:

<img width="168" alt="Screen Shot 2020-11-27 at 12 14 16 PM" src="https://user-images.githubusercontent.com/13629122/100472367-1d5ade00-30aa-11eb-8153-9f64fed0b81c.png">


In the following (25)WANT* ((25(WANT+NEG) should be grouped under WANT

<img width="237" alt="Screen Shot 2020-11-27 at 12 14 55 PM" src="https://user-images.githubusercontent.com/13629122/100472454-44b1ab00-30aa-11eb-85df-66a803a5bbb2.png">

**Comment by cneidle** [comment]
For compounds that include "+part:indef" as the second part, I am not seeing the full compounds, only the compound parts.  And there is also an issue with the thumbnails.

<img width="534" alt="Screen Shot 2020-11-27 at 12 20 20 PM" src="https://user-images.githubusercontent.com/13629122/100472920-25ffe400-30ab-11eb-94bd-946e275f359d.png">

**Comment by cneidle** [comment]
There are also errors in how the above compounds containing "part:indef" are sorted.

![Uploading Screen Shot 2020-11-27 at 4.36.47 PM.png…]()

**Comment by cneidle** [comment]
The top item has not been fixed.

In the second group, the (25)WANT issue is still in need of attention.

This still needs to be fixed: For compounds that include "+part:indef" as the second part, I am not seeing the full compounds, only the compound parts.

The sorting issue  for part:indef is included in a different ticket.

**Comment by cneidle** [comment]
Here is another case.  These two entries should be distinct main variants

<img width="222" alt="Screen Shot 2022-08-17 at 8 41 13 AM" src="https://user-images.githubusercontent.com/13629122/185129579-29db8f40-7a06-40b9-aa64-512f7cfc9a54.png">

**Comment by cneidle** [comment]
one more:  RED+BLACK+(2h)CHECKERS should be its own main entry, not a variant under CHECKERS.

<img width="374" alt="Screen Shot 2022-08-17 at 6 58 18 PM" src="https://user-images.githubusercontent.com/13629122/185258169-f7d6908b-42f3-4dc3-a1f4-8fe3ef9a3bd6.png">

**Comment by cneidle** [comment]
one more:  

HEAR+(1h)RUMBLE should be its own main entry.

It should not be listed as a variant under HEAR+RUMBLE.

thanks.

**Comment by cneidle** [comment]
Another one:

INTERPRET+(1h)AGENT should be its own main entry, not a variant under INTERPRET+AGENT

**Comment by cneidle** [comment]
more:
 
CELEBRATE+(2h)IX-honorific:j  should be its own main entry, not a variant under IX-honorific

**Comment by cneidle** [comment]
PREACH+(1h)AGENT. should be its own main entry, not a variant under PREACH+AGENT

**Comment by cneidle** [comment]
SHOW-2p+AGENT should be its own main entry, not a variant under SHOW+AGENT

**Comment by cneidle** [comment]
(1h)TEACH+(1h)AGENT  should be its own main entry, not a variant under TEACH+AGENT

(1h)TEACH+AGENT  should also be its own main entry, not a variant under TEACH+AGENT

**Comment by cneidle** [comment]
ANY+ONE-pl-arc should be its own main entry, not a variant under ANY+ONE

**Comment by cneidle** [comment]
I have just gone through the list of compounds.  The following (all of which have been previously reported -- see the top of this ticket) still remain to be corrected.  There should never be more than one variant listed under a compound main entry.  Every compound variant should be its own main entry.  Thanks.


<img width="188" alt="Screen Shot 2022-09-02 at 9 56 24 AM" src="https://user-images.githubusercontent.com/13629122/188169176-14dfed48-0b4d-4f6b-af5a-022ba60db757.png">

<img width="188" alt="Screen Shot 2022-09-02 at 9 56 41 AM" src="https://user-images.githubusercontent.com/13629122/188169178-6764a0de-8d8c-4829-9206-816681e683fa.png">

<img width="183" alt="Screen Shot 2022-09-02 at 10 13 03 AM" src="https://user-images.githubusercontent.com/13629122/188169312-2222c440-10ac-44e5-9f85-7327fecaccab.png">

Also, this is incorrect:

<img width="204" alt="Screen Shot 2022-09-02 at 9 59 10 AM" src="https://user-images.githubusercontent.com/13629122/188169462-2bf37971-b5c3-44b9-b60f-5750d845b4de.png">

The main entry seems to have gotten cut off.  In any case,
that example has been reglossed, and when uploaded, it
should appear with the other examples of this:

<img width="245" alt="Screen Shot 2022-09-02 at 10 04 45 AM" src="https://user-images.githubusercontent.com/13629122/188169755-b9bbdee7-c8b0-4ac7-8325-cac88107319c.png">

although, as I told you, this entry appears correctly in the 
list of compounds, but not in the main list.

**Comment by cneidle** [comment]
The version with :j has now disappeared since re-uploading the edited SignStream file. But the problem with this compound not appearing in the Sign Bank list remains:

<img width="318" alt="Screen Shot 2022-09-03 at 5 31 19 PM" src="https://user-images.githubusercontent.com/13629122/188288327-20ad26be-f138-4f0a-ac95-c0e76b14b138.png">

**Comment by cneidle** [comment]
Remaining to be fixed: 
<img width="173" alt="Screen Shot 2022-10-14 at 1 38 46 PM" src="https://user-images.githubusercontent.com/13629122/195908030-6f88e37f-8363-42ad-8176-ecf6d9116741.png">

COLD needs to be moved out from here:

<img width="277" alt="Screen Shot 2022-10-14 at 1 45 07 PM" src="https://user-images.githubusercontent.com/13629122/195909043-32c729ff-6f0f-4cf2-9a9b-22b01ebffed4.png">

In the following (25)WANT* ((25(WANT+NEG) should be grouped under WANT

<img width="223" alt="Screen Shot 2022-10-14 at 1 49 39 PM" src="https://user-images.githubusercontent.com/13629122/195909774-61a82d3f-7f20-4ee5-a66b-cff6cbb3227e.png">

The compound at the bottom below should also be its own entry, but it is not showing up:

<img width="304" alt="Screen Shot 2022-10-14 at 1 51 55 PM" src="https://user-images.githubusercontent.com/13629122/195910210-f3fab9c2-9209-4a54-994b-aeb29b4f62fb.png">



- CN, 10/14

**Comment by kwasiopoku** [comment]
These have all been updated on dev1.   

CELEBRATE+(2h)IX-honorific:upward is grouped alphabetically under U.  This will need to be fixed in the sorting algorithm

**Comment by cneidle** [comment]
This is totally incorrect:

<img width="261" alt="Screen Shot 2022-10-15 at 1 14 05 PM" src="https://user-images.githubusercontent.com/13629122/195999366-1e6cf652-539c-4112-b308-b61cfa4328da.png">

That compound should be placed as follows:

<img width="313" alt="Screen Shot 2022-10-15 at 1 13 05 PM" src="https://user-images.githubusercontent.com/13629122/195999382-7f248014-d8d2-4b36-a591-b11b437bf314.png">

CELEBRATE+(2h)IX-honorific:upward

<img width="168" alt="Screen Shot 2022-10-15 at 1 13 11 PM" src="https://user-images.githubusercontent.com/13629122/195999385-48c0f805-e536-4df7-8f74-b576cf8aed08.png">

Please let me know if you have any questions about this.  I can't imagine why you would put it under U.

Thanks.

**Comment by kwasiopoku** [comment]
The issue was in the sorting algo where it was getting sorted with "U" because of the ":" before upward.  This has been fixed and pushed to dev1

**Comment by cneidle** [comment]
Ok. great!

Thanks very much.  I misinterpreted your message to suggest that the correction was to list it under U.

Looks perfect now, anyway :-).  THANKS. AGAIN.
