### ISSUE TITLE
Latest ASLLVD small change requests :-). THANKS.

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#268]
For 4544, please change the handshapes to match those of 4543:

<img width="785" alt="Screen Shot 2020-11-28 at 11 25 21 AM" src="https://user-images.githubusercontent.com/13629122/100520788-b9015280-316d-11eb-9570-5cca05b99593.png">

For #JOB, please change the handshapes for 77 to match those of 76:

<img width="770" alt="Screen Shot 2020-11-28 at 11 36 47 AM" src="https://user-images.githubusercontent.com/13629122/100520851-27461500-316e-11eb-99fd-56bcd3ab0f08.png">

**Comment by kwasiopoku** [comment]
This is done.

**Comment by cneidle** [comment]
thanks!
