### ISSUE TITLE
Classifier counts are off

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#27]
![screen shot 2017-10-13 at 9 48 23 am](https://user-images.githubusercontent.com/13629122/31549289-b9ae0d5a-affb-11e7-9eb3-02ab10496c06.png)

DCL count is 1, although there are 4 examples
LCL count is 2, although there are 3 examples

**Comment by kwasiopoku** [comment]
Hi Carol are both of these considered classifiers (One has a semi colon and the other does not)?

DCL"opening can"
DCL:crvd-L"bagel"
--

**Comment by cneidle** [comment]
Hi - 

Yes - both are classifiers.

Classifiers very often (but not always) have a colon followed by handshape
preceding the “description of the meaning”.

Thanks,
 Carol

**Comment by kwasiopoku** [comment]
Fixed
