### ISSUE TITLE
A few more requested ASLLVD changes

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#270]
For this:

Please delete entirely ID 6029.  For 6030, that should be relabeled as VEIN+.  We should have a new main entry VEIN. 
The third example, from the RIT data collection, will be reglossed as VEIN+NERVY and reuploaded.  

So the main entry NERVE/VEIN should be completely deleted.

<img width="946" alt="Screen Shot 2020-11-29 at 1 08 53 PM" src="https://user-images.githubusercontent.com/13629122/100549926-35fefb80-3244-11eb-9ada-7f2c1a9f21f7.png">

**Comment by kwasiopoku** [comment]
This has been fixed

**Comment by cneidle** [comment]
thank you!
