### ISSUE TITLE
Several additional changes to ASLLVD data

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#274]
For 6045, please change the gloss "NEXT" to "UP-AHEAD"  (and move it into that group):

<img width="777" alt="Screen Shot 2020-12-08 at 11 27 15 AM" src="https://user-images.githubusercontent.com/13629122/101510818-62073480-3948-11eb-8449-ad36d2550653.png">

<img width="108" alt="Screen Shot 2020-12-08 at 11 25 33 AM" src="https://user-images.githubusercontent.com/13629122/101510591-210f2000-3948-11eb-876b-36d8f22d2b03.png">

<img width="792" alt="Screen Shot 2020-12-08 at 11 23 42 AM" src="https://user-images.githubusercontent.com/13629122/101510507-050b7e80-3948-11eb-9613-45990eae6228.png">

fixed -cn

**Comment by cneidle** [comment]
For 6537, please change the start and end dominant hand from "B" to "B-L"--
so that the handshapes will match 6536.

<img width="487" alt="Screen Shot 2020-12-08 at 11 29 41 AM" src="https://user-images.githubusercontent.com/13629122/101512049-c629f880-3948-11eb-9460-7cc81d21b074.png">


fixed --cn

**Comment by cneidle** [comment]
For 6545, please change the handshapes so that they match those
in the other two examples shown (i.e., from "I" to "Y"):

<img width="774" alt="Screen Shot 2020-12-08 at 11 34 21 AM" src="https://user-images.githubusercontent.com/13629122/101512752-5a945b00-3949-11eb-9fd4-3542dfe35356.png">

Thanks!

fixed. --cn

**Comment by cneidle** [comment]
For 7174, please change all handshapes from "5" to "crvd-5", i.e., to match the 3 examples below -- from Rachel and Cory.  Thanks!

<img width="919" alt="Screen Shot 2020-12-08 at 11 44 56 AM" src="https://user-images.githubusercontent.com/13629122/101514369-2fab0680-394b-11eb-9f43-002a9a2f03a8.png">


fixed --cn

**Comment by cneidle** [comment]
For 6604, please change the start handshapes from "baby-O" to "O"

<img width="917" alt="Screen Shot 2020-12-08 at 11 49 09 AM" src="https://user-images.githubusercontent.com/13629122/101514673-87497200-394b-11eb-9c39-d7ab74284128.png">


to match the handshapes in the example for OPPORTUNITY from Rachel, below:

<img width="660" alt="Screen Shot 2020-12-08 at 11 49 27 AM" src="https://user-images.githubusercontent.com/13629122/101514653-81ec2780-394b-11eb-88ff-b246488ea229.png">

fixed. --cn

**Comment by cneidle** [comment]
Please add a + after READ in 7188, so that it will be READ+

<img width="531" alt="Screen Shot 2020-12-08 at 11 52 21 AM" src="https://user-images.githubusercontent.com/13629122/101515039-ed35f980-394b-11eb-9834-424a82f86dff.png">

fixed. --cn

**Comment by cneidle** [comment]
For REDUCE, 7221, please change the dominant start handshape only from B to B-L (the same as the dominant start handshape in the example below). 

<img width="513" alt="Screen Shot 2020-12-08 at 12 26 32 PM" src="https://user-images.githubusercontent.com/13629122/101519007-a4cd0a80-3950-11eb-8fe4-04b4338b3751.png">

fixed. --cn

**Comment by cneidle** [comment]
Please add a + to 740, making it:  (Y)SHAVE+


<img width="558" alt="Screen Shot 2020-12-14 at 12 50 05 PM" src="https://user-images.githubusercontent.com/13629122/102116845-8e6cf600-3e0b-11eb-9bd9-73bfa14c44b8.png">

And for all three of these, please remove all +'s so that these will just be:  SAVE-MONEY

<img width="811" alt="Screen Shot 2020-12-14 at 12 56 11 PM" src="https://user-images.githubusercontent.com/13629122/102117087-e146ad80-3e0b-11eb-9d9a-1a1e200f2a2e.png">

Below, 7531 and 7533 should have only 1 +  rather than 2 (SEE-SEE+)

<img width="551" alt="Screen Shot 2020-12-14 at 1 29 28 PM" src="https://user-images.githubusercontent.com/13629122/102120353-6b911080-3e10-11eb-8011-2a8770ea805f.png">


Thanks!

fixed. --cn

**Comment by cneidle** [comment]
For 7563, the start and end handshapes are missing for the non-dominant hand.  The "crvd-flat-B" should be added for both.

<img width="543" alt="Screen Shot 2020-12-14 at 1 37 13 PM" src="https://user-images.githubusercontent.com/13629122/102121167-87e17d00-3e11-11eb-8daa-6d8afe0e542d.png">

Please remove 1 + from each of these.  So 7620 should be SEW and 7621 should be SEW+

<img width="536" alt="Screen Shot 2020-12-14 at 1 40 49 PM" src="https://user-images.githubusercontent.com/13629122/102121482-08a07900-3e12-11eb-9316-789232a3a88f.png">


For 7592, the handshapes for the dominant and non-dominant hand need to be reversed, both for start and end.

<img width="518" alt="Screen Shot 2020-12-14 at 1 38 27 PM" src="https://user-images.githubusercontent.com/13629122/102121294-bfe8c000-3e11-11eb-893b-a7cf1e421a71.png">

For 7721, please change the start handshape on the dominant hand from "B-L" to "bent-B-L"

<img width="591" alt="Screen Shot 2020-12-14 at 1 43 05 PM" src="https://user-images.githubusercontent.com/13629122/102121709-67fe8900-3e12-11eb-8a9e-d1dbb097142d.png">

Below, 7765 should be SIT++ (rather than SIT).  7767 should also be SIT++ (rather than SIT+)

<img width="536" alt="Screen Shot 2020-12-14 at 1 47 36 PM" src="https://user-images.githubusercontent.com/13629122/102123692-3935e200-3e15-11eb-8684-a0cccc78f075.png">

fixed --cn

**Comment by cneidle** [comment]
For these examples, 1747 should be BUILD+. 1750 should be BUILD++.

<img width="572" alt="Screen Shot 2020-12-14 at 2 06 30 PM" src="https://user-images.githubusercontent.com/13629122/102123922-99c51f00-3e15-11eb-80a5-cf5577a5c1b7.png">

fixed. -cn

**Comment by cneidle** [comment]
Please delete this example, 4186:

<img width="777" alt="Screen Shot 2020-12-16 at 10 52 40 AM" src="https://user-images.githubusercontent.com/13629122/102372192-f434bb80-3f8c-11eb-9b1e-81dd3df0635d.png">

fixed. --cn

**Comment by cneidle** [comment]
Apologies if this is a duplicate request.  I thought I had already submitted this, but I can't find it.

Please change these two occurrences of VISIT:i to VISIT

<img width="920" alt="Screen Shot 2020-12-16 at 11 45 43 AM" src="https://user-images.githubusercontent.com/13629122/102378912-4d541d80-3f94-11eb-9c82-d02210c56ace.png">

fixed.  --cn

**Comment by cneidle** [comment]
Please remove one + from each of the following, making 7905 SOON, and 7907 SOON++ and 7915 and 7916 should both be SOUP+ and 7997 and 7998 should both be STATISTICS : 
  
<img width="677" alt="Screen Shot 2020-12-17 at 1 02 15 PM" src="https://user-images.githubusercontent.com/13629122/102525527-61694f00-4068-11eb-874d-4ea297711e2a.png">

<img width="505" alt="Screen Shot 2020-12-17 at 1 06 57 PM" src="https://user-images.githubusercontent.com/13629122/102525819-cf157b00-4068-11eb-94e5-173e18f076bc.png">

<img width="573" alt="Screen Shot 2020-12-17 at 1 08 52 PM" src="https://user-images.githubusercontent.com/13629122/102526031-1865ca80-4069-11eb-900f-7505dc68f089.png">

**NOT FIXED: 7997**

**Comment by cneidle** [comment]
Please change this from STAB to STAB+ 

<img width="503" alt="Screen Shot 2020-12-17 at 1 11 20 PM" src="https://user-images.githubusercontent.com/13629122/102526288-72669000-4069-11eb-9f35-0fe1b9745498.png">

fixed --cn

**Comment by cneidle** [comment]
Please remove one +, making it STIMULATE+

<img width="546" alt="Screen Shot 2020-12-18 at 11 35 17 AM" src="https://user-images.githubusercontent.com/13629122/102638306-4872a380-4125-11eb-8748-f2e18fa9e346.png">

fixed.  - cn

**Comment by cneidle** [comment]
For example 524 only;, please regloss this as EVERY-THURSDAY (and move it in with the other examples of EVERY-THURSDAY):

<img width="725" alt="Screen Shot 2021-01-02 at 8 07 18 PM" src="https://user-images.githubusercontent.com/13629122/103469713-3f452180-4d36-11eb-9ead-4461285a26ed.png">

fixed --cn

**Comment by cneidle** [comment]
Please regloss CLOSE-DOOR_2 as CLOSE-DOOR and move in with the other examples of CLOSE-DOOR.
I will do the same for the 2 examples from RIT (in effect merging CLOSE-DOOR_2 with CLOSE-DOOR).
One that is done, the main entry CLOSE-DOOR_2 should be permanently deleted.  Thanks !!

<img width="787" alt="Screen Shot 2021-01-02 at 8 10 56 PM" src="https://user-images.githubusercontent.com/13629122/103469754-ca261c00-4d36-11eb-92b5-26376edb2aa3.png">

fixed --cn

**Comment by cneidle** [comment]
For example 2831 only, please regloss from DIM to DIM_2 and move that example in with the other examples of DIM_2.
Thanks.

<img width="780" alt="Screen Shot 2021-01-02 at 8 15 11 PM" src="https://user-images.githubusercontent.com/13629122/103469794-589a9d80-4d37-11eb-9ac2-7b2bc69631c1.png">

fixed --cn

**Comment by cneidle** [comment]
For the first three listed here -- examples 3252, 3251, and 3250 -- please delete the +, changing them from ELEVEN+ to ELEVEN.

<img width="789" alt="Screen Shot 2021-01-02 at 8 19 08 PM" src="https://user-images.githubusercontent.com/13629122/103469824-e080a780-4d37-11eb-85aa-71c399134941.png">

fixed --cn

**Comment by cneidle** [comment]
Please change (2h)CHRISTMAS to (2h)CHRISTMAS_2

<img width="1056" alt="Screen Shot 2021-01-03 at 10 50 34 AM" src="https://user-images.githubusercontent.com/13629122/103482901-94724900-4db1-11eb-94ff-e5e345b9bc4a.png">

I will make the same changes to some of the examples of (2h)CHRISTMAS from other data sets, but there will still be a gloss of (2h)CHRISTMAS once the corrections have been made.



-------------

**NOT FIXED**

The newly glossed (2h)CHRISTMAS_2 needs to be its own (new) entry/variant.

<img width="749" alt="Screen Shot 2021-01-12 at 9 00 52 PM" src="https://user-images.githubusercontent.com/13629122/104396786-55fb2d80-5519-11eb-8d63-09382a8070d4.png">

**Comment by cneidle** [comment]
Please change "POSS-2p-arc" to "POSS-2p-pl-arc".  I will make the same change to the RIT data, and "POSS-2p-arc" should be permanently deleted.  Thanks!

<img width="794" alt="Screen Shot 2021-01-03 at 11 53 07 AM" src="https://user-images.githubusercontent.com/13629122/103484116-5e859280-4dba-11eb-8970-9a0d5debae65.png">

fixed. --cn

**Comment by kwasiopoku** [comment]
These corrections have been applied

**Comment by cneidle** [comment]
There are two issues above that have not been fixed.  Please search for **NOT FIXED** ...

THANK YOU for making all these changes !!!!!

**Comment by cneidle** [comment]
THANKS
