### ISSUE TITLE
Latest requests for small fixes to ASLLVD data - thanks!

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#277]
PlEASE regloss only 3777 from FIRE to FIRE/BURN, and move it in with the other examples of the variant FIRE/BURN.  Thanks.

<img width="687" alt="Screen Shot 2021-01-12 at 2 28 56 PM" src="https://user-images.githubusercontent.com/13629122/104363069-ab681800-54e2-11eb-9cc9-beb08c07dce2.png">

<img width="730" alt="Screen Shot 2021-01-12 at 2 29 06 PM" src="https://user-images.githubusercontent.com/13629122/104363082-b02ccc00-54e2-11eb-88a2-024e96abad33.png">

done -CN

**Comment by cneidle** [comment]
Please regloss only 40031 and 40032, changing the first part of the compound from FIRE/BURN to FIRE.
So there will be a new main entry FIRE+BURN for those two.
We will also need to change the corresponding entries for the parts of those two compounds.

<img width="813" alt="Screen Shot 2021-01-12 at 2 31 33 PM" src="https://user-images.githubusercontent.com/13629122/104363392-1ade0780-54e3-11eb-86fa-a58bd43da23f.png">

done -CN

**Comment by cneidle** [comment]
Please remove 1 + from each of the following:

current gloss                         ID #             to be corrected to

(V)VODKA+                             707                  (V)VODKA
SUITCASE++                          8114                SUITCASE+
SUITCASE++                          8115                SUITCASE+
SUITCASE++                          8116                SUITCASE+
SUMMER+                              8122                SUMMER
SUMMER+                              8123                SUMMER
SUNDAY+                               8129                SUNDAY
TAKE-ADVANTAGE++           8198                TAKE-ADVANTAGE+
TALK-TO-SELF+                     8231                TALK-TO-SELF
TALK+                                     8226                TALK
TALK++                                   8227                TALK+
TEASE++                                8261                TEASE+
TEASE++                                8262                TEASE+
TEASE++                                8263                TEASE+
THINK+TALK-TO-SELF+       41057                THINK+TALK-TO-SELF   
THINK+TALK-TO-SELF++     41058               THINK+TALK-TO-SELF+
TIGER+                                    8394                TIGER
TOOTHBRUSH++                   8438                TOOTHBRUSH+
TOURNAMENT+                     8475                TOURNAMENT
TOURNAMENT+                     8476                TOURNAMENT
TRAFFIC+                                8485                TRAFFIC
TRAFFIC+++                           8486                TRAFFIC++
TRANSPORTATION+              8495                TRANSPORTATION
VODKA_2+                              8708                 VODKA_2

WIND+                                    8872                 WIND
WIND+                                    8873                 WIND
WINE++                                  8878                 WINE+
WINE++                                  8879                 WINE+
WISDOM+                              8882                 WISDOM
WISDOM+                              8883                 WISDOM
WOOD++                               8901                 WOOD+
WOOD++                               8903                 WOOD+
WOOD+++                             8904                 WOOD++
WORK-OUT+                         8915                  WORK-OUT
WORK-OUT+                         8916                  WORK-OUT
WORK-OUT+                         8917                  WORK-OUT
WORK-OUT+                         8918                 WORK-OUT
WORK-OUT+                         8919                  WORK-OUT
WORK-OUT++                       8921                  WORK-OUT+

done -CN

**Comment by cneidle** [comment]
Please remove **2** +'S from each of the following:

current gloss                         ID #             to be corrected to

TASTE++                             8246             TASTE
TASTE++                             8247             TASTE
TASTE++                             8248             TASTE
TASTE++                             8249             TASTE

(W)WAR++                             713              (W)WAR
(W)WAR++                             714              (W)WAR

=========================

Please change the glosses below as indicated --

FROM                          ID #                          TO

UNDERSTAND_2        8606                  UNDERSTAND           **Needs to be moved; see comment at the bottom.**
VOCABULARY_2++    8706                  VOCABULARY++        **Needs to be moved; see comment at the bottom.**

WHAT                         8822                   "WHAT"        **Needs to be moved; see comment at the bottom.**
WHAT                         8823                  "WHAT"        **Needs to be moved; see comment at the bottom.**

=========================


Please add 1 + to the examples below:

current gloss                         ID #             to be corrected to

VOICE                                    8709            VOICE+
VOTE                                     8722             VOTE+
ns-WASHINGTON                6498            ns-WASHINGTON+

=========================

Please add **2** +'s to the examples below:

current gloss                         ID #             to be corrected to

TOUGH                                  8464            TOUGH++
TOUGH                                  8465            TOUGH++

**Comment by cneidle** [comment]
For THAN   8292, change   
     both start DH/ND from "B" to "B-L" 
     the  DH-end from   "B" to "B-L" and 
     the ND-end from "rlxd" to   "bent-B-L"

<img width="679" alt="Screen Shot 2021-01-12 at 3 39 48 PM" src="https://user-images.githubusercontent.com/13629122/104370159-706ae200-54ec-11eb-9290-2df8d982bd6d.png">


done -CN

**Comment by cneidle** [comment]
For  TOUCH   8459, add handshapes for the non-dominant hand, both start and end, which should be the "S" handshape in both places:

<img width="781" alt="Screen Shot 2021-01-12 at 3 44 39 PM" src="https://user-images.githubusercontent.com/13629122/104370632-27675d80-54ed-11eb-83fc-0890916a417f.png">


done -CN

**Comment by cneidle** [comment]
Please change: 

ns-WASHINGTON        6499          

to:

ns-WASHINGTON+fs-DC

(This will mean adding each of the component parts of the compound, as well.)

thanks!!


done -CN

**Comment by cneidle** [comment]
A few more:  

Please remove 1 + to the examples below:

current gloss                             ID #             to be corrected to

WRENCH/PLUMBING+          8947            WRENCH/PLUMBING
WRENCH/PLUMBING+          8948            WRENCH/PLUMBING
WRENCH/PLUMBING++        8949            WRENCH/PLUMBING+

The above are done.  -CN


For    WRITE+AGENT           41252
Change   DH-Start from "1" to "baby-O" and change ND-start from  "empty" to "B-L"

**This is still not correct.  See comment at the bottom.**

**Comment by cneidle** [comment]
There is still a problem with some signs that are produced solely on the non-dominant hand showing up as if they were produced with the dominant hand.  I thought we had discussed this and you had eliminated the problem, but... 

<img width="711" alt="Screen Shot 2021-01-16 at 6 06 35 PM" src="https://user-images.githubusercontent.com/13629122/104825157-3409ef80-5826-11eb-84f4-9741a0585792.png">


<img width="794" alt="Screen Shot 2021-01-16 at 6 08 49 PM" src="https://user-images.githubusercontent.com/13629122/104825161-3b30fd80-5826-11eb-9200-c188a83486d5.png">

<img width="786" alt="Screen Shot 2021-01-16 at 6 09 53 PM" src="https://user-images.githubusercontent.com/13629122/104825164-43893880-5826-11eb-8ac3-ccf9895844e1.png">

Same problem with VOICE in U16 (twice).

These are not isolated examples.  There are many other cases, e.g., several with (1h)part:indef, e.g.

<img width="710" alt="Screen Shot 2021-01-16 at 6 21 32 PM" src="https://user-images.githubusercontent.com/13629122/104827042-cf4f9480-5827-11eb-8615-bb9cdcbeb203.png">
<img width="607" alt="Screen Shot 2021-01-16 at 6 21 01 PM" src="https://user-images.githubusercontent.com/13629122/104827043-cf4f9480-5827-11eb-8920-2dd62663f01f.png">

<img width="1132" alt="Screen Shot 2021-01-16 at 6 22 41 PM" src="https://user-images.githubusercontent.com/13629122/104827051-dd051a00-5827-11eb-8ea7-f4c73f753b50.png">

**Comment by cneidle** [comment]
Also, there are some missing thumbnails and videos from 3-Ben-Voice-Life .

<img width="788" alt="Screen Shot 2021-01-16 at 6 09 22 PM" src="https://user-images.githubusercontent.com/13629122/104825177-57cd3580-5826-11eb-97dc-147b77eaf7e9.png">

<img width="785" alt="Screen Shot 2021-01-16 at 6 09 14 PM" src="https://user-images.githubusercontent.com/13629122/104825178-57cd3580-5826-11eb-8a81-a90090a1088b.png">

**Comment by kwasiopoku** [comment]
This has been resolved


**BELOW I have explained the problems that remain.  THANKS.**

**Comment by cneidle** [comment]
UNDERSTAND_2 was changed to UNDERSTAND.  But it also needs to be moved into with the other examples of UNDERSTAND, and UNDERSTAND_2 should be removed as a gloss.  Thanks.

<img width="795" alt="Screen Shot 2021-01-26 at 6 05 38 PM" src="https://user-images.githubusercontent.com/13629122/105917981-324be300-6001-11eb-96c1-daef8fc8a7c4.png">

Same for VOCABULARY_2:

<img width="791" alt="Screen Shot 2021-01-26 at 6 07 26 PM" src="https://user-images.githubusercontent.com/13629122/105918200-8ce53f00-6001-11eb-9d30-321f6eda41ff.png">

Same for "WHAT""

<img width="786" alt="Screen Shot 2021-01-26 at 6 09 55 PM" src="https://user-images.githubusercontent.com/13629122/105918357-ca49cc80-6001-11eb-9929-20d094dd4927.png">

**Comment by cneidle** [comment]
For WRITE+AGENT 41252,

<img width="559" alt="Screen Shot 2021-01-26 at 6 18 33 PM" src="https://user-images.githubusercontent.com/13629122/105919113-06c9f800-6003-11eb-902d-8d1c97562204.png">

the dominant hand start should be "baby-O"  (not "D") and the ND-start should be changed from "empty" to "B-L"

**Comment by kwasiopoku** [comment]
This is complete.

**Comment by cneidle** [comment]
thank you VERY much !!!!!!
