### ISSUE TITLE
A few more requests - thank you - for the ASLLVD data

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#278]
Please regloss 4439 to be GROUP/TOGETHER-pl (and moved in with the other occurrence of that variant).

<img width="1100" alt="Screen Shot 2021-01-17 at 4 57 10 PM" src="https://user-images.githubusercontent.com/13629122/104857292-53b41d00-58e5-11eb-9225-0b1c8c6ba7a4.png">

done -CN

**Comment by cneidle** [comment]
Please regloss 40171  as GROW++COLLECTwg and move in with other examples 

<img width="160" alt="Screen Shot 2021-01-17 at 5 10 44 PM" src="https://user-images.githubusercontent.com/13629122/104857506-f91bc080-58e6-11eb-973b-e1016914feca.png">
of that gloss.

<img width="748" alt="Screen Shot 2021-01-17 at 5 06 24 PM" src="https://user-images.githubusercontent.com/13629122/104857406-624f0400-58e6-11eb-82eb-d29236d2c217.png">

Also the parts of the compounds need to be modified accordingly.

done -CN

**Comment by cneidle** [comment]
For 4232 only, please change the gloss from GIVE to GIVE_2 and move that in with the other examples of GIVE_2.  Thanks.

<img width="783" alt="Screen Shot 2021-01-20 at 2 37 03 PM" src="https://user-images.githubusercontent.com/13629122/105225839-2c4f9100-5b2d-11eb-9fb4-6a509df44249.png">



<img width="798" alt="Screen Shot 2021-01-20 at 2 36 52 PM" src="https://user-images.githubusercontent.com/13629122/105225828-278add00-5b2d-11eb-8e06-b682bf6353a7.png">

done -CN

**Comment by cneidle** [comment]
For 4270, please change from GO-AWAY_2 to GO-AWAY_2+++

<img width="776" alt="Screen Shot 2021-01-20 at 2 40 30 PM" src="https://user-images.githubusercontent.com/13629122/105226099-88b2b080-5b2d-11eb-9592-1ed9b4744263.png">

done -CN

**Comment by cneidle** [comment]
We will merge AGE with OLD.  I will regloss the two examples from the continuous signing data.  Please change AGE to OLD as follows:  6552 should be changed from AGE to OLD+++ and 6551 should be changed to OLD+.
Then AGE should be deleted as a possible gloss for the Sign Bank.  Thanks !!
<img width="837" alt="Screen Shot 2021-01-22 at 10 48 27 AM" src="https://user-images.githubusercontent.com/13629122/105512867-a6078c00-5c9f-11eb-8e11-3c49f6d5fe1d.png">

done -CN

**Comment by kwasiopoku** [comment]
This is complete

**Comment by cneidle** [comment]
Thank you !!!
