### ISSUE TITLE
Help for (1h)CANNOT

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#279]
Hi Augustine, 

This sign had been marked to be hidden, but since it is the only occurrence of this sign,
it came back unhidden.  Could you please remove this from the Sign Bank?  We want to
retain it for the DAI sentence-level searches...  THANKS!

<img width="1042" alt="Screen Shot 2021-01-29 at 1 27 16 PM" src="https://user-images.githubusercontent.com/13629122/106313345-09606380-6236-11eb-99e3-9804e37c1706.png">

**Comment by cneidle** [comment]
PS. Isn't this a case that should have been detected by the algorithm you developed, to identify signs where different things were happening on the 2 hands, including cases where that happens in the primary (/only) occurrence ??

**Comment by cneidle** [comment]
(1h)CANNOT is still showing up; it is not hidden, although it was marked to be hidden.  This issue still needs to be addressed.

**Comment by kwasiopoku** [comment]
This has been resolved on dev1.cs
