### ISSUE TITLE
same and different handshape selectors are all not working

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#28]
E.g. Searching for Same start and end handshape on the dominant hand does not work

![screen shot 2017-10-13 at 9 59 31 am](https://user-images.githubusercontent.com/13629122/31550889-d6750e3e-b000-11e7-9cd4-b2fdbbb48725.png)

**Comment by kwasiopoku** [comment]
This seems to work for me.

**Comment by cneidle** [comment]
"Dominant hand same start and end handshapes" search - results include fingerspelled and loan signs, which clearly do not have same start and end handshapes.

<img width="644" alt="screen shot 2017-10-14 at 11 31 28 am" src="https://user-images.githubusercontent.com/13629122/31576920-67717710-b0d3-11e7-8f88-64471b37e55e.png">

<img width="767" alt="screen shot 2017-10-14 at 11 31 08 am" src="https://user-images.githubusercontent.com/13629122/31576921-67800ece-b0d3-11e7-890c-fcc791e03dbe.png">

Those are far from the only problems.

For example "dominant different start and end handshapes" search - results include CAR nS 
(1h)part:indef

<img width="387" alt="screen shot 2017-10-14 at 11 40 54 am" src="https://user-images.githubusercontent.com/13629122/31577003-ac6bca7c-b0d4-11e7-84d7-a375ddf9dbb2.png">
although clicking on the "2" in both cases shows a very large set of results.

Unless this means that there are 2 cases for each of those examples that were incorrectly annotated in this respect - sigh.

I think my suggestion would be to eliminate the  same and different handshape options
from the search for now, because the task of correcting the massive number of annotation errors (if that's what we're dealing with here) would be daunting and not something I can do in the next 10 days...

**Comment by cneidle** [comment]
I would suggest that we revise the interface to reflect the decision that we just made, e.g.:

![revised-search](https://user-images.githubusercontent.com/13629122/31585550-b374d206-b191-11e7-9891-bbe6830516b0.png)

Thanks!

**Comment by cneidle** [comment]
We would need to decide how this would interact with the upper part of the search.
Would any selection in this region automatically DE-SELECT all but lexical options in the top part ??

i.e., result in:

<img width="523" alt="screen shot 2017-10-15 at 10 18 58 am" src="https://user-images.githubusercontent.com/13629122/31585595-56f567b0-b192-11e7-9963-77c1df2eb8aa.png">

**Comment by kwasiopoku** [comment]
fixed

**Comment by cneidle** [comment]
De-selection does not seem to be working.  

1) Selecting something in that region does not de-select all but lexical (although the lexical signs included among the results appear, correctly, to be 1-handed).

2) Manually selecting "lexical" and "1-handed" or "2-handed" does appear to give the correct results, however.

Related issue: 

3) I selected lexical signs, same start/end hs for dominant hand, and start hs on dominant hand = A.
The handshape selection does not show up on the top of the search results page:

![screen shot 2017-10-16 at 1 17 47 pm](https://user-images.githubusercontent.com/13629122/31625617-ac398fe8-b274-11e7-8102-b1444fc0b947.png)

More significantly, the results include examples where this condition is satisfied only on the *non-dominant* hand:

![screen shot 2017-10-16 at 1 19 56 pm](https://user-images.githubusercontent.com/13629122/31625650-c6b677e6-b274-11e7-9532-b0b40efb1b43.png)

**Comment by kwasiopoku** [comment]
Selecting A on dominant hand and specifying Same start/end does not return the right results.  Look at ROWING as an example.

**Comment by kwasiopoku** [comment]
Fixed
