### ISSUE TITLE
DAI display - 1) icons for playing the videos; and 2) problems with thumbnails not appearing (e.g., for 1-Ben file)

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#280]
When we have 1 view available, we should be seeing 1 icon for playing... 

I thought that had been working properly, but it isn't now -- both for utterance and sign searches. 

Thanks.

<img width="813" alt="Screen Shot 2021-02-03 at 9 56 31 AM" src="https://user-images.githubusercontent.com/13629122/106764887-3b8f0e00-6606-11eb-8023-029ababd77bb.png">

<img width="840" alt="Screen Shot 2021-02-03 at 9 57 57 AM" src="https://user-images.githubusercontent.com/13629122/106764960-4fd30b00-6606-11eb-961d-9e894404a361.png">

<img width="817" alt="Screen Shot 2021-02-03 at 9 59 05 AM" src="https://user-images.githubusercontent.com/13629122/106765206-8c9f0200-6606-11eb-97cb-94ace694bfa1.png">

It does currently work properly in the dai -- but only for sign search, not for utterance search:

<img width="690" alt="Screen Shot 2021-02-03 at 10 01 52 AM" src="https://user-images.githubusercontent.com/13629122/106765524-e1427d00-6606-11eb-8961-6e3af2f16876.png">

<img width="694" alt="Screen Shot 2021-02-03 at 10 02 58 AM" src="https://user-images.githubusercontent.com/13629122/106765672-0df69480-6607-11eb-83a2-d4c271b4ada0.png">

**Comment by cneidle** [comment]
Thumbnails also missing in Sign Bank for 1-Ben file

<img width="699" alt="Screen Shot 2021-02-03 at 10 11 58 AM" src="https://user-images.githubusercontent.com/13629122/106766860-464aa280-6608-11eb-8953-06bd61d0c430.png">

**Comment by cneidle** [comment]
This problem with the 1-Ben file has not been fixed, and now affects both the dev1 and dai servers.

**Comment by kwasiopoku** [comment]
Resolved

**Comment by cneidle** [comment]
This still needs to be fixed.

**Comment by kwasiopoku** [comment]
I have confirmed that this has been fixed on dev1
