### ISSUE TITLE
special characters - dev1 " show up as ?

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#282]
in translation field

<img width="1034" alt="Screen Shot 2021-02-04 at 5 41 40 PM" src="https://user-images.githubusercontent.com/13629122/106964647-6e252d80-6710-11eb-802f-f85ff499a2ac.png">

**Comment by cneidle** [comment]
This remains a problem for some of the newly visible data, e.g.

<img width="252" alt="Screen Shot 2021-02-20 at 9 44 31 AM" src="https://user-images.githubusercontent.com/13629122/108599682-9479d880-7360-11eb-93f6-c9c7e5bb0135.png">

**Comment by cneidle** [comment]
there are still some problems with this

<img width="313" alt="Screen Shot 2021-03-06 at 11 33 03 AM" src="https://user-images.githubusercontent.com/13629122/110213842-c9f9e800-7e6f-11eb-9a17-4ef925c91d6c.png">

**Comment by cneidle** [comment]
This is still a problem...

**Comment by kwasiopoku** [comment]
This has been resolved on dev1.cs.  Changes will be migrated to dai.cs with the upcoming full data migration
