### ISSUE TITLE
A few more updates for ASLLVD data - Feb. 2021

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#285]
Could you please change the gloss from THREE-HOUR to THREE-HOURS?  (I will update the RIT data accordingly.). Thanks.

<img width="794" alt="Screen Shot 2021-02-20 at 9 25 25 AM" src="https://user-images.githubusercontent.com/13629122/108598794-ce95ab00-735d-11eb-85a1-4754fb9607ee.png">

**Comment by cneidle** [comment]
Could you please merge all occurrences under the main entry IX-honorific 
(and eliminate main entry IX-honorific:i)?

<img width="305" alt="Screen Shot 2021-02-21 at 9 34 36 PM" src="https://user-images.githubusercontent.com/13629122/108650076-b7091000-748c-11eb-8136-8311fbe8fbe5.png">

Thank you !

**Comment by cneidle** [comment]
Could you please make both of these changes.  For the change on top, merge that occurrence of THREE-HOURS with the others that are now in the sign bank.  thanks!

<img width="147" alt="Screen Shot 2021-03-06 at 11 28 43 AM" src="https://user-images.githubusercontent.com/13629122/110213721-31fbfe80-7e6f-11eb-8fcf-1a396272660c.png">

**Comment by kwasiopoku** [comment]
These changes have been made

**Comment by cneidle** [comment]
This is not fully fixed.  The occurrence also needs to be changed.  Thanks.

<img width="783" alt="Screen Shot 2021-03-06 at 7 04 53 PM" src="https://user-images.githubusercontent.com/13629122/110225032-4102a100-7eaf-11eb-9e6b-cacc799fba38.png">

**Comment by kwasiopoku** [comment]
FIXED
