### ISSUE TITLE
Problem playing sign clip from ASLLVD - in both public DAI and DEV1 servers

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#286]
The male sign for TWINS is showing up correctly in the composite video and in the original video, but not in the sign clip here:

<img width="786" alt="Screen Shot 2021-02-26 at 2 49 41 PM" src="https://user-images.githubusercontent.com/13629122/109348031-014e1080-7842-11eb-950a-559491be3d67.png">

**Comment by kwasiopoku** [comment]
This issue has been resolved
