### ISSUE TITLE
problem with "secrets" data display on dev1; it's working fine on the DAI

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#288]
on dev1

<img width="982" alt="Screen Shot 2021-03-06 at 11 35 27 AM" src="https://user-images.githubusercontent.com/13629122/110213947-4ee50180-7e70-11eb-90f7-41e205cc9da5.png">

on dai

<img width="977" alt="Screen Shot 2021-03-06 at 11 36 28 AM" src="https://user-images.githubusercontent.com/13629122/110213950-52788880-7e70-11eb-9fa5-edd3cc7715b5.png">

**Comment by kwasiopoku** [comment]
This is a non issue
