### ISSUE TITLE
One requested correction

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#289]
I found this:

<img width="132" alt="Screen Shot 2021-04-21 at 2 21 28 PM" src="https://user-images.githubusercontent.com/13629122/115602463-f5fceb80-a2ac-11eb-94e4-7c95cf7b0f7c.png">

The variant of GO is misclassified as a variant of SLIDE.

Can you move (1h)(5)GO to main entry GO?

DONE - thank you. - CN

**Comment by cneidle** [comment]
Also, I saw the gloss AFFORD occurs in one file of ours.  I will correct it and re-upload.
That should really be glossed as BILL/OWE.

So you can delete the entry for AFFORD from our list of English translations/synonyms/related words.

THANKS !!

**Comment by cneidle** [comment]
I need to ask for one more bit of help, with respect to this:

<img width="171" alt="Screen Shot 2021-04-21 at 7 21 34 PM" src="https://user-images.githubusercontent.com/13629122/115634092-e72b2e80-a2d6-11eb-9a67-db1510523793.png">

The last two items shown there, i.e., 

<img width="103" alt="Screen Shot 2021-04-21 at 7 22 56 PM" src="https://user-images.githubusercontent.com/13629122/115634155-032ed000-a2d7-11eb-9f81-4f3d4ed2d85e.png">

should be under the main entry IX-pl rather than under IX:i.  Can you help move them?

THANK YOU !

**Comment by kwasiopoku** [comment]
This has been resolved
