### ISSUE TITLE
results not all being displayed 

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#29]
I assume that the counts are right, but that the displays are incomplete...

![screen shot 2017-10-13 at 11 41 56 am](https://user-images.githubusercontent.com/13629122/31554505-cb84e002-b00b-11e7-81f6-b148c1e50c07.png)

![screen shot 2017-10-13 at 11 42 21 am](https://user-images.githubusercontent.com/13629122/31554512-d208d514-b00b-11e7-9966-2de49f03928f.png)

![screen shot 2017-10-13 at 11 42 35 am](https://user-images.githubusercontent.com/13629122/31554515-d61920e6-b00b-11e7-844b-ef4f8a9f01af.png)

**Comment by cneidle** [comment]
More problems with counts:   For HOMEWORK, I clicked on the 4 for the combined examples from Rachel, and 5 sentences were displayed. 

![screen shot 2017-10-13 at 11 46 56 am](https://user-images.githubusercontent.com/13629122/31554957-39e45d7e-b00d-11e7-9b04-af63bd290cd4.png)

![screen shot 2017-10-13 at 11 46 39 am](https://user-images.githubusercontent.com/13629122/31554964-407976ce-b00d-11e7-9b71-9ee12c7254f6.png)


I then clicked on the 4 just below that, for the subentry without the + by Rachel, and 1 sentence was displayed.

![screen shot 2017-10-13 at 11 47 46 am](https://user-images.githubusercontent.com/13629122/31554975-4963f07a-b00d-11e7-81b6-216155c7c6a7.png)

![screen shot 2017-10-13 at 11 47 07 am](https://user-images.githubusercontent.com/13629122/31554994-535c2af2-b00d-11e7-9b16-95b262011d1a.png)

**Comment by kwasiopoku** [comment]
Fixed.  Should be pushed to the dev & prod tonight

**Comment by cneidle** [comment]
Still not fixed - just FYI

**Comment by kwasiopoku** [comment]
I haven't pushed the changes to the prod and dev1 server yet.

**Comment by kwasiopoku** [comment]
Fixed and pushed to dai.cs.rutgers.edu
