### ISSUE TITLE
Duplicates in sign bank

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#292]
Sent email about this:

On both dev1 and dai, the sign bank has a duplication.

The first and last example below are exactly the same: ID 6948 and 6949.

I’ll let you know if I find others like this.  I just stumbled upon this one.
(I am preparing to teach a course on sign language linguistics this spring,
so will be actively using our data… )

<img width="802" alt="Screen Shot 2021-12-26 at 12 22 17 PM" src="https://user-images.githubusercontent.com/13629122/147415562-5fb09ca4-36a0-4f8a-b5ac-67c8925aa28b.png">

**Comment by kwasiopoku** [comment]
Remove #6948 and make #6949 the default occurrence.

**Comment by kwasiopoku** [comment]
This has been resolved on dev1.cs.  I confirmed that there are no more examples of duplicate signs

**Comment by kwasiopoku** [comment]
Verified with Carol and confirmed to be complete
