### ISSUE TITLE
a few new corrections

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#293]
<img width="147" alt="Screen Shot 2022-01-04 at 4 18 07 PM" src="https://user-images.githubusercontent.com/13629122/148125207-ab9184ac-6810-4fa1-b274-5e667eb79193.png">

GROUND+AREA_2 should be its own main entry.
_____
<img width="161" alt="Screen Shot 2022-01-04 at 4 32 33 PM" src="https://user-images.githubusercontent.com/13629122/148127223-674f2ccf-9807-4277-89c8-5b081c3cd6ab.png">

These should also be 2 distinct main entries.

**Comment by kwasiopoku** [comment]
This has been resolved on dev1.cs.  It will be migrated to dai.cs when we migrate the dev1.cs data to dai.cs

**Comment by cneidle** [comment]
No - there are lots of remaining cases. 

<img width="151" alt="Screen Shot 2022-01-20 at 10 58 50 AM" src="https://user-images.githubusercontent.com/13629122/150374974-a96f2a9a-e978-4f27-8e1d-91fea5d26eda.png">
<img width="193" alt="Screen Shot 2022-01-20 at 10 58 41 AM" src="https://user-images.githubusercontent.com/13629122/150374977-f97daf37-39e5-47bd-b84c-028f3dd12923.png">
<img width="209" alt="Screen Shot 2022-01-20 at 10 58 31 AM" src="https://user-images.githubusercontent.com/13629122/150374980-f7533e1c-45f4-4deb-9241-f9b03bde26a8.png">

<img width="226" alt="Screen Shot 2022-01-20 at 10 57 47 AM" src="https://user-images.githubusercontent.com/13629122/150375045-bd25c1eb-8ab6-4bc5-aa88-4906df90c9d7.png">
<img width="186" alt="Screen Shot 2022-01-20 at 10 57 07 AM" src="https://user-images.githubusercontent.com/13629122/150375048-0f067829-08fe-4c8d-b313-10788ccd1212.png">
<img width="216" alt="Screen Shot 2022-01-20 at 10 56 57 AM" src="https://user-images.githubusercontent.com/13629122/150375055-d687058f-dc63-497e-822f-1446d0b3f691.png">
<img width="174" alt="Screen Shot 2022-01-20 at 10 56 38 AM" src="https://user-images.githubusercontent.com/13629122/150375056-b721d693-40f5-4ca9-b49d-a87245124f7b.png">
<img width="244" alt="Screen Shot 2022-01-20 at 10 56 13 AM" src="https://user-images.githubusercontent.com/13629122/150375058-7e73e1be-3c7b-4b25-8872-b260aaf28555.png">
<img width="218" alt="Screen Shot 2022-01-20 at 10 55 51 AM" src="https://user-images.githubusercontent.com/13629122/150375059-fe5230e4-160d-44ad-a20d-ed55618bd023.png">

**Comment by kwasiopoku** [comment]
For compounds, we should not auto classify signs under a main entry unless the label matches that of the main entry

**Comment by kwasiopoku** [comment]
The below sign variants have been updated with a matching primary entry label in dev1.cs.

+---------------+-----------------------------+---------------------------+
| id_Occurrence | label                       | label                     |
+---------------+-----------------------------+---------------------------+
|         39023 | (1h)(L-X)INTERESTING+ZERO_2 | (1h)(L-X)INTERESTING+ZERO |
|         39139 | (S)OLD+FIVE_2               | (S)OLD+FIVE               |
|         39140 | (S)OLD+FOUR_2               | (S)OLD+FOUR               |
|         39142 | (S)OLD+ONE_2                | (S)OLD+ONE                |
|         39144 | (S)OLD+THREE_2              | (S)OLD+THREE              |
|         39145 | (S)OLD+TWO_2                | (S)OLD+TWO                |
|         39848 | DRY+AREA_2                  | DRY+AREA                  |
|         40118 | GIRL+BABY_2                 | GIRL+BABY                 |
|         40119 | GIRL+BABY_2                 | GIRL+BABY                 |
|         40294 | KING+AREA_2                 | KING+AREA                 |
|         40295 | KING+AREA_2                 | KING+AREA                 |
|         40628 | OLD+TESTAMENT_2             | OLD+TESTAMENT             |
|         41180 | WATER+FLOW_2                | WATER+FLOW                |
|         41181 | WATER+FLOW_2                | WATER+FLOW                |
|         41182 | WATER+FLOW_2                | WATER+FLOW                |
|         41183 | WATER+FLOW_2                | WATER+FLOW                |
|         41184 | WATER+FLOW_2                | WATER+FLOW                |
|         41185 | WATER+FLOW_2                | WATER+FLOW                |
|         41189 | WATER+RIVER_2               | WATER+RIVER               |
|         41230 | WITH+NEG_2                  | WITH+NEG                  |
|         41231 | WITH+NEG_2                  | WITH+NEG                  |
|        172027 | NONE/NOTHING_2+ONE          | NONE/NOTHING+ONE          |
|        172041 | NONE/NOTHING_2+ONE          | NONE/NOTHING+ONE          |
|        174974 | CLASS_2+BOX/ROOM            | CLASS+BOX/ROOM            |
|        175154 | CLASS_2+BOX/ROOM            | CLASS+BOX/ROOM            |
|        175350 | CLASS_2+BOX/ROOM            | CLASS+BOX/ROOM            |
|        175645 | CLASS_2+BOX/ROOM            | CLASS+BOX/ROOM            |
|        176022 | CLASS_2+BOX/ROOM            | CLASS+BOX/ROOM            |
|        176271 | CLASS_2+BOX/ROOM            | CLASS+BOX/ROOM            |
|        178032 | CLASS_2+BOX/ROOM            | CLASS+BOX/ROOM            |
|        178270 | CLASS_2+BOX/ROOM            | CLASS+BOX/ROOM            |
|        178528 | CLASS_2+BOX/ROOM            | CLASS+BOX/ROOM            |
|        178928 | CLASS_2+BOX/ROOM            | CLASS+BOX/ROOM            |
|        179339 | CLASS_2+BOX/ROOM            | CLASS+BOX/ROOM            |
|        179348 | CLASS_2+BOX/ROOM            | CLASS+BOX/ROOM            |
|        179865 | PAST_2+NIGHT                | PAST+ALL-NIGHT            |
|        185930 | WITH+NEG_2                  | WITH+NEG                  |
|        186039 | CLASS_2+BOX/ROOM            | CLASS+BOX/ROOM            |
|        187031 | CLASS_2+BOX/ROOM            | CLASS+BOX/ROOM            |
|        189041 | GIRL+BABY_2                 | GIRL+BABY                 |
|        190610 | KING+AREA_2                 | KING+AREA                 |
|        190674 | (1h)(L-X)INTERESTING+ZERO_2 | (1h)(L-X)INTERESTING+ZERO |
|        191188 | CELEBRATE(2h)IX-honorific:j | IX-honorific              |
|        191415 | WATER+FLOW_2                | WATER+FLOW                |
|        192010 | DRY+AREA_2                  | DRY+AREA                  |
|        192343 | (S)OLD+TWO_2                | (S)OLD+TWO                |
|        192346 | (S)OLD+THREE_2              | (S)OLD+THREE              |
|        192349 | (S)OLD+FOUR_2               | (S)OLD+FOUR               |
|        192352 | (S)OLD+FIVE_2               | (S)OLD+FIVE               |
|        192438 | WITH+NEG_2                  | WITH+NEG                  |
|        193122 | WATER+FLOW_2                | WATER+FLOW                |
|        193403 | PAST_2+NIGHT                | PAST+ALL-NIGHT            |
|        193921 | (1h)(L-X)INTERESTING+ZERO_2 | (1h)(L-X)INTERESTING+ZERO |
|        194754 | GIRL+BABY_2                 | GIRL+BABY                 |
|        195346 | CLASS_2+BOX/ROOM            | CLASS+BOX/ROOM            |
|        195443 | GIRL+BABY_2                 | GIRL+BABY                 |
|        195512 | WATER+FLOW_2                | WATER+FLOW                |
|        197486 | (S)OLD+ONE_2                | (S)OLD+ONE                |
|        197489 | (S)OLD+TWO_2                | (S)OLD+TWO                |
|        197494 | (S)OLD+FOUR_2               | (S)OLD+FOUR               |
|        197497 | (S)OLD+FIVE_2               | (S)OLD+FIVE               |
|        197604 | WITH+NEG_2                  | WITH+NEG                  |
|        198356 | WATER+FLOW_2                | WATER+FLOW                |
|        199048 | (S)OLD+FOUR_2               | (S)OLD+FOUR               |
|        199282 | GIRL+BABY_2                 | GIRL+BABY                 |
|        200012 | GIRL+BABY_2                 | GIRL+BABY                 |
|        200403 | (1h)(L-X)INTERESTING+ZERO_2 | (1h)(L-X)INTERESTING+ZERO |
|        202446 | (S)OLD+ONE_2                | (S)OLD+ONE                |
|        203430 | (1h)(L-X)INTERESTING+ZERO_2 | (1h)(L-X)INTERESTING+ZERO |
|        203917 | WATER+FLOW_2                | WATER+FLOW                |
|        205001 | GIRL+BABY_2                 | GIRL+BABY                 |
+---------------+-----------------------------+---------------------------+

**Comment by cneidle** [comment]
thank you!
