### ISSUE TITLE
error with utterance search - on both DAI and dev1

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#294]
When searching for utterances in 8-Ben file

<img width="562" alt="Screen Shot 2022-01-04 at 4 40 14 PM" src="https://user-images.githubusercontent.com/13629122/148127496-2dc1803e-4615-41ac-b8cb-b8cef7f199e6.png">

<img width="739" alt="Screen Shot 2022-01-04 at 4 40 05 PM" src="https://user-images.githubusercontent.com/13629122/148127513-6c2d60e4-40f1-4d78-80d8-937a10e9f6af.png">

**Comment by cneidle** [comment]
I suspect this should not be showing up as it is, as BUOY is normally on the non-dominant hand, but I can't check because of the problem above... 

<img width="985" alt="Screen Shot 2022-01-04 at 4 41 47 PM" src="https://user-images.githubusercontent.com/13629122/148127631-f108eee8-d0ad-43e2-b96e-a3de6e2dc3bc.png">

**Comment by kwasiopoku** [comment]
I am unable to reproduce the search issue with 8-Ben.  We should discuss further on our next call.
