### ISSUE TITLE
merging indices - not working properly

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#295]
<img width="123" alt="Screen Shot 2022-01-20 at 9 58 29 AM" src="https://user-images.githubusercontent.com/13629122/150363786-16be898b-4a7c-405a-a019-40e46779092e.png">

All occurrences of :i , :j , :x , etc.  should be merged

**Comment by cneidle** [comment]
another example

<img width="116" alt="Screen Shot 2022-01-20 at 10 01 31 AM" src="https://user-images.githubusercontent.com/13629122/150364120-c4c61834-f3c8-4d95-82b7-ad5ab75af227.png">

<img width="98" alt="Screen Shot 2022-01-20 at 10 01 24 AM" src="https://user-images.githubusercontent.com/13629122/150364153-79536d5b-9949-4224-bea4-3da110e93ff5.png">

**Comment by kwasiopoku** [comment]
This change has been pushed to dev1.cs.  Parser has also been updated

**Comment by cneidle** [comment]
fixed - thank you
