### ISSUE TITLE
Problem with the entry for fs-UP

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#296]
<img width="261" alt="Screen Shot 2022-01-20 at 10 58 13 AM" src="https://user-images.githubusercontent.com/13629122/150375156-55839a8b-a7be-4a1f-8db9-27ec3384b8ba.png">

First - fs-UP is showing up in the list of compounds (selected from the dropdown menu at the top).

The things listed under fs-UP do not belong there either.  Those are compounds that should be listed independently.  There should also be a listing for the compound parts, under both fs-UP and the other part.

There does seem to be a correct (distinct) listijng for fs-UP with those things listed underneath:

fs-UP
*(2h)fs-UP (BREAK+(2h)fs-UP) 
*(2h)fs-UP (GIVE-UP+(2h)fs-UP) 

This is correctly listed:

<img width="278" alt="Screen Shot 2022-01-20 at 11 06 16 AM" src="https://user-images.githubusercontent.com/13629122/150376285-6d52730b-5aaa-4f80-b5b3-27bfcb05bb4c.png">

BREAK
BREAK* (BREAK+(2h)fs-UP) 

GIVE-UP
GIVE-UP* (GIVE-UP+(2h)fs-UP) 

These are also listed correctly.

**Comment by kwasiopoku** [comment]
This has been resolved on dev1.cs

**Comment by cneidle** [comment]
fixed - thank you
