### ISSUE TITLE
One ASLLVD sign type correction needed.

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#297]
RIVER_2 is not a classifier.  It should be classified as a lexical sign.
Can you fix?

Thanks !!

<img width="1176" alt="Screen Shot 2022-01-20 at 1 53 54 PM" src="https://user-images.githubusercontent.com/13629122/150403831-3d5319b6-1f47-422c-a7bf-6c9219b6d2c1.png">

RIVER_2 should be an entry/variant under RIVER

<img width="289" alt="Screen Shot 2022-01-20 at 1 56 22 PM" src="https://user-images.githubusercontent.com/13629122/150403976-f762781c-5246-42d6-bcf6-783bcdcf382c.png">

**Comment by kwasiopoku** [comment]
This change has been pushed to dev1.cs

**Comment by cneidle** [comment]
This one has been corrected, but there is now one other sign type error:

BEAT is showing up among classifiers; it is lexical.

<img width="267" alt="Screen Shot 2022-03-14 at 5 06 35 PM" src="https://user-images.githubusercontent.com/13629122/158261443-34e59ece-cd55-4c25-a4f7-d59dce5eae59.png">

**Comment by cneidle** [comment]
fixed - thank you
