### ISSUE TITLE
Sign Bank:  text search not working properly

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#30]
"HAVE" is not found (!)

![screen shot 2017-10-13 at 2 54 49 pm](https://user-images.githubusercontent.com/13629122/31561665-9c3eecdc-b026-11e7-8d70-a4409a097f8d.png)

just one example - this seems quite generally broken.

**Comment by kwasiopoku** [comment]
I accidentally broke this while trying to fix the "Enter to Submit" feature on the search form.  I will revert the change

**Comment by kwasiopoku** [comment]
Fixed
