### ISSUE TITLE
request for a couple of changes

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#300]
So sorry for the inconvenience!

But 

(1) could you please move MEDIUM to make it an entry/variant under main entry AVERAGE?

<img width="900" alt="Screen Shot 2022-02-04 at 6 46 23 PM" src="https://user-images.githubusercontent.com/13629122/152618072-55e35c5d-63b5-4a46-af86-780beaef09da.png">

(2) Could you please move these two examples currently under AVERAGE so that they are glossed as MEDIUM
(and moved in with the example above)?

<img width="828" alt="Screen Shot 2022-02-04 at 6 48 19 PM" src="https://user-images.githubusercontent.com/13629122/152618126-9e5b14d2-d3d7-4ddf-acd6-8642aa203727.png">

(3) There are still some thumbnails and videos missing:

<img width="885" alt="Screen Shot 2022-02-04 at 6 49 08 PM" src="https://user-images.githubusercontent.com/13629122/152618141-59734e83-34cf-4930-87a3-7e91b3c14234.png">

(4) Also, I don't know why, but the original videos are not playing for the AVERAGE examples... 
I don't know how much more general this problem is...

THANKS !!

**Comment by kwasiopoku** [comment]
These have been updated.  

With regards to (4), there were two collections that failed video processing because the video files were not available at the time of parsing.  I have restarted the video parsing for PF04_V03_RIT.xml and PF18_V04_RIT.xml

**Comment by cneidle** [comment]
fixed - thank you
