### ISSUE TITLE
DAI display probblem

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#301]
<img width="882" alt="Screen Shot 2022-02-05 at 4 07 04 AM" src="https://user-images.githubusercontent.com/13629122/152635639-1112f8ed-0dbf-4aab-8a6b-0c9800332a45.png">

**Comment by kwasiopoku** [comment]
This will be resolved when we regenerate the thumbnails for the ASLLVD data using the start and end frames

**Comment by cneidle** [comment]
I understand this problem goes back to the ASLLVD data.  I will just change the canonical example where possible when this appears  there.
