### ISSUE TITLE
Missing items - DAI

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#302]
The windows for occurrences, play sign video, translation, and composite video come up blank.

<img width="1174" alt="Screen Shot 2022-02-05 at 9 32 13 AM" src="https://user-images.githubusercontent.com/13629122/152646041-624a7375-fe9a-4622-893a-a48a2b594785.png">

**Comment by cneidle** [comment]
Seems to b happening for the whole site.

I just got notification from the Monitor that the site is down...

**Comment by kwasiopoku** [comment]
I confirmed with Carol is that this is a non issue.
