### ISSUE TITLE
one more request for a change 

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#303]
Hi Augustine 

Could you please make SLICE_2 a variant under SLICE
(rather than a variant under CHOP) ?

THANKS. !!

<img width="101" alt="Screen Shot 2022-02-07 at 7 29 20 AM" src="https://user-images.githubusercontent.com/13629122/152788491-b3e2d0c1-6f92-4e06-a58a-4ff85854cace.png">

<img width="167" alt="Screen Shot 2022-02-07 at 7 29 06 AM" src="https://user-images.githubusercontent.com/13629122/152788494-9c53601e-e11e-4d10-8a30-1719da0deafb.png">

**Comment by kwasiopoku** [comment]
This has been fixed on dev1.cs

**Comment by cneidle** [comment]
fixed -thank you
