### ISSUE TITLE
Still some missing thumbnails and videos - ASLLVD

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#304]
<img width="1180" alt="Screen Shot 2022-02-07 at 12 31 12 PM" src="https://user-images.githubusercontent.com/13629122/152841007-a66ca4c3-c2bb-4012-b654-08b35bbfc849.png">

**Comment by cneidle** [comment]
<img width="1148" alt="Screen Shot 2022-02-09 at 3 13 00 PM" src="https://user-images.githubusercontent.com/13629122/153282567-ef6906a2-33d9-40e5-8bed-2f5962664b7f.png">

**Comment by kwasiopoku** [comment]
Thumbnails and videos are  available for these signs.

**Comment by cneidle** [comment]
fixed - thank you
