### ISSUE TITLE
One more requested change

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#306]
Could you please move FLAG_2 so that it is a variant under FLAG ?

THANK YOU !!!

<img width="1057" alt="Screen Shot 2022-02-09 at 11 30 41 AM" src="https://user-images.githubusercontent.com/13629122/153245455-ad07453c-7a94-4345-b4ff-ea0297333b8c.png">

**Comment by kwasiopoku** [comment]
This has been updated on dev1.cs

**Comment by cneidle** [comment]
fixed - thank you
