### ISSUE TITLE
seeking help in hiding one sign

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#307]
There is a sign that should be hidden, but because i's the only occurrence, I am unable to.  Can you help?  

Thanks !!
<img width="999" alt="Screen Shot 2022-02-09 at 9 50 17 PM" src="https://user-images.githubusercontent.com/13629122/153328110-b2dc9fc2-066b-45ab-adcc-0517d6fd5378.png">

**Comment by kwasiopoku** [comment]
This has been updated on dev1.cs

**Comment by cneidle** [comment]
This still needs to be fixed.  I thought it had been, but this sign is showing up again.
<img width="1149" alt="Screen Shot 2022-03-14 at 4 54 34 PM" src="https://user-images.githubusercontent.com/13629122/158259645-6dd0d312-8e8b-4cff-a23c-6d28f811a64a.png">

**Comment by cneidle** [comment]
fixed - thank you - but we need to make sure that this doesn't come if the file should be re-uploaded.

**Comment by cneidle** [comment]
This has come back on dev1

<img width="259" alt="Screen Shot 2022-03-27 at 7 29 49 PM" src="https://user-images.githubusercontent.com/13629122/160305874-95be2c7a-31a7-4038-95c9-49c3812f525f.png">

**Comment by cneidle** [comment]
Should we permanently delete entries that have no examples, at a time when all existing files have already been uploaded ??

**Comment by cneidle** [comment]
This is back again on both dev1 and the DAI    :-(

<img width="223" alt="Screen Shot 2022-04-02 at 3 54 40 PM" src="https://user-images.githubusercontent.com/13629122/161399152-4fece465-6c93-4b2c-841f-645b0b460559.png">

**Comment by kwasiopoku** [comment]
This sign has been hidden.
