### ISSUE TITLE
Another small request: changing main entry 

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#308]
Hi Augustine,

Currently we have:

<img width="192" alt="Screen Shot 2022-02-10 at 10 53 19 AM" src="https://user-images.githubusercontent.com/13629122/153445115-db25dcc1-400a-4640-96a9-e92fbfaef597.png">

Could you please change this so that the main entry is listed as "IMPROVE"
rather than "IMPROVE-A-LOT" (with the same two variants associated
with the new main entry) ??

THANK YOU VERY MUCH !!!

**Comment by kwasiopoku** [comment]
This has been updated on dev1.cs

**Comment by cneidle** [comment]
fixed - thank you
