### ISSUE TITLE
One more small request for reorganization

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#309]
Hi Augustine, 

Could you please make PIZZA_2 a variant under PIZZA ?

So instead of 
<img width="107" alt="Screen Shot 2022-02-13 at 6 16 06 PM" src="https://user-images.githubusercontent.com/13629122/153779655-9db301d7-08c9-48d6-8cc7-aaeb46b8cf0f.png">

we would have:

PIZZA
>  PIZZA
>  PIZZA_2

#PIZZA

Thank you very much !!

**Comment by kwasiopoku** [comment]
This has been updated on dev1.cs

**Comment by cneidle** [comment]
fixed - thank you
