### ISSUE TITLE
When the primary variant is selected in the Sign Bank, the Show Occurrences doesn't work properly

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#31]
The occurrences are not being shown for the  sign variant that is (correctly) displayed: 

<img width="888" alt="screen shot 2017-10-14 at 11 48 55 am" src="https://user-images.githubusercontent.com/13629122/31577057-d7a34f3e-b0d5-11e7-9280-377bf19ac4ca.png">

<img width="694" alt="screen shot 2017-10-14 at 11 49 04 am" src="https://user-images.githubusercontent.com/13629122/31577058-d96ed4dc-b0d5-11e7-9ddb-3f7f0bd93e51.png">

**Comment by kwasiopoku** [comment]
Fixed
