### ISSUE TITLE
Yet another small request

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#310]
Hi Augustine,

Could you please change 

<img width="211" alt="Screen Shot 2022-02-15 at 9 48 07 AM" src="https://user-images.githubusercontent.com/13629122/154086069-9eb0a485-ae21-4b8a-9ae1-87204621f691.png">

so that the main entry is SINGLE?

**SINGLE**
>     SINGLE
>     BACHELOR
>     SWINGING-SINGLE

Thank you so much !!

**Comment by kwasiopoku** [comment]
This has been updated on dev1.cs

**Comment by cneidle** [comment]
fixed - thank you
