### ISSUE TITLE
one more request for reorganization - thank you!

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#311]
Hi Augustine,

We currently have one example of ABDOMEN.

Could you please make that a variant under main entry STOMACH ?

Thank you !

<img width="1237" alt="Screen Shot 2022-02-16 at 11 36 14 AM" src="https://user-images.githubusercontent.com/13629122/154312645-262b26ab-7c76-48f7-9d90-be5f99d34a78.png">

<img width="161" alt="Screen Shot 2022-02-16 at 11 38 23 AM" src="https://user-images.githubusercontent.com/13629122/154312800-3e862bfe-b635-49ee-9697-e2033b74550a.png">

So we will have 

STOMACH
> STOMACH
> ABDOMEN

Thank you !!!

**Comment by kwasiopoku** [comment]
This has been resolved on dev1.cs

**Comment by cneidle** [comment]
fixed - thank you
