### ISSUE TITLE
one sign out of place

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#315]
The compound part should not be included here.

<img width="229" alt="Screen Shot 2022-03-17 at 6 30 01 PM" src="https://user-images.githubusercontent.com/13629122/158904919-0872bb05-3292-416b-a017-350ccc2b8d46.png">

<img width="295" alt="Screen Shot 2022-03-17 at 6 30 13 PM" src="https://user-images.githubusercontent.com/13629122/158904922-ec312dc6-85bd-4244-86c8-64c20a08098f.png">

**Comment by kwasiopoku** [comment]
This has been corrected on dev1.cs
