### ISSUE TITLE
+ has been incorrectly removed from compounds containing part:indef

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#317]
examples:

<img width="290" alt="Screen Shot 2022-03-26 at 9 22 15 AM" src="https://user-images.githubusercontent.com/13629122/160241507-3694ede5-9bde-42e9-8f34-5583cb5fa770.png">

<img width="317" alt="Screen Shot 2022-03-26 at 9 22 52 AM" src="https://user-images.githubusercontent.com/13629122/160241505-71b292e8-d2cb-4ab7-b80b-5514b30e4326.png">

**Comment by cneidle** [comment]
I wanted to check the spreadsheet that you gave to. Konstantinos to see if the plusses were also missing there.  But it looks like these compounds are completely missing in that file, so far as I can tell...

**Comment by kwasiopoku** [comment]
This has been updated on the dev1.cs site.

**Comment by cneidle** [comment]
Thank you !!
