### ISSUE TITLE
INDEX SIGNS not being classified properly

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#318]
This still needs to be fixed:

<img width="82" alt="Screen Shot 2022-03-26 at 3 19 17 PM" src="https://user-images.githubusercontent.com/13629122/160254075-378a0214-0c84-4e7b-9518-3bc970f04ce9.png">

These need to be classified with    :j

THANK YOU

**Comment by kwasiopoku** [comment]
These have been corrected on dev1.cs
