### ISSUE TITLE
TWO plus signs should not be there

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#319]
The last two entries here should not have a + at the beginning.

Thanks

<img width="291" alt="Screen Shot 2022-03-26 at 3 27 01 PM" src="https://user-images.githubusercontent.com/13629122/160254295-b16a76a3-4b0d-4784-8be1-a505f9e0c19a.png">

**Comment by kwasiopoku** [comment]
This has been updated on dev1.cs

**Comment by kwasiopoku** [comment]
I verified that no more occurrences of this issue exist
