### ISSUE TITLE
Sign Bank - problem with 'Play composite video'

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#32]
This works ok when launched from the display of occurrences, but when launched from the main
search result, it brings up one blank window plus the composite video for 'A-LOT' regardless of which sign had been selected.

![screen shot 2017-10-17 at 2 22 42 pm](https://user-images.githubusercontent.com/13629122/31682032-dd256726-b346-11e7-9a64-0418aead57a8.png)

![screen shot 2017-10-17 at 2 22 01 pm](https://user-images.githubusercontent.com/13629122/31682037-e100f784-b346-11e7-9e46-dcb2fa363e63.png)

**Comment by kwasiopoku** [comment]
Fixed in production
