### ISSUE TITLE
Handshape palette - 1 handhape is missing:  bent-V

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#33]
![bent-v](https://user-images.githubusercontent.com/13629122/31788530-fe140342-b4dc-11e7-9dbf-ea64bab4fa3a.jpg)

![big-bent-v](https://user-images.githubusercontent.com/13629122/31788535-00dbc7f4-b4dd-11e7-877d-f61d062ae9fa.jpg)

![screen shot 2017-10-19 at 2 50 09 pm](https://user-images.githubusercontent.com/13629122/31788545-097164dc-b4dd-11e7-8a58-e2df79565a34.png)

I'll email you the handshape images, in case that is helpful.  Thanks!

**Comment by kwasiopoku** [comment]
Fixed
