### ISSUE TITLE
One correction needed to Sign Bank data: BORN vs. BIRTH

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#336]
We currently have two different main entries:  BORN and BIRTH.

BIRTH should be made into a variant, under BORN.

So we now have:

BIRTH
- BIRTH (4)

BORN
- BORN (27)
- (S)BORN (6)

What we want to have is:

BORN
- BORN (27)
- (S)BORN (6)
- BIRTH (4)

Can you help by moving BIRTH to make it a variant of BORN?

Thanks so much!

**Comment by kwasiopoku** [comment]
This has been resolved on dev1
