### ISSUE TITLE
Related English words for gestures

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#337]
Clicking on related English words for gestures results in...

> HTTP Status 500 – Internal Server Error
> 
> Type Exception Report
> 
> Message An exception occurred processing [WEB-INF/jsp/translation.jsp] at line [40]
> 
> Description The server encountered an unexpected condition that prevented it from fulfilling the request.
> 
> Exception
> 
> org.apache.jasper.JasperException: An exception occurred processing [WEB-INF/jsp/translation.jsp] at line [40]
> 
> 37: 	
> 38: 	
> 39: 	edu.rutgers.cs.lcsr.apps.lobbydisplay.data.SignBankOccurrence translationObj = 
> 40: 	search.getSignBankOccurrenceTranstion(id_SignBankVariant);
> 41: 	
> 42: 	
> 43: 	
> 
> 
> Stacktrace:
> 	org.apache.jasper.servlet.JspServletWrapper.handleJspException(JspServletWrapper.java:593)
> 	org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:482)
> 	org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:385)
> 	org.apache.jasper.servlet.JspServlet.service(JspServlet.java:329)
> 	javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
> 	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
> 	edu.rutgers.cs.lcsr.apps.lobbydisplay.controller.UIDispatcher.requestDispatch(UIDispatcher.java:19)
> 	edu.rutgers.cs.lcsr.apps.lobbydisplay.servlets.translationServlet.doGetOrPost(translationServlet.java:28)
> 	edu.rutgers.cs.lcsr.apps.lobbydisplay.servlets.translationServlet.doGet(translationServlet.java:15)
> 	javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
> 	javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
> 	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
> Root Cause
> 
> java.lang.StringIndexOutOfBoundsException: begin 0, end -2, length 0
> 	java.base/java.lang.String.checkBoundsBeginEnd(String.java:3734)
> 	java.base/java.lang.String.substring(String.java:1903)
> 	edu.rutgers.cs.lcsr.apps.lobbydisplay.search.search.getSignBankOccurrenceTranstion(search.java:7290)
> 	org.apache.jsp.WEB_002dINF.jsp.translation_jsp._jspService(translation_jsp.java:183)
> 	org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
> 	javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
> 	org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:444)
> 	org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:385)
> 	org.apache.jasper.servlet.JspServlet.service(JspServlet.java:329)
> 	javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
> 	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
> 	edu.rutgers.cs.lcsr.apps.lobbydisplay.controller.UIDispatcher.requestDispatch(UIDispatcher.java:19)
> 	edu.rutgers.cs.lcsr.apps.lobbydisplay.servlets.translationServlet.doGetOrPost(translationServlet.java:28)
> 	edu.rutgers.cs.lcsr.apps.lobbydisplay.servlets.translationServlet.doGet(translationServlet.java:15)
> 	javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
> 	javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
> 	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
> Note The full stack trace of the root cause is available in the server logs.
> 
> Apache Tomcat/9.0.1

**Comment by cneidle** [comment]
Seems more general than just gestures.
Seems to happen whenever there are no English words defined.

**Comment by kwasiopoku** [comment]
This has been resolved

**Comment by cneidle** [comment]
Thanks !!
