### ISSUE TITLE
Quick correction:  Title of 'View Occurrences' Window

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#34]
Should be "ASLLRP Sign Bank" not "SignSream Sign Bank"  

thanks!

![screen shot 2017-10-19 at 4 24 44 pm](https://user-images.githubusercontent.com/13629122/31792479-37891100-b4ea-11e7-8c03-412ea98dd5cb.png)

**Comment by cneidle** [comment]
Note also a previously reported bug -- that the wrong set of occurrences is still showing up here...

**Comment by kwasiopoku** [comment]
Fixed
