### ISSUE TITLE
utterance search error

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#341]

**Comment by cneidle** [comment]
limiting utterance search to DSP sentences

<img width="738" alt="Screen Shot 2022-08-17 at 9 43 56 AM" src="https://user-images.githubusercontent.com/13629122/185149824-7a4d50ed-fd14-4933-b36a-662f34696dcc.png">


HTTP Status 500 – Internal Server Error

Type Exception Report

Message An exception occurred processing [WEB-INF/jsp/utterancesearchresult.jsp] at line [207]

Description The server encountered an unexpected condition that prevented it from fulfilling the request.

Exception

org.apache.jasper.JasperException: An exception occurred processing [WEB-INF/jsp/utterancesearchresult.jsp] at line [207]

204: 
205:         }
206:         
207:         ArrayList<edu.rutgers.cs.lcsr.apps.lobbydisplay.data.ViewUtterances> utterances = search.getUtteranceDetail( utterances_no_details, start, end );
208:         
209:         String video_download = "";
210:        if(dbProperties.STR_environment.equals("prod")){


Stacktrace:
	org.apache.jasper.servlet.JspServletWrapper.handleJspException(JspServletWrapper.java:593)
	org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:482)
	org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:385)
	org.apache.jasper.servlet.JspServlet.service(JspServlet.java:329)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	edu.rutgers.cs.lcsr.apps.lobbydisplay.controller.UIDispatcher.requestDispatch(UIDispatcher.java:19)
	edu.rutgers.cs.lcsr.apps.lobbydisplay.servlets.utteranceSearchResultServlet.doGetOrPost(utteranceSearchResultServlet.java:28)
	edu.rutgers.cs.lcsr.apps.lobbydisplay.servlets.utteranceSearchResultServlet.doGet(utteranceSearchResultServlet.java:15)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
Root Cause

java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 0
	java.base/java.lang.String.checkBoundsBeginEnd(String.java:3734)
	java.base/java.lang.String.substring(String.java:1903)
	edu.rutgers.cs.lcsr.apps.lobbydisplay.search.search.getUtteranceDetail(search.java:2945)
	org.apache.jsp.WEB_002dINF.jsp.utterancesearchresult_jsp._jspService(utterancesearchresult_jsp.java:342)
	org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:444)
	org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:385)
	org.apache.jasper.servlet.JspServlet.service(JspServlet.java:329)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	edu.rutgers.cs.lcsr.apps.lobbydisplay.controller.UIDispatcher.requestDispatch(UIDispatcher.java:19)
	edu.rutgers.cs.lcsr.apps.lobbydisplay.servlets.utteranceSearchResultServlet.doGetOrPost(utteranceSearchResultServlet.java:28)
	edu.rutgers.cs.lcsr.apps.lobbydisplay.servlets.utteranceSearchResultServlet.doGet(utteranceSearchResultServlet.java:15)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
Note The full stack trace of the root cause is available in the server logs.

Apache Tomcat/9.0.1

**Comment by cneidle** [comment]
Same thing seems to happen when attempting to limit the utterance search based on any collections.

I think the problem is that I may have deselected all participants.

In which case, it should return no results - rather than the error message that comes up.

**Comment by cneidle** [comment]
This is still occurring.  To reproduce:  Go to DAI utterance search.  Select only +DSP sentences; de-select participants and ASLLRP sentences.

HTTP Status 500 – Internal Server Error

Type Exception Report

Message An exception occurred processing [WEB-INF/jsp/utterancesearchresult.jsp] at line [207]

Description The server encountered an unexpected condition that prevented it from fulfilling the request.

Exception

org.apache.jasper.JasperException: An exception occurred processing [WEB-INF/jsp/utterancesearchresult.jsp] at line [207]

204: 
205:         }
206:         
207:         ArrayList<edu.rutgers.cs.lcsr.apps.lobbydisplay.data.ViewUtterances> utterances = search.getUtteranceDetail( utterances_no_details, start, end );
208:         
209:         String video_download = "";
210:        if(dbProperties.STR_environment.equals("prod")){


Stacktrace:
	org.apache.jasper.servlet.JspServletWrapper.handleJspException(JspServletWrapper.java:593)
	org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:482)
	org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:385)
	org.apache.jasper.servlet.JspServlet.service(JspServlet.java:329)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	edu.rutgers.cs.lcsr.apps.lobbydisplay.controller.UIDispatcher.requestDispatch(UIDispatcher.java:19)
	edu.rutgers.cs.lcsr.apps.lobbydisplay.servlets.utteranceSearchResultServlet.doGetOrPost(utteranceSearchResultServlet.java:28)
	edu.rutgers.cs.lcsr.apps.lobbydisplay.servlets.utteranceSearchResultServlet.doGet(utteranceSearchResultServlet.java:15)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
Root Cause

java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 0
	java.base/java.lang.String.checkBoundsBeginEnd(String.java:3734)
	java.base/java.lang.String.substring(String.java:1903)
	edu.rutgers.cs.lcsr.apps.lobbydisplay.search.search.getUtteranceDetail(search.java:2945)
	org.apache.jsp.WEB_002dINF.jsp.utterancesearchresult_jsp._jspService(utterancesearchresult_jsp.java:342)
	org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:444)
	org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:385)
	org.apache.jasper.servlet.JspServlet.service(JspServlet.java:329)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	edu.rutgers.cs.lcsr.apps.lobbydisplay.controller.UIDispatcher.requestDispatch(UIDispatcher.java:19)
	edu.rutgers.cs.lcsr.apps.lobbydisplay.servlets.utteranceSearchResultServlet.doGetOrPost(utteranceSearchResultServlet.java:28)
	edu.rutgers.cs.lcsr.apps.lobbydisplay.servlets.utteranceSearchResultServlet.doGet(utteranceSearchResultServlet.java:15)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
Note The full stack trace of the root cause is available in the server logs.

Apache Tomcat/9.0.1

**Comment by kwasiopoku** [comment]
This has been fixed and pushed to dev1 and dai servers

**Comment by cneidle** [comment]
thank you !!
