### ISSUE TITLE
RIT data in sign bank should NOT include 'play utterance' option 

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#342]
Although these were coded as utterances in SignStream, they are only individual signs, so this should not be appearing with an option to play utterance.

<img width="1261" alt="Screen Shot 2022-08-17 at 9 54 32 AM" src="https://user-images.githubusercontent.com/13629122/185152485-67470c05-2b2e-4650-ae2f-5218378ad596.png">

**Comment by cneidle** [comment]
Same issue with DSP data for isolated signs (although for SOME DSP data, there are available utterances).

<img width="560" alt="Screen Shot 2022-08-17 at 11 28 44 AM" src="https://user-images.githubusercontent.com/13629122/185180291-d230f0b9-05ec-4fa5-8f9e-765b4ca4b2d1.png">

**Comment by kwasiopoku** [comment]
This has been fixed and pushed to dev1 and dai servers

**Comment by cneidle** [comment]
thank you !!
