### ISSUE TITLE
These two index entries should be merged

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#344]
<img width="175" alt="Screen Shot 2022-08-17 at 10 56 55 AM" src="https://user-images.githubusercontent.com/13629122/185172831-7402f9f6-418b-4900-9912-a3fdc91c3562.png">

**Comment by kwasiopoku** [comment]
This issue has been resolved and the fix is now on dev1 and dai

**Comment by cneidle** [comment]
looks good.  thank you.
