### ISSUE TITLE
overall problems with words file

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#345]
[cn-gloss_variant_translations_CAREY-Aug-22.xlsx](https://github.com/DCS-LCSR/ASL-DAI/files/9366835/cn-gloss_variant_translations_CAREY-Aug-22.xlsx)

**Comment by kwasiopoku** [comment]
This ticket has been superseded by a recent version of the translation file.  See cn-gloss_variant_translations_CAREY-Aug-29
