### ISSUE TITLE
Download button does not work from Download cart for DAI

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#348]
Nothing happens...

<img width="1005" alt="Screen Shot 2022-08-31 at 12 44 35 PM" src="https://user-images.githubusercontent.com/13629122/187733763-3337a783-5a3a-4630-82e6-5f30f00bebad.png">

**Comment by cneidle** [comment]
after this is fixed, check #235

**Comment by kwasiopoku** [comment]
This is been resolved and pushed to dai server
