### ISSUE TITLE
Sign Bank: Handshapes for finger spelled signs and compounds

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#35]
When we talk next, could we discuss what should be shown with respect to handshapes for signs that are part of compounds?

It seems to me that the start and end handshapes should show up for the compound part that is being displayed, not for the whole compound...

Also, fingerspelled signs show up without any handshapes at all...

<img width="637" alt="screen shot 2017-10-20 at 2 33 57 pm" src="https://user-images.githubusercontent.com/13629122/31837140-ac0f6dc4-b5a5-11e7-8df8-0817ec6bc838.png">

<img width="750" alt="screen shot 2017-10-20 at 2 46 39 pm" src="https://user-images.githubusercontent.com/13629122/31837144-b4a2c3d2-b5a5-11e7-8808-d9cd40149e1b.png">
<img width="641" alt="screen shot 2017-10-20 at 2 45 07 pm" src="https://user-images.githubusercontent.com/13629122/31837145-b4b816ba-b5a5-11e7-9ebd-f3eaa11fa1af.png">
<img width="744" alt="screen shot 2017-10-20 at 2 42 22 pm" src="https://user-images.githubusercontent.com/13629122/31837146-b4c2431a-b5a5-11e7-9504-e204792af667.png">

**Comment by kwasiopoku** [comment]
Fixed

**Comment by cneidle** [comment]
Handshapes are not showing up properly for these examples

<img width="693" alt="screen shot 2017-10-22 at 8 32 28 pm" src="https://user-images.githubusercontent.com/13629122/31868114-47913354-b768-11e7-9d34-98b16756bf91.png">

For compounds, the start should be the start of the whole compound (not the start of the last part).
