### ISSUE TITLE
Can you please regloss and move the 2 ASLLVD examples of (1h)PREGNANT ?

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#352]
<img width="743" alt="Screen Shot 2022-08-31 at 4 11 23 PM" src="https://user-images.githubusercontent.com/13629122/187773122-874e7d6e-b85e-48d5-8630-1d4f28211e33.png">

I have modified the 2 RIT files that have the gloss of (1h)PREGNANT, changing it to PREGNANT_2, and have left those 2 files in the re-upload folder.

<img width="660" alt="Screen Shot 2022-08-31 at 4 34 50 PM" src="https://user-images.githubusercontent.com/13629122/187776866-3ba2efa3-9c3b-4b06-966a-54c72c66530c.png">

So, with the 2 ASLLVD examples moved, and with the 2 RIT examples replaced, we will end up with:

PREGNANT
- PREGNANT(7)

PREGNANT_2
- PREGNANT_2(11)

instead of what is there now:

<img width="149" alt="Screen Shot 2022-08-31 at 4 14 57 PM" src="https://user-images.githubusercontent.com/13629122/187773577-56f637a2-63b2-47ed-b63c-269042cb1892.png">

Thank you so much

**Comment by kwasiopoku** [comment]
This has been resolved on dev1
