### ISSUE TITLE
Some DAI search results fail to be displayed

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#355]
Clicking on CULTURE brings up NO results.

I thought that perhaps a server was down or something, but other searches work (e.g. CROWDED).  VOICE also does not work.  These two are likely to contain examples from the newer "Ben" files; I don't know if that is related to this problem.

<img width="613" alt="Screen Shot 2022-09-02 at 1 48 08 PM" src="https://user-images.githubusercontent.com/13629122/188214557-73ed6aea-df2d-4064-8091-b3796b896e7e.png">

<img width="1371" alt="Screen Shot 2022-09-02 at 1 48 28 PM" src="https://user-images.githubusercontent.com/13629122/188214558-dc6f9c23-12b8-47e7-9c5a-863502e1b864.png">

<img width="584" alt="Screen Shot 2022-09-02 at 2 24 02 PM" src="https://user-images.githubusercontent.com/13629122/188215220-1f011604-a67b-499b-a19e-0884d43453ac.png">

This seems to be happening when there are examples involving BEN, another example being GROUP/TOGETHER

<img width="590" alt="Screen Shot 2022-09-02 at 2 25 32 PM" src="https://user-images.githubusercontent.com/13629122/188215480-127318d2-4874-4602-9c73-01fe8f8b2f78.png">

<img width="911" alt="Screen Shot 2022-09-02 at 2 26 24 PM" src="https://user-images.githubusercontent.com/13629122/188215479-fc854664-9458-49f3-9798-d91cf486a951.png">

**Comment by kwasiopoku** [comment]
This issue has been resolved on dev1 and dai

**Comment by cneidle** [comment]
thank  you!
