### ISSUE TITLE
0. Summary of ASLLVD corrections still needed

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#356]
#352  (1h)PREGNANT --> PREGNANT_2
 #225 ns-MAINE --> ns-PITTSBURGH/MAINE
#94 one occurrence of WORK --> WORK+
#336 BORN / BIRTH

in addition to compound issues, e.g., #266

**Comment by cneidle** [comment]
The above are now fixed, EXCEPT:

#94  one occurrence of WORK --> WORK+

THANK YOU !

**Comment by cneidle** [comment]
Everything fixed except for the extra + on WORK. - CN 10/14

**Comment by kwasiopoku** [comment]
This has been updated on dev1.cs

**Comment by cneidle** [comment]
I just commented on the other ticket.  That + is still not there.
