### ISSUE TITLE
One sign is in the wrong place

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#359]
Could you please move ns-PITTSBURGH/MAINE ?

<img width="956" alt="Screen Shot 2022-10-30 at 11 30 43 PM" src="https://user-images.githubusercontent.com/13629122/198925584-b6eaa913-ce96-424a-b23d-8975ccc32a41.png">

this is where it belongs:

<img width="1059" alt="Screen Shot 2022-10-30 at 11 34 07 PM" src="https://user-images.githubusercontent.com/13629122/198925771-e5ebf203-74d7-4ac1-bb89-76ccda99898f.png">

Thanks!

**Comment by cneidle** [comment]
Also:  another very small correction is needed for the ASLLVD data.  Could you please change the 2 start handshapes so that they are identical with the end handshapes shown here?  Thanks very much !!!

<img width="607" alt="Screen Shot 2022-11-01 at 5 09 28 PM" src="https://user-images.githubusercontent.com/13629122/199342220-b2f211a2-8cb8-4116-b367-cd0899b85fff.png">

**Comment by cneidle** [comment]
One more ASLLVD correction:  There is a handshape missing here.  All the dominant start handshapes should be the same.  Can you add the missing one?  THANKS.

<img width="553" alt="Screen Shot 2022-11-04 at 10 14 08 PM" src="https://user-images.githubusercontent.com/13629122/200096685-9f8c5bd3-b2c7-4511-94ba-38727c6106a3.png">

**Comment by kwasiopoku** [comment]
This is resolved on dev1

**Comment by cneidle** [comment]
Sorry - I misstated the necessary correction.  It is both the start and end handshapes that needed to be added.  I see you added the dominant handshape (as stated above).  Could you please add the non-dominant as well?  Sorry about that.  Thanks!  The other two issues are resolved :-). THANKS>

**Comment by kwasiopoku** [comment]
This has been corrected on dev1

**Comment by cneidle** [comment]
thank you !!
