### ISSUE TITLE
Sign Bank - groupings need to be fixed for these

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#361]
The compounds are messed up with TEACH+AGENT, (1h)TEACH+AGENT.

<img width="150" alt="Screen Shot 2022-11-06 at 11 44 51 AM" src="https://user-images.githubusercontent.com/13629122/200183387-51b607c9-a385-4ce3-9f1a-0f4cef2c3044.png">

What we should have is:

(1h)TEACH+AGENT
-  (1h)TEACH+AGENT (1)

TEACH+AGENT
-  TEACH+AGENT (57)

BROTHER should be moved out and in with the other examples of the same sign:

<img width="208" alt="Screen Shot 2022-11-06 at 11 39 11 AM" src="https://user-images.githubusercontent.com/13629122/200183104-dc564e83-5f2c-47ca-8181-a416d972a05a.png">

====

BROTHER has been moved to the correct place.  Thank you.  

**BUT the compound (1h)TEACH+AGENT has now disappeared** (although its parts are shown correctly):

<img width="286" alt="Screen Shot 2022-11-14 at 11 48 01 AM" src="https://user-images.githubusercontent.com/13629122/201717860-a692ca2c-4d3d-47c3-ac91-ee6d6159dcb7.png">
 
- CN.  11/14
- 
fixed -- thank you -- CN

**Comment by cneidle** [comment]
A few more small fixes needed to asllvd:

1)  Could you please add the relaxesd handshape to the top item non-dominant end handshape, so that it matches the other entries? 
<img width="971" alt="asllvd-fixmetoo" src="https://user-images.githubusercontent.com/13629122/200977268-6982ac28-1a20-4f01-af5a-a0faca832917.png">

2) Entries number 1 and 3 are missing their dominant end handshape.  It should be the same handshape as the other two entries shown here:  

<img width="867" alt="Screen Shot 2022-11-09 at 8 26 30 PM" src="https://user-images.githubusercontent.com/13629122/200977889-95e5232d-4475-491b-86b2-2e04ac860de9.png">


One item still not fixed - see the bottom of this message - thanks, CN

**Comment by cneidle** [comment]
Another set of missing handshapes:

The first two are missing the start and end dominant handshapes.  These should both look exactly like the third one:

<img width="637" alt="Screen Shot 2022-11-09 at 8 47 25 PM" src="https://user-images.githubusercontent.com/13629122/200980630-aa0a1e78-5141-43f8-a0ee-fb4f3b3dce74.png">

THANKS !!

fixed - thanks - CN

**Comment by cneidle** [comment]
Same problem here:  The top row of handshapes should look like the other three:

<img width="537" alt="Screen Shot 2022-11-09 at 8 57 05 PM" src="https://user-images.githubusercontent.com/13629122/200981766-fdfa8a78-e1f2-46f6-a710-ba8a70f9f978.png">

Could you please add the missing end non-dominant handshapes?  THANKS.

fixed - thank you - CN

**Comment by cneidle** [comment]
Not sure why those handshapes should have disappeared.  They were present in Ashwin's database...

<img width="731" alt="Screen Shot 2022-11-09 at 10 34 28 PM" src="https://user-images.githubusercontent.com/13629122/200994773-fbf70e3b-fa23-4253-802d-cd9c7b3e110c.png">

<img width="729" alt="Screen Shot 2022-11-09 at 10 35 25 PM" src="https://user-images.githubusercontent.com/13629122/200994790-81f34ff1-39a8-4676-a77f-734a452851f3.png">

**Comment by cneidle** [comment]
4 more missing handshapes (start and end, dominant).  All of these should have the same start handshapes.

<img width="941" alt="Screen Shot 2022-11-10 at 9 39 29 AM" src="https://user-images.githubusercontent.com/13629122/201120653-31affbe1-cd88-41ec-a786-dc7d7eeb6674.png">

fixed - thank you - CN

**Comment by cneidle** [comment]
The + is missing from this compound (in multiple places: the compound itself plus the 2 compound parts):  it should be #DO+part:indef

<img width="221" alt="Screen Shot 2022-11-10 at 12 45 36 PM" src="https://user-images.githubusercontent.com/13629122/201168992-7a9a18cd-a05f-4fdd-a13c-9bc51c57055c.png">

<img width="267" alt="Screen Shot 2022-11-10 at 12 47 08 PM" src="https://user-images.githubusercontent.com/13629122/201169234-4b73a58f-9044-420f-8b14-bc1346122537.png">

fixed - thank you - CN

**Comment by cneidle** [comment]
Another case of missing handshapes:  these should all be the same.  Could you fill in the missing ones?
THANKS.

<img width="582" alt="Screen Shot 2022-11-10 at 4 22 16 PM" src="https://user-images.githubusercontent.com/13629122/201208688-0125cd92-a4ce-4be6-ab87-f939a018f6b1.png">

fixed - thank you - CN

**Comment by cneidle** [comment]
Another missing hs needs to be restored:

<img width="631" alt="Screen Shot 2022-11-10 at 5 43 59 PM" src="https://user-images.githubusercontent.com/13629122/201221730-53dfff74-7956-44e2-b7f8-612b8066b72e.png">

fixed - thank you - CN

**Comment by cneidle** [comment]
More missing handshapes: V/2 

<img width="935" alt="Screen Shot 2022-11-11 at 10 22 39 AM" src="https://user-images.githubusercontent.com/13629122/201371179-e4d1f7e6-f637-4f7e-b7b2-2bcce9f0145d.png">

fixed - thank you - CN

**Comment by cneidle** [comment]
Missing handshapes here also, also V/2:

<img width="690" alt="Screen Shot 2022-11-11 at 10 32 20 AM" src="https://user-images.githubusercontent.com/13629122/201373117-ed60c3dd-c4d6-4eac-9ce1-453da8bf9d96.png">

fixed - thank you - CN

**Comment by cneidle** [comment]
more missing handshapes, also V/2

the second sign should have exactly the same handshapes as the third:

<img width="701" alt="Screen Shot 2022-11-11 at 2 51 09 PM" src="https://user-images.githubusercontent.com/13629122/201421508-0c0f5896-ce4e-4eb7-818b-9d80dfc1d50e.png">

This was modified, but not quite correctly.  The final handshape for 207840 should have been the same as the final handshape for 5025 (not 5024).  Could you please change that final handshape to V/2 ?  Thanks.

**Comment by cneidle** [comment]
There is an error in the glossing of the sign below.  This is actually the sign ns-IRAN rather than ns-IRAQ.  Could you please change all occurrences of ns-IRAQ to ns-IRAN ?

<img width="844" alt="Screen Shot 2022-11-11 at 3 52 03 PM" src="https://user-images.githubusercontent.com/13629122/201429073-dd1b4298-bb5f-4dc2-9563-94c48d239ab7.png">

We have another example of the sign for ns-IRAN from DSP, as shown below; so these will all end up together once the above fix is made.  THANKS !

<img width="742" alt="Screen Shot 2022-11-11 at 3 54 07 PM" src="https://user-images.githubusercontent.com/13629122/201429192-f3dcaff6-bb7c-4cb1-9c8b-31330329bada.png">

fixed - thank you - CN

**Comment by cneidle** [comment]
Here's an opposite problem: a handshape that needs to be deleted:

Please delete the start handshape on the dominant hand for the first sign.   THANKS.

<img width="735" alt="Screen Shot 2022-11-11 at 6 25 37 PM" src="https://user-images.githubusercontent.com/13629122/201443818-ba2c8002-b936-475f-bd4d-747ed75d9638.png">

fixed - thank you - CN

**Comment by cneidle** [comment]
more missing handshapes - also V/2.

The first sign should have the same handshapes as the others:

<img width="649" alt="Screen Shot 2022-11-11 at 6 39 58 PM" src="https://user-images.githubusercontent.com/13629122/201444779-7241effb-b9c1-4139-881a-9c92b96b18df.png">

thanks!!

fixed - thank you - CN

**Comment by cneidle** [comment]
6 more missing V/2 handshapes - start and end dominant.  Alll these signs should be the same:


<img width="748" alt="Screen Shot 2022-11-11 at 6 51 03 PM" src="https://user-images.githubusercontent.com/13629122/201445474-228c4dc3-2c6a-4435-ad11-61006ca67e29.png">

fixed - thank you - CN

**Comment by cneidle** [comment]
Last sign should be like all the others - more missing V/2 handshapes.

<img width="725" alt="Screen Shot 2022-11-11 at 6 54 13 PM" src="https://user-images.githubusercontent.com/13629122/201445618-5e81ef1f-fc1d-4a4f-8cfe-1ff776b1f28e.png">

fixed - thank you - CN

**Comment by cneidle** [comment]
Another set of missing V/2 handshapes - start and end dominant for the first sign.  Should be the same as the others.  Thanks.

<img width="684" alt="Screen Shot 2022-11-11 at 6 58 43 PM" src="https://user-images.githubusercontent.com/13629122/201445853-b3f6c32c-dbeb-4da0-957f-744fb70405aa.png">

fixed - thank you - CN

**Comment by kwasiopoku** [comment]
This have all be resolved on dev1

**Comment by cneidle** [comment]
REMAINING TO BE FIXED:

<img width="847" alt="Screen Shot 2022-11-15 at 9 02 49 AM" src="https://user-images.githubusercontent.com/13629122/201939106-2d3fd61f-d03b-42b4-a711-495b71eff7d8.png">


-----

<img width="681" alt="Screen Shot 2022-11-20 at 1 12 34 PM" src="https://user-images.githubusercontent.com/13629122/202918646-1f1a0338-925e-4af2-ba23-210643997b9f.png">

**Comment by kwasiopoku** [comment]
The last two corrections have been made on dev1
