### ISSUE TITLE
GIRL-SCOUT - need to discuss

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#362]
We should either hide these examples, or else assign them to the "other handshape" icon (which has a ?).

We should discuss...

<img width="903" alt="Screen Shot 2022-11-10 at 6 17 10 PM" src="https://user-images.githubusercontent.com/13629122/201226274-159dcc84-2962-47a0-af65-fc06ad7c09aa.png">

**Comment by cneidle** [comment]
one possibility

<img width="164" alt="Screen Shot 2022-11-10 at 6 47 38 PM" src="https://user-images.githubusercontent.com/13629122/201229625-ad699709-f2f4-4cf4-a3d7-ab2171f3f84b.png">

**Comment by kwasiopoku** [comment]
This has sign has been hidden and is no longer show for non-admin users

**Comment by cneidle** [comment]
I believe this is done.
