### ISSUE TITLE
more ASLLVD corrections

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#363]
Here, the second sign has the dominant and non-dominant handshapes reversed!

The second sign's handshapes should be adjusted to match those if the first sign.  thanks!

<img width="651" alt="Screen Shot 2022-11-12 at 9 11 47 AM" src="https://user-images.githubusercontent.com/13629122/201478127-6c9e0c22-8800-453f-a8ed-6a29579d886f.png">

FIXED - thank you - CN

**Comment by cneidle** [comment]
4 more missing V/2 handshapes:  The first two signs should have exactly the same handshapes as the third:


<img width="658" alt="Screen Shot 2022-11-12 at 12 18 11 PM" src="https://user-images.githubusercontent.com/13629122/201486451-c438383b-d585-412c-8275-26a22a39dd03.png">


FIXED - thank you - CN

**Comment by cneidle** [comment]
Two more missing handshapes.  Please adjust the first so that it has the same handshapes as the second.


<img width="646" alt="Screen Shot 2022-11-12 at 1 00 24 PM" src="https://user-images.githubusercontent.com/13629122/201488258-5be21bcb-a1c9-4ad5-9794-3da764c82fea.png">

fixed - thank you - CN

**Comment by cneidle** [comment]
More missing V/2 handshapes. The 2nd sign should be like the others:


<img width="870" alt="Screen Shot 2022-11-12 at 2 32 08 PM" src="https://user-images.githubusercontent.com/13629122/201491464-c0198d44-3373-4926-a4f6-7c6baad8e288.png">


FIXED - thank you - CN

**Comment by cneidle** [comment]
**OOPS !  This was not a problem with the ASLLVD data, but with the SignStream file.  It has since been corrected, so. PLEASE IGNORE THIS ONE !   - sorry - thanks - Carol**

More missing handshapes.  The first sign should be exactly like the THIRD:


<img width="933" alt="Screen Shot 2022-11-12 at 2 35 26 PM" src="https://user-images.githubusercontent.com/13629122/201491577-9edc322e-39aa-4f9b-ae12-1b3fd4c14c5f.png">

===================================

READ_2 has totally disappeared !!!!!

- CN - 11/15

<img width="597" alt="Screen Shot 2022-11-15 at 9 31 16 AM" src="https://user-images.githubusercontent.com/13629122/201945084-8066a7ce-dbe7-49a8-809a-d8391ceedcfb.png">


- This is now fine.  Thanks!  - CN

**Comment by cneidle** [comment]
2 more missing V/2 handshapes.  Handshapes for first sign should be the same as for the others.


<img width="900" alt="Screen Shot 2022-11-12 at 5 11 49 PM" src="https://user-images.githubusercontent.com/13629122/201496558-6545ed0a-0bfd-43a6-b0b9-f952c0657ef6.png">

fixed - thank you - CN

**Comment by cneidle** [comment]
Two more missing handshapes.  The third sign should have the same handshapes as the first sign below.  Thanks.

<img width="596" alt="Screen Shot 2022-11-12 at 6 14 06 PM" src="https://user-images.githubusercontent.com/13629122/201498217-81a9f7a5-4415-4c45-a1f5-3edd491d3ed2.png">

=============

This was modified, but incorrectly.  207969 should match 7855, not 7854.  

<img width="570" alt="Screen Shot 2022-11-15 at 9 36 02 AM" src="https://user-images.githubusercontent.com/13629122/201946158-d227641c-2df5-4292-ab39-bf2b59846bd5.png">

- CN, 11/15

**Comment by cneidle** [comment]
Two more missing V/2 handshapes. The 2nd sign should have the same handshapes as the others. Thanks.

<img width="749" alt="Screen Shot 2022-11-12 at 11 06 20 PM" src="https://user-images.githubusercontent.com/13629122/201505189-56b00f3b-7895-411f-a3e7-d6443e865db6.png">

fixed - thank you - CN

**Comment by kwasiopoku** [comment]
All of these corrections have been made on dev1

**Comment by cneidle** [comment]
See notes above for SMOKE.  

Everything else is good!  - Thanks, CN.  11/16

**Comment by kwasiopoku** [comment]
The handshapes for SMOKE++(207969) has been updated to match 7855

**Comment by cneidle** [comment]
fixed.  thank you!
