### ISSUE TITLE
DSP video and thumbnails missing from DAI

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#364]
<img width="960" alt="Screen Shot 2022-11-12 at 4 43 25 PM" src="https://user-images.githubusercontent.com/13629122/201495730-8deec39e-88a8-4c48-80fe-7888256f99cb.png">

**Comment by kwasiopoku** [comment]
This is available on dev1 so I will validate this again when we migrate the data from dev1 to dai
