### ISSUE TITLE
Request to hide two signs 

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#366]
Could you please hide these two?  THANKS.

<img width="1085" alt="Screen Shot 2022-11-13 at 7 46 08 AM" src="https://user-images.githubusercontent.com/13629122/201522521-9413580a-b10c-45c7-883e-dd691ea6fe0e.png">

<img width="1013" alt="Screen Shot 2022-11-13 at 7 47 24 AM" src="https://user-images.githubusercontent.com/13629122/201522522-b41af8cc-de48-4d95-a7f0-cc53b2905a9b.png">

**Comment by kwasiopoku** [comment]
This is done on dev1

**Comment by cneidle** [comment]
thank you!
