### ISSUE TITLE
IMPORTANT:  Some signs are missing from dev1

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#367]
Related to #361

Missing compounds that start with. e.g., (1):

dev1 on the left; DAI on the right here

<img width="426" alt="Screen Shot 2022-11-14 at 7 28 21 PM" src="https://user-images.githubusercontent.com/13629122/201796548-f8764eb2-fec8-48e9-baf5-7e983933a8f6.png">

<img width="428" alt="Screen Shot 2022-11-14 at 7 31 04 PM" src="https://user-images.githubusercontent.com/13629122/201796766-0d0dbb78-fdfa-4f8e-9d90-a01675d8bd2c.png">

**Comment by cneidle** [comment]
ns-#AA is also missing

<img width="289" alt="Screen Shot 2022-11-14 at 7 33 12 PM" src="https://user-images.githubusercontent.com/13629122/201797135-9b673671-a923-4645-8c91-edd5a89f12cd.png">

**Comment by cneidle** [comment]
(1h)ACCEPT is also missing

<img width="367" alt="Screen Shot 2022-11-14 at 7 35 21 PM" src="https://user-images.githubusercontent.com/13629122/201797391-01626bfd-45c2-4bba-ad88-e0d660009637.png">

**Comment by cneidle** [comment]
AGE-SIX+HALF also missing

<img width="387" alt="Screen Shot 2022-11-14 at 7 38 37 PM" src="https://user-images.githubusercontent.com/13629122/201797780-d245a76e-3d32-4a5a-bfe2-3ed6e6eb5ae0.png">

**Comment by cneidle** [comment]
Also missing:  AGE-TWENTY-ONE

<img width="325" alt="Screen Shot 2022-11-14 at 7 39 38 PM" src="https://user-images.githubusercontent.com/13629122/201797951-fce6e834-9066-4a54-a481-7618992f36fb.png">

**Comment by cneidle** [comment]
ALWAYS+FOREVER is missing

<img width="589" alt="Screen Shot 2022-11-14 at 7 45 15 PM" src="https://user-images.githubusercontent.com/13629122/201798609-a0132ae2-f1e5-4d9b-a8ed-fd9b25ded910.png">

**Comment by cneidle** [comment]
Hopefully these are enough examples to allow you to resolve the issue with th parser.

I'll gladly check. again whenever you think this is resolved.

Thanks !!!!

**Comment by kwasiopoku** [comment]
This has been resolved on dev1

**Comment by cneidle** [comment]
PROBLEMS - This is what I see on DAI, and what SHOULD be on dev 1.  (Note:  I am not logged in on DAI):

<img width="973" alt="Screen Shot 2022-11-15 at 9 39 18 AM" src="https://user-images.githubusercontent.com/13629122/201947122-b741da6b-47a8-4c6e-ad06-a87ec505fbf9.png">


However, this is what shows up on dev1 

<img width="572" alt="Screen Shot 2022-11-15 at 9 38 37 AM" src="https://user-images.githubusercontent.com/13629122/201947147-310c2989-fe0f-414e-abee-ac4370f0cf85.png">

===================

Same problem for ns-#AA - on DAI:

<img width="963" alt="Screen Shot 2022-11-15 at 9 41 56 AM" src="https://user-images.githubusercontent.com/13629122/201947784-7b7ba054-3a6a-4a57-80d6-747f804507f9.png">


but on dev1:

<img width="579" alt="Screen Shot 2022-11-15 at 9 41 26 AM" src="https://user-images.githubusercontent.com/13629122/201947753-accb101e-ada8-430b-9bd1-49f39b9b7dae.png">

===================

same for (1h)ACCEPT 

on DAI

<img width="991" alt="Screen Shot 2022-11-15 at 9 43 59 AM" src="https://user-images.githubusercontent.com/13629122/201948276-c3739599-eb7a-49bd-b47b-4a1c2a4a4770.png">


on dev1

<img width="601" alt="Screen Shot 2022-11-15 at 9 43 37 AM" src="https://user-images.githubusercontent.com/13629122/201948309-eff4561c-ae89-493c-95f7-61f6313b32f3.png">

**Comment by cneidle** [comment]
All the rest of the above examples appear to have the same problem... I am not including the rest of the screenshots.

**Comment by kwasiopoku** [comment]
As discussed, this issue was because the uploaded collections were private mode.   I have updated the status field for the impacted collections to public
