### ISSUE TITLE
Would be good to terminate the "login" code everywhere

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#370]
I was unexpectedly redirected...

<img width="925" alt="Screen Shot 2022-11-25 at 11 09 28 PM" src="https://user-images.githubusercontent.com/13629122/204071854-29c0a0ae-2e7c-4f78-a8d4-e8d0bdee338e.png">

_______________

<img width="878" alt="Screen Shot 2022-11-25 at 11 07 01 PM" src="https://user-images.githubusercontent.com/13629122/204071815-0e90969d-0d3e-43ef-807b-da5aea78a427.png">

thanks

**Comment by cneidle** [comment]
This still needs to be fixed.

I am taken to the login page from the search page when I should not be.

Thank you.

**Comment by cneidle** [comment]
E.g. from this page

<img width="1120" alt="Screen Shot 2023-01-25 at 11 29 19 AM" src="https://user-images.githubusercontent.com/13629122/214620130-8ee4fb45-0891-4c8d-a775-c7cc1321db67.png">

**Comment by cneidle** [comment]
I *think* this has been fixed.  Thanks.

**Comment by kwasiopoku** [comment]
Yes this has been fixed
