### ISSUE TITLE
Small ASLLVD correction:  DEAF_2

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#377]
BOWLING-STRIKE_2 should be its own main entry.

So instead of:

<img width="157" alt="Screen Shot 2022-12-16 at 10 10 09 AM" src="https://user-images.githubusercontent.com/13629122/208128537-f2384377-6b18-4e4e-bed8-3a64a1c03492.png">

we should have

BOWLING-STRIKE

- BOWLING-STRIKE

BOWLING-STRIKE_2

- BOWLING-STRIKE_2

This has been taken care of   - CN. 2/18

**Comment by cneidle** [comment]
This still needs to be fixed.  - CN. 2/18

<img width="101" alt="Screen Shot 2022-12-18 at 10 22 28 AM" src="https://user-images.githubusercontent.com/13629122/208306520-858d707c-a46b-4bdd-8e17-8d69e7997621.png">


DEAF_2 should be its own main entry

we should have

DEAF
- DEAF

DEAF_2
- DEAF_2

But this is not from the ASLLVD, rather: 

6-Ben-Control-of-Sound-U-6

What's the best way to fix this ??

THANKS !!

**Comment by kwasiopoku** [comment]
This has been resolved
