### ISSUE TITLE
Sign Bank - Something very strange

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#38]
The 5 occurrences shown for SECOND (e.g.) seem to be 5 instances of a single example.  The composite video has (correctly) 5 *different* occurrences

<img width="684" alt="screen shot 2017-10-22 at 8 40 16 pm" src="https://user-images.githubusercontent.com/13629122/31868231-c535b1b2-b769-11e7-87da-be3938d4a480.png">

<img width="1349" alt="screen shot 2017-10-22 at 8 39 39 pm" src="https://user-images.githubusercontent.com/13629122/31868237-cf420f84-b769-11e7-990a-8b53cf549d30.png">

This seems to be the case with all windows that display occurrences.  What is displayed is n examples of a single one (where n = the number of different occurrences that actually exist).

**Comment by kwasiopoku** [comment]
Fixed
