### ISSUE TITLE
Sign Recognition:  Another incorrect relationship between sign and label in search results

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#382]
Results for Liz-ASLLVD-CURTAIN.mp4

The sign labelled as RAIN is actually DRIZZLE, and that's what selecting that sign
takes you to... 

Note however that DRIZZLE is a variant of RAIN

fixed

_______________

<img width="1023" alt="Screen Shot 2022-12-18 at 9 12 46 AM" src="https://user-images.githubusercontent.com/13629122/208303158-4428c124-1e54-4bbe-8e8b-79f007fed264.png">

_______________

<img width="876" alt="Screen Shot 2022-12-18 at 9 13 50 AM" src="https://user-images.githubusercontent.com/13629122/208303213-868ce591-4aef-416e-996c-0b962c973704.png">

_______________

<img width="164" alt="Screen Shot 2022-12-18 at 9 14 52 AM" src="https://user-images.githubusercontent.com/13629122/208303269-f30e37c9-8608-4c06-8e9a-aed13eb064a8.png">

**Comment by cneidle** [comment]
Results for videos/RIT-ASK_116782.mp4

<img width="1059" alt="Screen Shot 2022-12-18 at 9 37 55 AM" src="https://user-images.githubusercontent.com/13629122/208304434-889c5266-7a57-462e-85e6-dfe3cee08c87.png">

But the sign shown for DONUT is actually the variant (R)DONUT -- identical to the variant video for (R)DONUT shown when variants are displayed.

And if you select DONUT, you are taken to a variant instead:  (R)DONUT.

<img width="898" alt="Screen Shot 2022-12-18 at 9 38 11 AM" src="https://user-images.githubusercontent.com/13629122/208304444-3a632169-35d1-4bee-b99e-df36397f4ba4.png">

**Comment by cneidle** [comment]
Here's another case where what is displayed for the main entry is
instead a variant, identical with the variant displayed below.

WLASL-1h-CARELESS-09215.mp4

<img width="1090" alt="Screen Shot 2022-12-18 at 10 12 23 AM" src="https://user-images.githubusercontent.com/13629122/208306121-94b9bd15-e621-404d-bab4-93cf0c0d1a9b.png">

What is labelled as HORSE is really (2h)HORSE.


Selecting the main entry:

<img width="952" alt="Screen Shot 2022-12-18 at 10 13 35 AM" src="https://user-images.githubusercontent.com/13629122/208306139-4e1b564a-a2b7-459f-aed0-b728360a5573.png">


fixed

**Comment by cneidle** [comment]
Another case where the main entry that is being displayed is really the
variant, repeated below.  What is displayed with the label "EMERGENCY"
is really (2h)EMERGENCY.

WLASL-5-weather.mp4

<img width="1067" alt="Screen Shot 2022-12-18 at 10 33 04 AM" src="https://user-images.githubusercontent.com/13629122/208306801-371dad69-288e-48f4-9ce2-a67b81eb81ba.png">

fixed

**Comment by cneidle** [comment]
Another case where the main entry (in this case, GLUE) has the video of a variant (G)GLUE
displayed instead.  Same as the variant shown below it.  And choosing GLUE takes you to
the DAI page for (G)GLUE.

WLASL-BELL-05869.mp4

<img width="1032" alt="Screen Shot 2022-12-18 at 10 45 10 AM" src="https://user-images.githubusercontent.com/13629122/208307251-8e46a06f-2fc3-44bf-96fc-81fcd7bea7f9.png">




<img width="879" alt="Screen Shot 2022-12-18 at 10 45 22 AM" src="https://user-images.githubusercontent.com/13629122/208307294-05cc5c8d-2217-4f67-b24d-9e3bc35e7d31.png">

**Comment by kwasiopoku** [comment]
This issue has been resolved.... It will be work a discussion as there are some edge cases that could be problematic
