### ISSUE TITLE
Another video that does not display - not ASLLVD

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#383]
Here the problem cannot be the lack of an original video...

Results from videos/Tyler-ASLLVD-DOUBT.mp4

<img width="1044" alt="Screen Shot 2022-12-18 at 9 53 59 AM" src="https://user-images.githubusercontent.com/13629122/208305246-f0e790c5-7782-4191-85d9-510bde85c3a1.png">

But the video is indeed missing on the DAI:

<img width="833" alt="Screen Shot 2022-12-18 at 9 56 46 AM" src="https://user-images.githubusercontent.com/13629122/208305327-9430fa46-ac78-4230-9376-525fb2e0bbe6.png">

**Comment by cneidle** [comment]
Another one:  WLASL-A-CABBAGE-08535.mp4

<img width="1103" alt="Screen Shot 2022-12-18 at 10 38 28 AM" src="https://user-images.githubusercontent.com/13629122/208306978-2a17480b-829e-4ea5-95cc-6360caceb4de.png">

This video is also missing in the DAI.

<img width="966" alt="Screen Shot 2022-12-18 at 10 41 45 AM" src="https://user-images.githubusercontent.com/13629122/208307031-0e765ba6-e0e6-4621-8106-a1a5a7aa6f6b.png">

**Comment by cneidle** [comment]
The video for DOUBT-1p  and COOPERATE/UNITE_2 are still missing.

**Comment by cneidle** [comment]
See #399 .  That will fix this.

**Comment by kwasiopoku** [comment]
This is complete on dev1
