### ISSUE TITLE
Another missing video

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#384]
on DAI:

<img width="843" alt="Screen Shot 2022-12-20 at 6 59 09 PM" src="https://user-images.githubusercontent.com/13629122/208789614-e2a9522a-55e7-4e75-9282-7a4b6df9cb7b.png">

also missing on dev1

The requested URL /ss3front/sign_303939.mp4 was not found on this server.

**Comment by cneidle** [comment]
<img width="833" alt="Screen Shot 2022-12-24 at 12 35 29 PM" src="https://user-images.githubusercontent.com/13629122/209446211-df05e406-d72e-408d-ae6b-0de01a983366.png">

**Comment by kwasiopoku** [comment]
This has been resolved on dev1 and dai

**Comment by cneidle** [comment]
thank you !
