### ISSUE TITLE
sign search - tiny fix needed

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#385]
Please change the message by adding "again" after "try".  Thanks.

<img width="590" alt="Screen Shot 2022-12-24 at 11 42 16 AM" src="https://user-images.githubusercontent.com/13629122/209444578-0070fdc5-768e-4df4-8e10-5142f659567d.png">

**Comment by kwasiopoku** [comment]
This has been fixed on dev1.

**Comment by cneidle** [comment]
thank you :-)
