### ISSUE TITLE
tiny fix - please add line break

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#39]
so that we will have, on the acknowledgments page:

Data Access Interface (DAI) 2 
<img width="939" alt="screen shot 2017-10-22 at 11 23 39 pm" src="https://user-images.githubusercontent.com/13629122/31871131-3ab06764-b780-11e7-8b71-14ee6deae83f.png">

     Credits and Acknowledgments

**Comment by cneidle** [comment]
picture came out between the 2 lines.

Should be:

Data Access Interface (DAI) 2
     Credits and Acknowledgments

so that the title is not obscured by the menu on the right.

thanks.

**Comment by kwasiopoku** [comment]
Fixed
