### ISSUE TITLE
Gloss alignment issues

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#40]
Nothing new, but I don't see a ticket for it.  Still some gloss alignment problems, e.g.:

<img width="1011" alt="screen shot 2017-10-25 at 7 11 11 am" src="https://user-images.githubusercontent.com/13629122/31995801-e829afc0-b953-11e7-9d02-ea3b7da6ee14.png">

**Comment by kwasiopoku** [comment]
Fixed and confirmed
