### ISSUE TITLE
Data correction needed for 1 ASLLVD sign

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#414]
When we search the Sign Bank within SignStream, this is what comes up for #IF.

<img width="929" alt="Screen Shot 2023-03-03 at 3 36 39 PM" src="https://user-images.githubusercontent.com/13629122/222824847-ee412267-73f0-4cb2-a9bb-6a02b1af442b.png">

<img width="871" alt="Screen Shot 2023-03-03 at 3 37 02 PM" src="https://user-images.githubusercontent.com/13629122/222824840-b9ce1633-77be-4877-92d2-a9fa1cb4a3e1.png">

This is NOT actually the sign #IF.  It is actually the sign we would gloss as #IFwg.  

So I have updated the default occurrence for #IF on both dev1 and DAI, to correct this.

However, the other three occurrences of #IF from the ASLLVD examples need to be relabelled as #IFwg.

#IFwg should also be made a variant under #IF.  So we would have

  #IF
>   #IF
>   #IFwg

So the first of these is now shown correctly below.  But the other three need to be reglossed as #IFwg (which will now be an entry/variant under #IF):

<img width="1098" alt="Screen Shot 2023-03-03 at 3 54 55 PM" src="https://user-images.githubusercontent.com/13629122/222827765-120a5be7-a253-4484-9317-5e4bbce7ea86.png">

**Comment by cneidle** [comment]
Note that there are lots of examples of #IF and 1 example of #IFwg in the non-ASLLVD data.  Those are correct.  No change is needed to the non-ASLLVD data (other than making #IFwg an entry/variant under #IF).  THANK YOU.

**Comment by kwasiopoku** [comment]
this has been resolved on dev1
