### ISSUE TITLE
+ missing on dev1, correct on DAI:  Should be #DO+part:indef

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#417]
**This is correct (DAI):**

<img width="151" alt="Screen Shot 2023-03-05 at 2 45 06 PM" src="https://user-images.githubusercontent.com/13629122/222982187-20131f6a-1b3c-4d9a-8673-63aa21640668.png">

<img width="1207" alt="Screen Shot 2023-03-05 at 2 42 23 PM" src="https://user-images.githubusercontent.com/13629122/222982128-ea8698cd-2842-44bf-bd66-b6437aa5e6c1.png">

**This is missing a + (dev1)**

<img width="137" alt="Screen Shot 2023-03-05 at 2 44 08 PM" src="https://user-images.githubusercontent.com/13629122/222982151-89005763-c457-440b-857c-f6616778500e.png">

Top of this window:

<img width="798" alt="Screen Shot 2023-03-05 at 2 41 38 PM" src="https://user-images.githubusercontent.com/13629122/222982121-a6c8d493-2878-4cd0-a3d5-0855bc46353f.png">

also the compound part

<img width="322" alt="Screen Shot 2023-03-05 at 8 03 10 PM" src="https://user-images.githubusercontent.com/13629122/222997471-ee2cb31b-3bcd-4553-a987-5b3ed334793f.png">

**Comment by cneidle** [comment]
This had apparently been fixed as of last November, but perhaps only on an ad hoc basis...

from #361 

<img width="860" alt="Screen Shot 2023-03-05 at 7 59 43 PM" src="https://user-images.githubusercontent.com/13629122/222997323-d44e00d1-62cf-4ab0-a45f-2e201da6cba7.png">

**Comment by cneidle** [comment]
This is more general.  The previous fixes from #317 have also been undone on dev1...

**Comment by kwasiopoku** [comment]
This has been resolved on dev1.cs
