### ISSUE TITLE
ASLLVD compound correction needed

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#418]
on both DAI and dev11:

These two variants should be separate main entries.  As with all compounds.

HEAR+NOISE
HEAR+(1h)NOISE

<img width="472" alt="Screen Shot 2023-03-05 at 3 12 10 PM" src="https://user-images.githubusercontent.com/13629122/222983488-f2d9e696-a490-4b83-b87b-4baef3051da3.png">

**Comment by cneidle** [comment]
another one:

<img width="475" alt="Screen Shot 2023-03-05 at 3 18 50 PM" src="https://user-images.githubusercontent.com/13629122/222983738-4d119ff5-9c96-4336-85da-726442c8cbcd.png">

**Comment by cneidle** [comment]
Another one.  I apologize for this, as this one was my fault :-(

<img width="436" alt="Screen Shot 2023-03-05 at 3 28 07 PM" src="https://user-images.githubusercontent.com/13629122/222984192-84133945-76cf-4298-8a12-ac3b0e75fbc7.png">

**Comment by kwasiopoku** [comment]
This has been updated on dev1.cs
