### ISSUE TITLE
CARROT showing up on dev1 as canonical occurrence of NOT !

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#419]
We need to check if there are others like this, and we need to fix this one.

<img width="976" alt="Screen Shot 2023-03-05 at 4 31 39 PM" src="https://user-images.githubusercontent.com/13629122/222987321-fae8203b-ad6f-403b-affd-97ecbfa2603d.png">

thanks!

**Comment by kwasiopoku** [comment]
This has been fixed on dev1.cs
