### ISSUE TITLE
Not urgent, but... there is an issue with the Restriction of the search to hand and other characteristics

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#42]
We discussed this when we were looking at the search restrictions related to the hands.

Not necessary prior to our beta release, but we should look at this again.   The logic doesn't quite work.

See my suggestion below -- and if something in this box is selected, compounds should be de-selected.  If something in the bottom part is selected, then all but lexical signs should be de-selected.

<img width="677" alt="screen shot 2017-10-28 at 4 58 22 pm" src="https://user-images.githubusercontent.com/13629122/32138471-6896e010-bc01-11e7-9b79-6540b0d0f788.png">

This obviously isn't going to happen today, but I think this is what is needed to make this work right.   (SORRY)

**Comment by cneidle** [comment]
This might be a simpler -- and better -- alternative:

<img width="677" alt="screen shot 2017-10-28 at 4 58 59 pm" src="https://user-images.githubusercontent.com/13629122/32138468-5b0e0cf2-bc01-11e7-98ed-100e89048570.png">

**Comment by kwasiopoku** [comment]
Fixed

**Comment by cneidle** [comment]
Clicking on a handshape doesn't de-select non-lexical signs.

![screen shot 2017-10-30 at 4 06 55 pm](https://user-images.githubusercontent.com/13629122/32193078-7c70d1cc-bd8c-11e7-904c-1cf03aec678d.png)

**Comment by kwasiopoku** [comment]
Fixed

**Comment by cneidle** [comment]
Still not working for me...

**Comment by kwasiopoku** [comment]
This fix has now been pushed to the dai production server.
