### ISSUE TITLE
Sign Lookup:  Default selection missing

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#421]
additional/Liz-BEFORE_2-SCHOOL-ASL_2008_02_15-scene-47-1275-1331-camera1.mp4

<img width="885" alt="Screen Shot 2023-03-12 at 1 44 12 PM" src="https://user-images.githubusercontent.com/13629122/224562629-6738834c-047e-47ed-b8a8-bc67bd556989.png">

**Comment by cneidle** [comment]
Presumably this is because the canonical entry variant for this class label does not have the same text string as the class label.  This is not the only case of that...

**Comment by kwasiopoku** [comment]
This has been resolved and pushed to dev1.cs

**Comment by cneidle** [comment]
YAY.  Beautiful.  Thank you.
