### ISSUE TITLE
Sign Lookup:  When there is only one option, user should be taken directly to Sign Bank

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#422]
But that's not happening.

e.g.      videos/other/x-Brady-ASLLVD-1h-DIMPLE.mp4

<img width="844" alt="Screen Shot 2023-03-12 at 1 52 24 PM" src="https://user-images.githubusercontent.com/13629122/224563016-9d83ba85-4830-43b1-af06-a22972906eed.png">

<img width="791" alt="Screen Shot 2023-03-12 at 1 53 18 PM" src="https://user-images.githubusercontent.com/13629122/224563068-7962f0d0-40b3-474b-9395-f6409466aa5d.png">

**Comment by kwasiopoku** [comment]
This has been fixed on dev1.cs

**Comment by cneidle** [comment]
Thank you !
