### ISSUE TITLE
Carey recording of TRIANGLE can be added to the Sign Bank.

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#424]
THANK YOU.

<img width="263" alt="Screen Shot 2023-03-13 at 2 25 47 PM" src="https://user-images.githubusercontent.com/13629122/225166097-c67fe1f8-2fdd-472f-b271-a078fbf380e4.png">

**Comment by kwasiopoku** [comment]
This has been resolved on dev1.cs
