### ISSUE TITLE
Problem with display of canonical form for search results

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#426]
This is what now shows up for Carey's ARRIVE video (Carey-videos/1-ARRIVE_1.mov).
Note TIRED.

The (1h) variant shows up twice.

The intermediate page correctly shows the canonical variant

<img width="1482" alt="Screen Shot 2023-03-16 at 11 41 01 AM" src="https://user-images.githubusercontent.com/13629122/225689176-cb39effa-9532-4bad-a4b8-809c5c769065.png">

<img width="711" alt="Screen Shot 2023-03-16 at 12 41 08 PM" src="https://user-images.githubusercontent.com/13629122/225690986-35d5ff1d-6736-46a2-9151-c2bcc7cc20ae.png">

Same problem with Carey-videos/2p-CUTE_1.mov - for TEND.  The (1h) variant is showing
up as the canonical form and then again as the variant.  Although it all shows up correctly
on the intermediate page.

<img width="1491" alt="Screen Shot 2023-03-16 at 12 43 34 PM" src="https://user-images.githubusercontent.com/13629122/225691764-ba17a642-1f1c-4b31-b6da-4fa9f2df3e0a.png">

<img width="732" alt="Screen Shot 2023-03-16 at 12 43 43 PM" src="https://user-images.githubusercontent.com/13629122/225691794-d0c23f78-e41d-429b-8a11-7cf7231e02c4.png">

**Comment by cneidle** [comment]
Same problem for VICARS/
<img width="121" alt="Screen Shot 2023-03-16 at 1 05 54 PM" src="https://user-images.githubusercontent.com/13629122/225697469-42918fc8-dccc-4dcc-8760-af8c31eb7c35.png">

Look at HORSE - where the variant (2h)HORSE shows up as the canonical form as well as the variant.


<img width="1281" alt="Screen Shot 2023-03-16 at 1 04 35 PM" src="https://user-images.githubusercontent.com/13629122/225697234-b7b287ab-5047-46b0-9048-2c5bd9aec434.png">

<img width="716" alt="Screen Shot 2023-03-16 at 1 04 45 PM" src="https://user-images.githubusercontent.com/13629122/225697266-97f68092-45c0-4e61-b080-95ea5f04a64d.png">

**Comment by kwasiopoku** [comment]
This has been fixed on dev1.cs

**Comment by cneidle** [comment]
Looks good!  thanks.
