### ISSUE TITLE
dev1 special character issue

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#428]
<img width="223" alt="Screen Shot 2023-03-22 at 9 27 12 PM" src="https://user-images.githubusercontent.com/13629122/227075377-1ac3e6ca-4bef-4ba2-8d47-ca091ec6d096.png">

<img width="326" alt="Screen Shot 2023-03-22 at 9 28 36 PM" src="https://user-images.githubusercontent.com/13629122/227075480-281ec3f7-b8ca-411a-bfd1-f313df9333ba.png">

<img width="182" alt="Screen Shot 2023-03-22 at 9 29 23 PM" src="https://user-images.githubusercontent.com/13629122/227075647-bf2c7939-536a-4d8e-a18a-ce2b44b85d37.png">
<img width="281" alt="Screen Shot 2023-03-22 at 9 29 09 PM" src="https://user-images.githubusercontent.com/13629122/227075649-42371beb-289f-4e51-a762-ae0e60278372.png">

**Comment by kwasiopoku** [comment]
This has been resolved on dev1.cs

**Comment by cneidle** [comment]
GREAT !!

One remaining case needs to be fixed:

<img width="783" alt="Screen Shot 2023-03-25 at 3 20 06 PM" src="https://user-images.githubusercontent.com/13629122/227737213-82935dde-9c78-470f-b99d-9180071b57bf.png">

**Comment by cneidle** [comment]
This also needs to be addressed for the DAI part...  Just a few examples:

<img width="171" alt="Screen Shot 2023-03-25 at 3 22 29 PM" src="https://user-images.githubusercontent.com/13629122/227737293-69090189-8956-4ce6-b716-00a08ee82030.png">

<img width="156" alt="Screen Shot 2023-03-25 at 3 22 37 PM" src="https://user-images.githubusercontent.com/13629122/227737294-b9003f62-d505-4c0c-a10e-35275172ce3a.png">

Thank you VERY much!
