### ISSUE TITLE
Display of search criteria does not include handshape

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#43]
I had mentioned this in passing in the discussion of the dominant hand issues, but it deserves its own ticket (although this is non-urgent!  does not need to be fixed prior to release).

When a specific handshape is selected, that is not displayed.

<img width="865" alt="screen shot 2017-10-28 at 5 02 34 pm" src="https://user-images.githubusercontent.com/13629122/32138518-fb1fb1a0-bc01-11e7-954f-b51a175e01d9.png">

In this case, it should have shown that I had selected the start Dominant handshape  = "A"

**Comment by kwasiopoku** [comment]
Add all search criteria to the list of items searched for.  This is displayed at the top of the search results page to make it easier for users to know what they searched for.

**Comment by kwasiopoku** [comment]
Fixed.
