### ISSUE TITLE
PROBLEM WITH PARTICIPANTS on the DAI (resolved on dev1)

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#431]
This is correct on the DAI, but we don't want to replace the correct DAI information with the incorrect dev1 data!

On dev1:

Note there are some listed as 0 --

<img width="246" alt="Screen Shot 2023-03-25 at 5 37 54 PM" src="https://user-images.githubusercontent.com/13629122/227743415-9d901f7d-1423-42da-add7-7f5cf84cc113.png">

On DAI:

<img width="221" alt="Screen Shot 2023-03-25 at 5 35 47 PM" src="https://user-images.githubusercontent.com/13629122/227743348-2d6d41c8-5e9e-47c3-b009-e852de125a5b.png">

**Comment by kwasiopoku** [comment]
This has been resolved on dev1.cs

**Comment by cneidle** [comment]
Now seeing 

  No User (1821)

on the DAI
