### ISSUE TITLE
New correction needed for ASLLVD

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#432]
I found an error in the glossing, unfortunately.  The sign we have glossed as UNDEWEAR/PRECIOUS is actually identical with the sign we gloss as CHERISH.

The easiest way to fix this is for you to change the one ASLLVD occurrence of UNDERWEAR/PRECIOUS to CHERISH.

To make the other corrections, I will need to edit the 4 SignStream files for re-upload... sigh.

<img width="1007" alt="Screen Shot 2023-04-08 at 2 23 02 PM" src="https://user-images.githubusercontent.com/13629122/230737156-30a9dc71-db22-4b65-8f23-2118a3d74669.png">

THANKS.

**Comment by cneidle** [comment]
Those four files are now ready for re-upload.  THANKS.

<img width="495" alt="Screen Shot 2023-04-08 at 3 47 59 PM" src="https://user-images.githubusercontent.com/13629122/230740021-a0122353-25c7-4452-bd0f-725265768ce7.png">
<img width="499" alt="Screen Shot 2023-04-08 at 3 47 51 PM" src="https://user-images.githubusercontent.com/13629122/230740022-2b16ca70-3bca-4ad2-b067-7c8f1b6d59fe.png">

**Comment by kwasiopoku** [comment]
All 4 updated collections have been uploaded to dev1.cs.  Video processing is in progress

**Comment by kwasiopoku** [comment]
Video and thumbnail generation is complete

**Comment by cneidle** [comment]
thank you!
