### ISSUE TITLE
1 small data correction needed for the Sign Bank

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#441]
Carey has informed me that what we have as GO_2 should be its own main entry, rather than a variant of GO.  Whenever you have a chance, could you please make that change?  THANKS!

<img width="891" alt="Screen Shot 2023-06-18 at 11 09 32 AM" src="https://github.com/DCS-LCSR/ASL-DAI/assets/13629122/a1685c24-54d2-4a2e-aae5-7aed58a75aad">

**Comment by cneidle** [comment]
This remains to be done.

**Comment by kwasiopoku** [comment]
This has been resolved
