### ISSUE TITLE
Extraneous Plus signs still in variant labels

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#444]
This has been an issue for a long time...

<img width="245" alt="Screen Shot 2023-06-30 at 10 33 56 AM" src="https://github.com/DCS-LCSR/ASL-DAI/assets/13629122/070fd732-1745-4e92-8f7d-e3a776650e43">

**Comment by cneidle** [comment]
This is still unresolved.

**Comment by kwasiopoku** [comment]
This has been resolved
