### ISSUE TITLE
Same problem with the end handshape of a compound needing to be taken from the last element of the compound

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#45]
<img width="904" alt="screen shot 2017-10-28 at 5 17 36 pm" src="https://user-images.githubusercontent.com/13629122/32138637-feffdc6c-bc03-11e7-9c04-9fa4ed4a8061.png">

<img width="645" alt="screen shot 2017-10-28 at 5 17 02 pm" src="https://user-images.githubusercontent.com/13629122/32138638-ff0d27c8-bc03-11e7-9a2a-8784444b367f.png">

The error from Ashwin's system is still showing up.

**Comment by kwasiopoku** [comment]
Fixed
