### ISSUE TITLE
Missing/wrong thumbnails on DAI

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#454]
One of these is missing the initial thumbnail -

and the ones shown for the start of the sign are not the start of the sign...

<img width="803" alt="Screen Shot 2024-01-12 at 3 19 12 PM" src="https://github.com/DCS-LCSR/ASL-DAI/assets/13629122/2909619c-e3b6-4154-89a7-646ea9d5c5e7">

<img width="955" alt="Screen Shot 2024-01-12 at 3 19 21 PM" src="https://github.com/DCS-LCSR/ASL-DAI/assets/13629122/50480d1b-5d09-445e-9b2e-23f7ecfa7d21">

**Comment by kwasiopoku** [comment]
This has been resolved in dev1

**Comment by cneidle** [comment]
Thanks!  I can't check this right now, because the thumbnails are again inaccessible on dev1...
