### ISSUE TITLE
Still needs to be fixed:  'English Translation' --> 'Related English Words'

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#455]
This STILL says English Translation rather than Related English Words:

<img width="1253" alt="Screen Shot 2024-01-12 at 3 25 57 PM" src="https://github.com/DCS-LCSR/ASL-DAI/assets/13629122/007a28d3-2446-480a-b9cd-e8111c279b9c">

**Comment by kwasiopoku** [comment]
Reviewed and confirmed that this has been fixed
