### ISSUE TITLE
SELF

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#467]
(1) Please change the main entry SELF:i to SELF for all of this (leaving entry/variants and occurrence labels unchanged):

<img width="108" alt="Screen Shot 2024-06-23 at 11 11 29 AM" src="https://github.com/DCS-LCSR/ASL-DAI/assets/13629122/48c00d22-7def-41e8-a8e5-f1eddac8de1c">

=======
=======

(2) Please change main entry SELF-1p to SELF-1p-pl only for these variants:

    (A)SELF-1p-pl
    SELF-1p-pl

So we will end up with this:

SELF-1p
> SELF-1p
> (A)SELF-1p
> SELF-1p* (SELF-1p+CONFIDENT)

SELF-1p-pl
> (A)SELF-1p-pl
> SELF-1p-pl
   
instead of 

<img width="240" alt="Screen Shot 2024-06-23 at 11 15 25 AM" src="https://github.com/DCS-LCSR/ASL-DAI/assets/13629122/7f2703f7-c5d9-4b84-a3c0-ebfbedf4b650">

**Comment by kwasiopoku** [comment]
This has been updated on dai.cs

**Comment by cneidle** [comment]
Thank you !
