### ISSUE TITLE
Sign Bank export to SignStream

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#50]
Hi Augustine,

Just FYI - we are anticipating an imminent update to SignStream, as you probably gathered from the recent email.

This has new features, including the link to the DAI 2 for viewing occurrences.

As I mentioned in the last message, the display that currently showed for a sign from the Sign Bank file (the one that was last publicly released with SignStream) picked out the wrong sign.  I'm not sure if this is a bug, or if this is the result of the fact that your Sign Bank on the DAI 2 has evolved since the version that was exported for use with SignStream.  If the latter, we will need to be able to export the newest version of the Sign Bank for use with the next SIgnStream upgrade.  As we discussed some time back, this will only need to have the canonical example for each Sign/Variant, since the others have not been and will not be displayed from within SIgnStream (other than by opening up a browser window to connect to DAI 2).

Thanks!

**Comment by kwasiopoku** [comment]
I believe the changes to the sign bank since the last pushed version,
should address some of the issues you are noticing.  I will generate an
updated version and send it over to Greg.

**Comment by kwasiopoku** [comment]
Fixed
