### ISSUE TITLE
Icon: ? - 3 different use cases; best to have 3 different icons

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#51]
Just to reiterate what I wrote in yesterday's email:  Would suggest using a different ? type icon for the search options; using the existing ? icon to represent a handshape not in our canonical set; and using a blank rectangle for a missing handshape.

So, for example, I would like to search for the ? (non-standard) handshape.  When I select it, I can't tell that anything has been selected, because the icon for nothing selected is the same as for that handshape option... 

![screen shot 2017-11-21 at 11 39 12 am](https://user-images.githubusercontent.com/13629122/33084743-b82505c8-ceb0-11e7-9457-73417aef4c7f.png)

![screen shot 2017-11-21 at 11 39 19 am](https://user-images.githubusercontent.com/13629122/33084794-d9f85204-ceb0-11e7-925d-657c578023ff.png)

(I was trying to see if I could find any other cases where the handshape needed to be corrected in the annotations.)

**Comment by cneidle** [comment]
I see it shows up here :-)

![screen shot 2017-11-21 at 12 01 02 pm](https://user-images.githubusercontent.com/13629122/33085788-b9004aea-ceb3-11e7-97b7-2c285ff4508b.png)

**Comment by kwasiopoku** [comment]
Fixed and pushed to production
