### ISSUE TITLE
Many wh-questions are missing their labels

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#52]
<img width="1051" alt="screen shot 2017-12-20 at 11 31 47 am" src="https://user-images.githubusercontent.com/13629122/34217504-ab43164e-e579-11e7-8185-9e7f778cf8f8.png">

<img width="1044" alt="screen shot 2017-12-20 at 11 31 55 am" src="https://user-images.githubusercontent.com/13629122/34217512-b085ccc8-e579-11e7-9197-76998201a823.png">

<img width="1046" alt="screen shot 2017-12-20 at 11 32 03 am" src="https://user-images.githubusercontent.com/13629122/34217520-b4486604-e579-11e7-9a20-e3db9391b867.png">

<img width="1044" alt="screen shot 2017-12-20 at 11 32 09 am" src="https://user-images.githubusercontent.com/13629122/34217532-b80c839c-e579-11e7-9859-e4c1f53db3a7.png">

<img width="1055" alt="screen shot 2017-12-20 at 11 32 21 am" src="https://user-images.githubusercontent.com/13629122/34217541-bd971d2c-e579-11e7-9c95-0e3b62ec5266.png">

This is what it should look like:

<img width="1053" alt="screen shot 2017-12-20 at 11 35 15 am" src="https://user-images.githubusercontent.com/13629122/34217600-e33645b2-e579-11e7-99a1-05a5763e408b.png">

**Comment by kwasiopoku** [comment]
Fixed and confirmed
