### ISSUE TITLE
New icons:  Hitting "clear all" restores the old icons

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#53]
The new icons look great.

But from the main search page, if you hit "clear all" to clear the region with the handshapes, the old icons come back from the dead...

<img width="680" alt="screen shot 2017-12-20 at 1 16 34 pm" src="https://user-images.githubusercontent.com/13629122/34222028-1e28ccf4-e588-11e7-919b-8f4151390361.png">

**Comment by cneidle** [comment]
The icons also return when doing a search in the Sign Bank.

If I type in text into the search field and then hit a carriage return,
the old icons become visible.

before and after hitting the carriage return:


<img width="935" alt="screen shot 2017-12-25 at 4 37 13 pm" src="https://user-images.githubusercontent.com/13629122/34343082-fb4b5d4c-e991-11e7-8fdc-2ac20613cf08.png">

<img width="296" alt="screen shot 2017-12-25 at 4 37 21 pm" src="https://user-images.githubusercontent.com/13629122/34343086-0d9f320c-e992-11e7-8fde-c5f2d678db78.png">

**Comment by cneidle** [comment]
Also worth noting above is that the ? is still showing up in the sign search results, for one-handed signs, whereas this should be just a solid black rectangle, as we agreed (and as I thought you had implemented).   Thanks.

**Comment by kwasiopoku** [comment]
Fixed

**Comment by kwasiopoku** [comment]
Confirmed with Carol
