### ISSUE TITLE
Something is wrong here

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#56]
<img width="801" alt="screen shot 2018-01-23 at 7 34 45 pm" src="https://user-images.githubusercontent.com/13629122/35308236-a186e78c-0074-11e8-9a5e-5500f84d4063.png">

There is also a discrepancy between the examples in Ashwin's interface and those here for HEAD and HEAD_2

<img width="774" alt="screen shot 2018-01-23 at 7 35 04 pm" src="https://user-images.githubusercontent.com/13629122/35308250-ba963e94-0074-11e8-922a-2468690b02f4.png">

Compare with Ashwin:

<img width="768" alt="screen shot 2018-01-23 at 7 37 08 pm" src="https://user-images.githubusercontent.com/13629122/35308280-e050e940-0074-11e8-86df-3dcc597963d3.png">

<img width="741" alt="screen shot 2018-01-23 at 7 37 20 pm" src="https://user-images.githubusercontent.com/13629122/35308283-e3e593da-0074-11e8-96ad-a836df50acbe.png">

**Comment by cneidle** [comment]
There is a similar discrepancy between Ashwin's data and our sign bank for DEVIL/MISCHIEVOUS
<img width="745" alt="screen shot 2018-01-23 at 7 43 13 pm" src="https://user-images.githubusercontent.com/13629122/35308431-b6332c76-0075-11e8-8321-232d0605a8d8.png">

<img width="743" alt="screen shot 2018-01-23 at 7 42 30 pm" src="https://user-images.githubusercontent.com/13629122/35308432-b64bce66-0075-11e8-9cfc-0084a6b7485a.png">

These are all signs where it looks like changes may have been made at some point to the classification/grouping/glosses.  I am wondering if the version of the data used for the Sign Bank was something other than the latest version.

**Comment by kwasiopoku** [comment]
RESOLVED
