### ISSUE TITLE
Problem with Sign Bank search

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#57]
Sorry!  I accidentally posted this in the SignStream project.  Am copying it over here.

![screen shot 2018-01-24 at 9 53 29 am](https://user-images.githubusercontent.com/13629122/35338707-a1e199d4-00ec-11e8-86dc-117c185dccbd.png)

![screen shot 2018-01-24 at 9 53 45 am](https://user-images.githubusercontent.com/13629122/35338711-a5174cac-00ec-11e8-9fae-6c9f77d618c1.png)

![screen shot 2018-01-24 at 9 53 52 am](https://user-images.githubusercontent.com/13629122/35338719-a7ef5546-00ec-11e8-85d9-5fef2743dfe4.png)

**Comment by cneidle** [comment]
The original post is now closed, at" Search in Sign Bank not working right"  #204  (SignStream project)

**Comment by kwasiopoku** [comment]
Fixed
