### ISSUE TITLE
Sign Bank - examples from both ASLLVD (citation-form signs) and our continuous signing datasets

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#58]
Just recording this for the record:

1) The isolated sign data should appear at the top of the list, for each sign, labeled as such: "Citation-form examples", followed by the examples from the continuous signing datasets: "Examples from continuous signing."

2) For the continuous signing data, the button "Play composite video" should instead read "Play utterance."

3) The counts are off for the continuous signing examples.  It seems that when we remove a file from the DAI, its contributions to the DAI fail to be removed.  So that when they are reuploaded, there are duplications in the counts and the examples.

**Comment by kwasiopoku** [comment]
Fixed
