### ISSUE TITLE
Low-priority, very minor (but probably very quick) fix needed

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#61]
There is a sizing problem in the Safari display.  The lefthand column needs to be a little bit wider to accommodate the icons (or the icons could be made smaller):

![screen shot 2018-01-31 at 11 13 11 am](https://user-images.githubusercontent.com/13629122/35633728-f9f5632c-0677-11e8-9252-86708d981a89.png)

**Comment by kwasiopoku** [comment]
This issue is only visible when you are logged in.

**Comment by kwasiopoku** [comment]
Fixed
