### ISSUE TITLE
"Home" button works from some pages but not others

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#64]
From the Sign Search and Utterance Search pages, the "Home" button works fine.

But not so from the Overview and Acknowledgments & Credits page:

![screen shot 2018-01-31 at 11 29 55 am](https://user-images.githubusercontent.com/13629122/35634669-3db16d70-067a-11e8-969f-1ba11d2695ab.png)

![screen shot 2018-01-31 at 11 30 56 am](https://user-images.githubusercontent.com/13629122/35634675-42727ade-067a-11e8-8b88-827e4679b5a0.png)

**Comment by kwasiopoku** [comment]
Fixed
