### ISSUE TITLE
DAI - sign videos not playing

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#65]
In both Safari and Chrome, the utterance videos play fine, but not the sign videos.

Have just checked a couple of examples and have to run now, but FYI:

utterance video

![screen shot 2018-01-31 at 11 44 36 am](https://user-images.githubusercontent.com/13629122/35635468-5e682098-067c-11e8-86bf-097997ed7e9f.png)

sign video

![screen shot 2018-01-31 at 11 44 42 am](https://user-images.githubusercontent.com/13629122/35635487-69148310-067c-11e8-88e5-732d1de2096c.png)

Thanks,
 Carol

**Comment by cneidle** [comment]
Relatively high priority, fwiw.  Thanks !!

**Comment by kwasiopoku** [comment]
Fixed
