### ISSUE TITLE
Fix matlab single sign gloss extraction

### ISSUE THREAD

**Issue by kwasiopoku** [DCS-LCSR/ASL-DAI#68]
Some sign labels are showing incorrect main gloss.  The difference is in the attribute that we are using to determine the main gloss.  In Ashwin's interface, I suspect that he is using the corrected_sign_gloss field to group the labels whereas in the matlab script that Greg and Doug sent to me, we are using the gallaudet_gloss_description field.  In the cases where the two are different, the gloss will be labelled differently.  

Adding Gloss 48: (1)downstairs: (1)downstairs
                          utterance_xml: '/research/asl-data4/ASL_lexicon_project/asl-data2/quicktime/annotate/Si…'
                   xml_modified_datenum: 7.3484e+05
                      xml_modified_time: 1322506450
                                session: 'ASL_2011_07_19_Brady'
                                  scene: 95
                                  gloss: 'stairs2'
            **gallaudet_gloss_description**: '(1)downstairs'
                           gloss_period: [1310 1353]
                           onset_period: [1287 1312]
                          offset_period: [1355 1374]
                    initial_hold_period: []
                      final_hold_period: []
                             lhand_info: []
                             rhand_info: [3×2 double]
                           is_loan_sign: 0
                         compound_gloss: []
                  is_fingerspelled_sign: 0
                         is_number_sign: 0
                     is_classifier_sign: 0
                           sign_version: 1
                   sign_version_variant: 1
     session_scene_frame_number_datenum: 2.0251e+09
                 last_annotated_datenum: []
                           last_edit_by: []
                           last_edit_on: []
                           last_edit_at: []
                   **corrected_sign_gloss**: 'DOWNSTAIRS'
             corrected_start_end_frames: []
                          start_base_HS: []
                            end_base_HS: []
             start_non_dominant_base_HS: []
               end_non_dominant_base_HS: []
     signs_handshape_categorization_str: '0200000000'
                   dominant_HS_previous: []
               non_dominant_HS_previous: []
               annotate_verify_comments: 'Done - classified [revised: Naomi, moved here from 'OF:stairs2'] [Liz,T…'
           corrected_sign_gloss_datenum: []
     corrected_start_end_frames_datenum: []
                     old_compound_gloss: []
                set_reorganized_datenum: []
                      movie_label_gloss: []
               corrected_hand_locations: [1×1 struct]
                auto_move_no_new_signer: []
            overflow_sets_gloss_indices: []
        overflow_set_parent_gloss_index: []
    overflow_sets_sign_version_variants: []
               start_end_hand_locations: [2×6 double]
     start_end_hand_locations_confirmed: [1 1 0 0]
              hand_location_annotations: [2×6 double]
       sign_specific_annotator_messages: []

**Comment by cneidle** [comment]
Hi Augustine,

Yes, that makes sense!

I’m so glad you figured this out !!!

We definitely do NOT want to be using the Gallaudet gloss description !!!

THANK YOU !!!

best,
 Carol

**Comment by kwasiopoku** [comment]
Fixed
