### ISSUE TITLE
 visibility of values with 0 occurrences

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#7]
On the Utterance Search page, items with 0 occurrences are still visible.

e.g.

![screen shot 2017-10-04 at 11 15 26 am](https://user-images.githubusercontent.com/13629122/31183709-627e5100-a8f5-11e7-9cc4-3ff701e65b46.png)

**Comment by kwasiopoku** [comment]
Fixed & confirmed
