### ISSUE TITLE
BUG - Hands are sometimes reversed  (right vs. left) in Sign Bank display

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#72]
The display order should be

[Right-hand]  [left-hand]   IMAGES   [Right-hand]  [left-hand]

Sometimes this is correct, but sometimes it is reversed!

<img width="769" alt="screen shot 2018-03-07 at 5 27 16 pm" src="https://user-images.githubusercontent.com/13629122/37121980-dc19b1d4-222c-11e8-90bc-b76f26fcd18a.png">

<img width="909" alt="screen shot 2018-03-07 at 5 22 27 pm" src="https://user-images.githubusercontent.com/13629122/37121995-e556c4f8-222c-11e8-84d6-d9ebd98ff2cb.png">

**Comment by cneidle** [comment]
The citation-form signs seem to be correct.  The problem seems to involve a random set of examples from the continuous signing video.

**Comment by kwasiopoku** [comment]
Remove non-dominant hand sign data in SignBank_Occurrence from signbank search results for continuous sign results.  (Limit search results to id_Field=10000)

**Comment by kwasiopoku** [comment]
Fixed
