### ISSUE TITLE
BUG in connection between SignStream Sign Bank and Utterances in the DAI2 Sign Bank

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#73]
Hi,

I was demoing the latest version of SignStream (v15) yesterday,
and discovered that the connection between the SignStream
Sign Bank lookup and the Web is broken.

Consider, e.g., looking up the occurrences of NEW

<img width="935" alt="screen shot 2018-03-13 at 7 46 15 pm" src="https://user-images.githubusercontent.com/13629122/37546108-c6c03d78-2941-11e8-90b5-e4edcd4d11a2.png">

Clicking on “view occurrences” brings this up:

<img width="828" alt="screen shot 2018-03-13 at 7 47 00 pm" src="https://user-images.githubusercontent.com/13629122/37546118-d4958d4a-2941-11e8-8caf-33770b99b284.png">

Play sign video, and play composite video, bring up correct videos.

But systematically the “view occurrences” command shows the wrong signs.

For example, for REALLY, what comes up is REDUCE.

We had discussed the importance of having unique identifiers for signs
that remain constant with new versions of the Sign Bank…   

Not sure if this is the source of the problem.  But the wrong results
seem to be close alphabetically to what is being sought, i.e., it
seems that we’re getting the wrong item from the list, but an item
that is “in the neighborhood”.

THANKS,
 Carol

**Comment by kwasiopoku** [comment]
Fixed
