### ISSUE TITLE
In Sign Bank (DAI 2), continuous signing examples are not being properly identified

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#75]
<img width="768" alt="screen shot 2018-04-15 at 4 38 53 pm" src="https://user-images.githubusercontent.com/13629122/38783095-aad4f59e-40cb-11e8-8b67-4521d3ca8ca3.png">

All of those are citation-form.

Here they are all mixed together:

<img width="828" alt="screen shot 2018-04-15 at 4 41 07 pm" src="https://user-images.githubusercontent.com/13629122/38783113-e5611dbe-40cb-11e8-8c9b-5ebc1602f41a.png">

<img width="824" alt="screen shot 2018-04-15 at 4 41 13 pm" src="https://user-images.githubusercontent.com/13629122/38783112-dc2deefc-40cb-11e8-88d8-e65abc52b91e.png">

**Comment by kwasiopoku** [comment]
Fixed and deployed to DAI server

**Comment by cneidle** [comment]
Beautiful

Thanks!
  Carol
