### ISSUE TITLE
Dropdown on sign search summary is no longer working

### ISSUE THREAD

**Issue by kwasiopoku** [DCS-LCSR/ASL-DAI#76]

**Comment by cneidle** [comment]
Hi Augustine,  I thought you had fixed this, but it is again not working for me...Just FYI

![screen shot 2018-04-27 at 10 17 57 am](https://user-images.githubusercontent.com/13629122/39367354-7fac3426-4a04-11e8-83fc-043c15aafe86.png)

**Comment by cneidle** [comment]
Seems to be working now...
