### ISSUE TITLE
Menus - not working

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#77]
These menus don't work, FYI:

<img width="400" alt="screen shot 2018-04-16 at 2 42 09 pm" src="https://user-images.githubusercontent.com/13629122/38828547-647310f4-4184-11e8-8d77-1ac831c4ab19.png">

Reset password here also goes to the wrong place:  

<img width="773" alt="screen shot 2018-04-16 at 2 44 06 pm" src="https://user-images.githubusercontent.com/13629122/38828640-ae2c771c-4184-11e8-8235-ce59f7820969.png">

THANKS.

**Comment by cneidle** [comment]
These should open in their own windows:

NCSLGR - should point to http://secrets.rutgers.edu/dai/queryPages/querySelection.php

ASLLVD - should point to http://secrets.rutgers.edu/dai/queryPages/search/search.php

ASLLRP - should point to http://www.bu.edu/asllrp/

Right now the text in those menus also gets cut off, btw.

**Comment by kwasiopoku** [comment]
Fixed
