### ISSUE TITLE
Sign Bank:  View Sign Video does not work

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#8]
In both Chrome and Firefox, clicking on the View Sign Video button has not effect

![screen shot 2017-10-04 at 11 19 59 am](https://user-images.githubusercontent.com/13629122/31183942-13120ef8-a8f6-11e7-9741-b3a87d9a6b3f.png)

**Comment by kwasiopoku** [comment]
@cneidle This is fixed and pushed to prod
