### ISSUE TITLE
Very quick (but important) fix needed:  spelling!

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#80]
"Utterance" is misspelled in the Sign Bank buttons

<img width="248" alt="screen shot 2018-04-28 at 7 55 48 am" src="https://user-images.githubusercontent.com/13629122/39396321-20fab306-4aba-11e8-8f57-0c3326a7e58c.png">

thanks

**Comment by kwasiopoku** [comment]
Fixed
