### ISSUE TITLE
reminder:  changes in wording for statistics

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#81]
<img width="518" alt="screen shot 2018-04-29 at 12 58 17 pm" src="https://user-images.githubusercontent.com/13629122/39409003-08eb6ece-4bad-11e8-824f-d1464331ce98.png">

 Should be (with slightly improved wording) as follows -

Number of  ...
-----------------------
Primary entries for signs
Distinct sign entries/variants
Sign tokens

thanks!

**Comment by cneidle** [comment]
Model for labeling the lefthand column above:

<img width="760" alt="screen shot 2018-05-01 at 11 26 11 am" src="https://user-images.githubusercontent.com/13629122/39479223-8e235cec-4d32-11e8-8503-ab400c8678b9.png">

**Comment by cneidle** [comment]
Note also that it would be good to remove the "(dominant)" from every row in all the tables, in favor of a single note like the one above.   THANKS.

**Comment by cneidle** [comment]
Also, something is wrong here:

There cannot be reduplicated finger spelled signs (and a search for them shows none):

<img width="762" alt="screen shot 2018-05-01 at 11 55 14 am" src="https://user-images.githubusercontent.com/13629122/39480584-a6b2cec4-4d36-11e8-8174-ab3b604b8970.png">

**Comment by cneidle** [comment]
When I searched for fingerspelled signs, I found 186 examples (the first is an error in the annotations, which I will fix!).  Compare with 198 listed above.   Not consistent... 

<img width="451" alt="screen shot 2018-05-01 at 12 04 10 pm" src="https://user-images.githubusercontent.com/13629122/39481002-f76aa07a-4d37-11e8-99b1-c10fa9737d61.png">
<img width="446" alt="screen shot 2018-05-01 at 12 04 17 pm" src="https://user-images.githubusercontent.com/13629122/39481008-fb5e68b0-4d37-11e8-96f6-c37c76176b09.png">

**Comment by cneidle** [comment]
Number of loan signs matches, but classifiers are way off (without mentioning the first one, which needs to be corrected in the annotations):

<img width="314" alt="screen shot 2018-05-01 at 12 23 59 pm" src="https://user-images.githubusercontent.com/13629122/39481779-8efd1e3e-4d3a-11e8-98c8-706ab1ac6957.png">

**Comment by cneidle** [comment]
Statistics still do not add up - see my email.

Also please remove ("dominant") from the next-to-last table.

thanks.

**Comment by kwasiopoku** [comment]
Fixed
