### ISSUE TITLE
Small, non-urgent change needed - to handshape palette for queries in the DAI

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#82]
<img width="313" alt="screen shot 2018-04-29 at 7 20 47 pm" src="https://user-images.githubusercontent.com/13629122/39411988-77a8014e-4be2-11e8-8d71-a1575933aa35.png">
Delete the very last option "delete handshape"

That was for editing in Ashwin's system.  It doesn't correspond to anything one could search for in our current system.

Thanks!

**Comment by kwasiopoku** [comment]
Fixed
