### ISSUE TITLE
Please see my email message about help text, etc., with subject like "five things" - thanks!

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#84]

**Comment by cneidle** [comment]
---------- Forwarded message ----------
From: Carol Neidle <carolneidle@mac.com>
Date: Sun, Apr 29, 2018 at 1:59 PM
Subject: 5 and a half (small) things
To: Augustine Opoku <augustine.opoku@gmail.com>


1. We need to slightly revise the wording for the DAI 2 OVERVIEW screen 

OVERVIEW (for DAI 2)


**Current wording:**

This new Web interface, including many enhancements relative to our original Data Access Interface (DAI)and providing access to new data sets and a new Sign Bank, is being released as a Beta version. Development is ongoing, and we anticipate that a full release will be available by January 2018.

The data sets provided here are still in the very final stages of verification. They are provided as is for those who may be interested in browsing at this point. The final release of the interface may include minor corrections.

There is a Sign Bank feature, which will also, by the final release, be expanded to include signs from our new corpora of continous signing that were not in the original Sign Bank collection.

If you would like to be notified when the final version of the DAI 2 is released, please send that request to carol@bu.edu.



====

**I suggest replacing the above by the following:**

This new Web interface, including many enhancements relative to our original Data Access Interface (DAI)and providing access to new data sets and a new Sign Bank, is being released as a Beta version. Development is ongoing.

The data sets provided here are still in the very final stages of verification. They are provided as is for those who may be interested in browsing at this point.

There is a Sign Bank feature, which is based on the ASLLVD (citation-form signs) <http://www.bu.edu/av/asllrp/dai-asllvd.html>, but is in the process of being expanded to include signs from our new corpora of continuous signing that were not in the original Sign Bank collection.



_____________________________________________________________________

3.  We will need to modify the HELP text with respect to logging in.

**Current text:**

How do I log onto the DAI 2?
Only designated users from the partner institutions developing DAI 2 will be able to login in. Those users should register on the DAI 2. Such users can click the "New Account" button on the home page to register.


**Suggested modification:**

How do I log onto the DAI 2?
It is not necessary to establish an account in order to use the DAI 2.
However, to use the download features, you will need to have an account and be logged in.  This is so that the system can keep track of your download cart and downloads in progress.  If you wish to set up a login, you should register on the DAI 2. Click the "New Account" button on the home page to register.





4.  Additional change needed to the Help text.

**Current text:**

What is the DAI 2 (Beta) ?

The new DAI 2 provides a Web interface to permit browsing, searching, and (soon) downloading of linguistically annotated data. There are many new features relative to the original DAI, not all of which have yet been implemented. Development is ongoing, and we anticipate a full release by January 2018. If you would like to be notified when the final version of the DAI 2 is released, please send that request to carol@bu.edu. 

The data currently accessible through DAI 2 are from the ASLLRP SignStream® 3 corpus, with multiple synchronized video views of continuous signing (utterances (currently) and narratives and dialogs (coming in the future)) of native ASL signers. These video files have been linguistically annotated using SignStream® 3 and are being shared through this interface as the annotations are completed. The first set of data that is being offered is now in the final stages of verification and are provided as is for those who may be interested in browsing at this point. The final release of the interface will include minor corrections, as well as additional new data. 

One exciting new feature is a new ASLLRP Sign Bank, which allows a search of the American Sign Language Lexical Video Dataset (ASLLVD), with examples of almost 3,000 signs in citation form, with multiple examples of each sign produced by up to 6 signers. Further information about the ASLLVD is available here. 

The Sign Bank will also, by the final release, be expanded to include signs from our new ASLLRP SignStream® 3 corpus of continuous signing that were not in the original Sign Bank collection. 
The Sign Bank can also be accessed by SignStream® 3 users from within the application. 
Anyone accessing the ASLLRP SignStream® 3 corpus or the ASLLRP Sign Bank must agree to the Terms of Use.



**Proposed replacement text:**

What is the DAI 2 (Beta) ?

The new DAI 2 provides a Web interface to permit browsing, searching, and downloading of linguistically annotated data. There are many new features relative to the original DAI, not all of which have yet been implemented. Development is ongoing.

The data currently accessible through DAI 2 are from the ASLLRP SignStream® 3 corpus, with multiple synchronized video views of continuous signing (utterances (currently) and narratives and dialogs (coming in the future)) of native ASL signers. These video files have been linguistically annotated using SignStream® 3 and are being shared through this interface as the annotations are completed. The first set of data that is being offered is now in the final stages of verification and is provided as is for those who may be interested in browsing at this point. New data sets are being added as the verifications are completed, so this is an expanding data set. 

One exciting new feature is a new ASLLRP Sign Bank, which allows a search of the American Sign Language Lexical Video Dataset (ASLLVD), with examples of almost 3,000 signs in citation form, with multiple examples of each sign produced by up to 6 signers. Further information about the ASLLVD is available here. 

The Sign Bank is also being expanded to include signs from our new ASLLRP SignStream® 3 corpus of continuous signing that were not in the original Sign Bank collection. This expansion is ongoing.
The Sign Bank can also be accessed by SignStream® 3 users from within the application. 
Anyone accessing the ASLLRP SignStream® 3 corpus or the ASLLRP Sign Bank must agree to the Terms of Use.


5.  Additional change needed to the Help text.

How do I download materials?

**Current text**

The download cart is not yet implemented in the Beta version. Stay tuned... This will be coming soon.


**Suggested replacement text:**    Whatever you think will be appropriate !!!

**Comment by kwasiopoku** [comment]
Fixed
