### ISSUE TITLE
Sign Bank:  Odd behavior - after hitting <enter> for a search

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#9]
When I enter text in the "Key word" box and hit Enter, the handshape palette opens up.  Not sure why this is happening; It should happen only if the user clicks on one of the handshape boxes.

Happens with both Firefox and Chroms
![screen shot 2017-10-04 at 11 23 26 am](https://user-images.githubusercontent.com/13629122/31184113-80a9d7ac-a8f6-11e7-9748-fcde3ccdb8f9.png)

**Comment by kwasiopoku** [comment]
Fixed
