### ISSUE TITLE
Correction needed to ASLLVD entries: GOOD/THANK-YOU  grouping adjustments (manual)

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#92]
Please see attached.

[GOOD_THANK-YOU.pdf](https://github.com/DCS-LCSR/ASL-DAI/files/2156313/GOOD_THANK-YOU.pdf)

**Comment by cneidle** [comment]
This is one of those that required post-processing, to correct an error in the Ashwin data set.  But currently this is what is appearing.   We should discuss, when higher priority items have been addressed :-).  THANKS!

<img width="984" alt="screen shot 2018-08-01 at 9 54 28 am" src="https://user-images.githubusercontent.com/13629122/43525975-1ec907f2-9571-11e8-9bd7-8eda6905f97e.png">

**Comment by kwasiopoku** [comment]
Fixed

**Comment by cneidle** [comment]
This fix (and perhaps others intended for post-processing) still needs to be made... 
THANKS.  

See the pdf linked in above for details.
