### ISSUE TITLE
Correction needed to ASLLVD entries:  issue with SignBank entry for WORK

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#94]
There is a correction needed to the annotations for the Sign Bank entry for WORK.

Low priority relative to the rest of what is being worked on, but just to remember:

<img width="624" alt="screen shot 2018-07-04 at 12 13 02 pm" src="https://user-images.githubusercontent.com/13629122/42287301-cf959b1c-7f83-11e8-8095-43ba545c466c.png">

There is also an issue with the canonical example for GUILTY.  The annotation is missing a +.

**Comment by cneidle** [comment]
This one needs to be WORK+ rather than WORK:

<img width="888" alt="Screen Shot 2022-09-02 at 2 58 38 PM" src="https://user-images.githubusercontent.com/13629122/188219943-cbd93656-bf5f-4961-a35e-3c54d5cf1143.png">

**Comment by kwasiopoku** [comment]
This has been updated on dev1.cs

**Comment by cneidle** [comment]
No- I am not seeing the extra plus with 

<img width="769" alt="Screen Shot 2022-10-15 at 10 46 14 AM" src="https://user-images.githubusercontent.com/13629122/195992650-bfb14187-212d-46fd-ba7d-5c00f8a383d0.png">

**Comment by kwasiopoku** [comment]
Sorry for the confusion.  The correct sign has now been updated

**Comment by cneidle** [comment]
not visibly in dev1

<img width="306" alt="Screen Shot 2022-10-15 at 11 43 56 AM" src="https://user-images.githubusercontent.com/13629122/195995423-edff2a17-c81f-446e-a29d-7a34329ef68b.png">

**Comment by cneidle** [comment]
oops sorry - wrong ticket!  never mind !!

**Comment by cneidle** [comment]
WORK+ looks good.   thanks !!!
