### ISSUE TITLE
Quick fix needed to UI - Utterance video window front view in the DAI

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#95]
is incorrectly labelled as "face view".  Would be great to fix that one word.

<img width="582" alt="screen shot 2018-07-05 at 7 16 09 pm" src="https://user-images.githubusercontent.com/13629122/42352510-e86b5b30-8088-11e8-989b-b775693c1dd2.png">

**Comment by kwasiopoku** [comment]
Fixed

**Comment by cneidle** [comment]
Hi Augustine.  I thought this was fixed -- but here it is again.

<img width="1437" alt="screen shot 2018-07-24 at 3 16 37 pm" src="https://user-images.githubusercontent.com/13629122/43161012-d070857a-8f54-11e8-83ef-97821852d87f.png">

**Comment by kwasiopoku** [comment]
Fixed

**Comment by cneidle** [comment]
looks good :-)
