### ISSUE TITLE
Enhancement for the future:  Ability to search the translation field

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#97]
Would be nice to be able to search the translation field from within the DAI...  We can discuss at some point in the future when higher priority items have been dealt with.  Thanks.

**Comment by kwasiopoku** [comment]
This is complete and has been pushed to the DAI site.

**Comment by cneidle** [comment]
Hi Augustine,

Looks beautiful!

I just have one question about the logic, which we can discuss at your
convenience.

I think it would be helpful to have  “search all data” at the very top.

Then everything else should be “limit to… “  where everything is additive, i.e.,
  all selected limit conditions apply simultaneously.

SO:


SEARCH ALL DATA

LIMIT TO:  

[note that all checked options will be applied to the search]
_______

[ ]  character string in the translation field 

_______

[ ]   grammatical constructions

_______

[ ]  non-manual markings

_______

[ ] data source

_______

[ ]  participant

_______

[ ] video properties (not yet implemented)


	


Because right now, suppose you wanted to search for something in the translation
field of a sentence that had no non-manual markings and no grammatical markings,
the result would not show up.  Admittedly quite rare, but the above uniform logic
seems more appealing anyway.


We can discuss further.  Not urgent, but just a suggestion :-)


Thanks very much.

Best,
 Carol
