### ISSUE TITLE
Statistics page:  Number in top and bottom chart don't match

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#98]
http://dai.cs.rutgers.edu/dai/s/runningstats

Column 1 of the top chart should be consistent with what is shown below...

It's very close, but not exact for lexical signs and classifiers.

3883 lexical signs shown above; 3885 shown below (1 or 2 handed)
81 classifiers shown above; 74 shown below (1 or 2 handed)

<img width="307" alt="screen shot 2018-07-22 at 11 03 01 am" src="https://user-images.githubusercontent.com/13629122/43047003-57660382-8d9f-11e8-8324-eb0bc8a88231.png">

<img width="953" alt="screen shot 2018-07-22 at 11 04 56 am" src="https://user-images.githubusercontent.com/13629122/43047006-5d69a57c-8d9f-11e8-9956-583341f61d01.png">

thanks.

**Comment by kwasiopoku** [comment]
Fixed

**Comment by cneidle** [comment]
Statistics are still off -- by a little for classifiers

<img width="403" alt="screen shot 2018-08-01 at 6 49 38 am" src="https://user-images.githubusercontent.com/13629122/43517541-1619d740-9557-11e8-9e33-d86a3949f885.png">

<img width="311" alt="screen shot 2018-08-01 at 6 43 08 am" src="https://user-images.githubusercontent.com/13629122/43517472-d1abe7e2-9556-11e8-8108-f9585aac00e2.png">

<img width="700" alt="screen shot 2018-08-01 at 6 44 16 am" src="https://user-images.githubusercontent.com/13629122/43517471-d19b37bc-9556-11e8-80d3-edf4138b3348.png">

79 (on top) appears to be the correct number, based on a DAI search for all classifiers.

<img width="295" alt="screen shot 2018-08-01 at 6 55 40 am" src="https://user-images.githubusercontent.com/13629122/43517815-faa4f6a6-9557-11e8-9bae-9b8f6659ec4b.png">
__
