### ISSUE TITLE
Searching for "number signs" still does not work - there are actually some...

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#99]
Not only does a search for number signs come up empty (when it shouldn't), but none of the number signs show up in search results even when searched for otherwise (e.g., by their gloss label alone).

Number signs seem to be ineligible to appear in any search results. These examples do, however, show up in the Sign Bank.  I have verified that they are correctly annotated as number signs within SignStream.

<img width="787" alt="screen shot 2018-07-22 at 11 23 00 am" src="https://user-images.githubusercontent.com/13629122/43047271-b843961c-8da2-11e8-8502-8a025c5f1786.png">

<img width="806" alt="screen shot 2018-07-22 at 11 25 15 am" src="https://user-images.githubusercontent.com/13629122/43047274-bdadf822-8da2-11e8-8a50-edad766a2845.png">

<img width="1214" alt="screen shot 2018-07-22 at 11 28 18 am" src="https://user-images.githubusercontent.com/13629122/43047276-c362b4a6-8da2-11e8-8fb2-3884f2d7fa6d.png">

<img width="867" alt="screen shot 2018-07-22 at 11 32 21 am" src="https://user-images.githubusercontent.com/13629122/43047284-fa3361e2-8da2-11e8-8fe5-1cf0018ea688.png">

**Comment by kwasiopoku** [comment]
Fixed
